### ISSUE TITLE
Test TImeout Adjustments

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1008]
I have no idea why but the mdsobjects/cpp/MdsConnectionTest.cpp test application fails often for various reasons. Sometimes the log shows the client connected to the server but the test returns failure but most of the time the test fails with a connection timeout. There are no obvious reasons why and very little information in the log to even attempt to diagnose the problem. Pull request tests now have to be retested multiple times mostly because of this test.

**Comment by tfredian** [comment]
Related to this issue is that it is unclear how best to extend default timeouts. I added a --test_timeunit=factor option to the trigger and build scripts but it is hard to tell if this is actually working. I don't know exactly how this is used but it would be very useful if tests that report timeout errors would indicate the actual time limit that was in use when the test timed out.

**Comment by tfredian** [comment]
I suspect that the --test_timeunit=factor setting is not working or at least not as expected. Trying --test_timeunit=5000 on a build ended up again failing in the MdsConnectionTest in with a timeout after only a couple seconds.

**Comment by tfredian** [comment]
It appears that setting environment variable TEST_TIMEUNIT may be the culprit.  If the --test_timeunt option is not set the docker image runs with TEST_TIMEUNIT="" and that apparently behaves differently than if the environment variable is not defined. For now the platform_build script is not setting TEST_TIMEUNIT at all therefore disabling the build option. The timeouts disappeared after making this change.

**Comment by tfredian** [comment]
It would be useful if it were possible to adjust test timeout periods using options to the trigger.sh and/or build.sh scripts. The length of the timeout might be dependent on the performance of the system doing the build so implementing something like --test_timeunit=n would be useful. Simply defining the environment variable TEST_TIMEUNIT=n does not appear to work and actually seems to shorten the timeout periods causing more timeout failures with n > 1.

**Comment by tfredian** [comment]
More test timeout issues...
I extended the test timeout of MdsConnectionTest to 60 seconds with:

    int main(int argc UNUSED_ARGUMENT, char *argv[] UNUSED_ARGUMENT)
    {
        TEST_TIMEOUT(60);
    ...

I am still getting intermittent test failures and strangely the connection test failed much quicker than the 60 second setting:

The test log files contains:
      ,---------------------------------------. 
       |     MDSplus unit testing...           | 
       '---------------------------------------' 
      
       Running in suite: /source/mdsobjects/cpp/testing/MdsConnectionTest.cpp
      
       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
      
      started mdsip server on port: 8101 pid: 10119
      Thu Aug 17 13:23:46 2017 (6) (pid 10119) Connection received from Linux User@localhost [127.0.0.1]
      Connected: Linux User
      terminate called after throwing an instance of 'MDSplus::MdsException'
        what():  %MDSPLUS-E-ERROR, Error
      attempt to connect to: tcp://localhost:8101
       -- [Connection] -- 
      
       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
      
      0%: Checks: 1, Failures: 0, Errors: 1
      /source/mdsobjects/cpp/testing/MdsConnectionTest.cpp:50:E:Connection:test_main:0: (after this 
      point) Received signal 6 (Aborted)
      
       -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

      FAIL MdsConnectionTest (exit status: 1)

and the console log shows:

    00:07:45.450 PASS: MdsEventTest
    00:07:51.491 FAIL: MdsConnectionTest
    00:07:51.514 PASS: MdsExpressionCompileTest

where the times are delta times. This shows that the MdsConnectionTest failed in about 6 seconds. Is the test timeout not working as expected? I assume "Signal 6 (Aborted)" is caused by a test timeout.

**Comment by tfredian** [comment]
Python tasks with timeout problems. It appears that tasks which execute python code still have a race condition that can cause deadlock. If I recall this is related to dbid context locking in the python code. The mdsobjects/python/tests/dclUnitTest intermittently deadlocks doing tasks in the test device which has a timeout specified. I may investigate changing the TdiDoTask code to not do the task in a separate thread but instead do the task in the thread which called TdiDoTask. This would entail starting a thread which waits for the timeout period and then sends a signal to the thread executing the task. Perhaps this would prevent the locking issues since the timeout thread would not be doing any locking.

**Comment by AndreaRigoni** [comment]
Hi Tom,
 I think I've found .. the fix should be running in https://github.com/MDSplus/mdsplus/pull/1014

**Comment by tfredian** [comment]
Testing jenkins - ignore
