### ISSUE TITLE
read error when reading segments with no Dimension

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1011]
You can write Segments with null dimensions
```python
node.beginSegment(start,end,None,data)
```
which is great for data that does not require a dimension.

however, reading such a segmented node with e.g.
```python
node.record
```
will result in a memory access violation.

expected behavior:
return
```tdi
Signal(concatenated_data, *, *)
```
similar to
```python
node.getSegment(i)
```
which returns
```tdi
Signal(data_i, *, *)
```

Issue is addressed but not yet entirely fixed by pr #1010

**Comment by tfredian** [comment]
If this is still an issue please reopen adding more details.
