### ISSUE TITLE
Wrong length reported for segmented nodes in NCI

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1036]
When a tree node contain segments, the NCI fields LENGTH and RLENGTH do not contain correct values. RLENGTH and LENGTH appear to contain always  0 and  29, respectively.

**Comment by tfredian** [comment]
I'm not sure but I suspect this broke when TreeSegments.c was modified to use a lot of macros. It's a bit difficult to debug with gdb now since the length handling is done mostly inside macros.

**Comment by zack-vii** [comment]
supposed to be fixed with PR #1068
