### ISSUE TITLE
Strange jTraverser script behaviour

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#1039]
Hello,

I have a broken jTraverser script in my /usr/local/mdsplus/bin directory. I think the script is derived from the template

mdsplus/javatraverser/jTraverser.template

just by removing the file extension. It seems to me that my file contains a couple of errors: "}" instead of "|" and "64i-bit" instead of "64-bit", both at line number 8.

Moreover, on my installation, the corrected or not corrected script always results in the variable lib to be assigned the string "lib64", which is wrong, because MDSplus libraries are in fact installed under /usr/local/mdsplus/lib/.

If the libraries are not installed in the system directories but under the local/mdsplus directory tree, the preamble seems to me totally useless. I can imagine that the name of that directory does not change with the machine word size.

In case I am wrong (and I really have some installation problems), here are some info about my system which may help to solve this issue.

```
$ uname --all
Linux xdcren03 4.10.0-33-generic #37-Ubuntu SMP Fri Aug 11 10:55:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ file -L /usr/bin/java
/usr/bin/java: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=9f77390a9146e5370c8e36f6148c7bcf8a9189cc, stripped
```

Sincerely,

**Comment by alkhwarizmi** [comment]
I think that this and issue number #995 could be related.

Also, within kde over ubuntu 16.04, the /etc/profile.d scripts are not called for non-login shells. In order to see the correct environment 
```
sudo -u <username> -i
```
is required.

Sincerely

**Comment by GabrieleManduchi** [comment]
Ciao Anton,
 check out the latest alpha. The problem you reported has already been fixed in a commit on Sept 13
