### ISSUE TITLE
Support for new D-Tacq models (from Columbia - U)

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1055]
Hi Josh,
    Our research group is planning to order new D-tAcq hardware for HBT-EP, and I wanted to see if some modules are compatible with input/output control from MDSplus.  Our first intent is to use these in a standalone GPU-based feedback control system that doesn't use MDSplus (based on GPU controller presently used at HBT-EP and DIII-D), but we also would like to know MDSplus compatibility for upcoming input/output needs.  Our CAMAC hardware has been fraught with problems that are getting worse, and I want to scope out a replacement.  The D-tAcq modules from a quote we received are as follows:

- ACQ2106: motherboard/FPGA/chasssis. 1U x 19”, includes 100W external PSU, ZYNQ 7030 FPGA, embedded Linux, gigabit Ethernet.
-- This sounds similar to the housing for our existing ACQ196CPCI units, so I'm guessing MDSplus would have no need to interface with this.
- ACQ424ELF-32 : 32 channel simultaneous analog input, sub 1usec capture latency, 16 bit, +/-10V differential input. Pin-out compatible with ACQ196CPCI.
-- This is the newer modular equivalent of our ACQ196CPCI units.  We have ACQ196's that work with our MDSplus right now, but the ACQ196 units are now becoming obsolete according to D-tAcq.
- AO424ELF-32 : 32 channel simultaneous analog output, 2usec latency in 32 channel mode, 1 usec in 16 channel mode. +/-10V output. Pin-out compatible with AO32CPCI (in 32 channel mode).
-- These can be used to output arbitrary waveforms, but a baseline of just TTL Triggers and Gates in MDSplus would be great.  Our initial control system will be independent of MDSplus, but if we can use duplicates of these with MDSplus, it will save us from lots of downtime that we often experience.
- We're also looking at AO424ELF-16, which is the faster (1usec latency) 16-channel alternative.
- MGT482: SFP fiber optic adapter, 6Gbps.
-- This sounds like a a module that wouldn't interact with MDSplus, and might just be needed for our GPU-based control system.

    We also presently have two AO32CPCI units that run in a feedback loop independent of MDSplus.  If the bundled system above works well, we will probably want to re-purpose the AO32CPCI units to replace the output functionality of our CAMAC J221/222 modules if possible.  It would be great if these work with MDSplus with just triggers and gates, since they could be added seamlessly to our existing machine operation.

Thank you,
Jeff Levesque
Associate Research Scientist
Columbia University Plasma Physics Laboratory
JPL2131@columbia.edu
(212) 851-5937

**Comment by joshStillerman** [comment]
Jeff -
   Native MDS plus support for these devices is not yet available.  That said, they should be very similar in operation to the existing ACQ196 devices, so it should not be too difficult.  The boards / chassis sit on the ethernet, and accept similar commands to the existing boards.

  I know that some sites: EAST and KSTAR are using some of these boards with their own custom software, but do not know the details.

  I know that W7X has some of this hardware, but I am not sure of the state of the software support.
  The boards (like the previous generations) do support MDSplus natively, and could be used with onboard scripts to write to trees directly.  In the past, this has not been my preferred method for operating them.

  I have an ACQ1001Q (small chassis) and a ACQ435-32FF on loan from D-Tacq, and plan to do MDSplus software for it.

  What is your schedule for this?

-Josh

**Comment by joshStillerman** [comment]
Timo writes:
we have driver that are working so far. available on mds-control /git/MDSplusW7X/devices/acq4xx.py.
we plan on updating the once under w7xdevices. soon
 cheers

timo

**Comment by joshStillerman** [comment]
Timo -
  Both at MIT and at Columbia, we need support for these new modules.  D-Tacq has advised to only put the same model cards in each chassis.  This may make your device support model much more simple.  I could not, figure it out/ get it to work.  We have created a simple streaming daq module called ACQ435ST in HtsDevices.  And am about to create a ACQ437-6ST also.  I would be happy to use your code if it was available in the MDS distribution.  Would you clean out and refill W7xDevices with the non W7x specific ones you have developed.

**Comment by zack-vii** [comment]
acq4xx.py in pydevices/dtacq
also streaming devices have been added but notbassigned to this issue
