### ISSUE TITLE
Contour Level float vs double

### ISSUE THREAD

**Issue by kgerickson** [MDSplus/mdsplus#1090]
https://github.com/MDSplus/mdsplus/blob/a5fc88a03497ff026faa15218125e020e98702a5/javascope/jScope/Signal.java#L1517

level is a double here, but implicitly cast to float and elsewhere used as float.  Which is correct?  If countour points should be double, then they should be double everywhere, and not switched back and forth implicitly between float and double.

**Comment by GabrieleManduchi** [comment]
Reported in code
