### ISSUE TITLE
Code has no effect

### ISSUE THREAD

**Issue by kgerickson** [MDSplus/mdsplus#1091]
https://github.com/MDSplus/mdsplus/blob/6de0f3b4654dcf49bdb5773482387d55b157894a/javascope/jScope/Waveform.java#L299

The line:

      this.font = wave.font;

has no effect, since font is static and refers to the same member.  Is this intended?  Either font is supposed to be static and the line of code should be removed, or it's not and the static keyword should be removed (with a lot of testing of the fallout from that).

**Comment by GabrieleManduchi** [comment]
True, that line can be removed. I will do it soon.

**Comment by GabrieleManduchi** [comment]
Reported in code
