### ISSUE TITLE
Interface MDSplus with LabVIEW- Needs MDSobjectsLVShr.dll library

### ISSUE THREAD

**Issue by tyyao** [MDSplus/mdsplus#1103]
Hello all,

I would like to interface LabVIEW with MDSPlus. The tutorial on the mdsplus.org website says to make sure that library MDSobjectsLVShr.dll is present. 

I have MDSplus-7.7-7 installed on my computer and I installed Java Runtime Environment 1.8.0_151 as well. I checked inside the MDSPlus file folder that was created by the installation, and I could not find the .dll file inside. Where can I find this .dll file to download and make it present on my computer?

Many thanks for your help,
Tiffany

**Comment by tfredian** [comment]
Hi Tiffany,

The MDSplus libraries are now installed in C:\System32 on windows. If 
you included the LabVIEW option during the MDSplus installation then 
that library should be installed there and be found by LabVIEW.

-tom

**Comment by tyyao** [comment]
Tom,

Thank you for showing me how to find the right library. This solves my issue.

Many thanks,
Tiffany
