### ISSUE TITLE
Save text to node using LabVIEW

### ISSUE THREAD

**Issue by tyyao** [MDSplus/mdsplus#1112]
Hello all,

I am new to using LabVIEW to interface with MDSplus. Although my LabVIEW VI can save numeric type data into nodes in MDSplus, I cannot find a function in the LabVIEW MDSplus library that could save a string into a text type data in my MDSplus tree. Does anyone know which block/function I should use to do so?

Many thanks,
Tiffany

**Comment by gronchi** [comment]
You can use the "String Create.vi"  from the "MDSplus_LV2012\Library\Data\Scalar\String" folder, for instance; after creating the data,  you just need to put it on the Tree Node, as you do with numerical data.

**Comment by tyyao** [comment]
Thank you very much!
