### ISSUE TITLE
[enhancement] tree exploration tool

### ISSUE THREAD

**Issue by lamorton** [MDSplus/mdsplus#1126]
I made an attempt at developing a [simple Python tool](https://github.com/lamorton/MDSmonkey) that lets users explore a (new-to-the-user) tree using the full power of the IPython interpreter (particularly the tab-complete capability and the usual attribute-style access to mimic the MDSplus path style). Additionally, the data is loaded into `xarray` datasets on-demand.   The [xarray data model](https://github.com/pydata/xarray) is a very natural fit for the kind of array-based data (with array-based metadata like dimensions and error bars) that MDSplus often houses. 

There's still a fair bit to be done.  My implementation is done on top of the thick-client OOP MDSplus interface, which in retrospect was a less-portable choice. Additionally, the inference mechanism that attempts to construct a valid `xarray` dataset from a node in the MDSplus tree (especially assigning correct names for dimension arrays based on the names of nodes associated to those arrays) was developed specifically for the style of MDSplus tree used by NSTX / NSTX-U, and I've run into some issues testing it on MST. 

Nonetheless, I wanted to make you aware of this, because several sets of users ([OMFIT](https://github.com/gafusion/OMFIT-source/blob/unstable/src/classes/omfit_mds.py), the Fusion Data Project at PPPL, some MST users, and probably others) have done similar things indicates that we should think about adding some functionality like this to the MDSplus Python library itself. Additionally, if I have replicated some functionality that already exists in MDSplus, please let me know, and I would be glad to help edit the landing page to show new users how to find and use it.

**Comment by joshStillerman** [comment]
Hi -
  This is very interesting.  Consider creating a pull request for it. 

NOTE: There is a new library for remote objects based on rpyc that allows the use of the full python MDSplus objects from remote systems.  EVEN IF THEY Do not have MDSplus installed !

See the mdsconnector object, discussed here: https://github.com/MDSplus/mdsplus/issues/1074
and available from pip:
https://libraries.io/pypi/mdsconnector

**Comment by lamorton** [comment]
Josh, 
Thanks! I've been working on a thin-client version, which I think will be superior.  However, I'm still struggling to find a satisfactory resolution to the data model mismatch between MSDplus and xarray.  Do you have a development branch that I could submit the pull to?  

Hmm, I'll have to check this SSH version out.  
Lucas

**Comment by joshStillerman** [comment]
The alpha is our development branch.  You can make a PR to it, or if it 
is more appropriate, let this application just stand alone. Depending on 
if you want it to eventually be distributed with MDSplus.

The thin-client is a functional as opposed to object based interface.  
It has some good performance characteristics when used over wide area 
networks.

The remote objects just make small proxy objects locally, and all of the 
object stuff is done on the server.  When the application calls a method 
that returns an answer, the server, packages up the answer and sends it 
over the wire to the client.

The connection time is long, but once connected it runs pretty fast.

**Comment by joshStillerman** [comment]
Did you make progress on this ?

**Comment by lamorton** [comment]
I have a prototype but it doesn't yet handle all the cases. 'xarray' needs to know which dimension-array corresponds to which axis of the data array before it can construct the 'xarray' object.  MDSplus doesn't require/allow the tree creator to provide enough information to do this.  Therefore, it's not always possible to programmatically convert from MDSplus arrays to xarrays.  I've set a default for when this failure occurs -- just returning a dictionary containing all the arrays.  I'm not satisfied with this solution, because it is type-unstable, but I don't feel like working on it anymore.

**Comment by zack-vii** [comment]
I think we should promote this feature in the third party contribution part if mdsplus.org. 
MDSplus now has tab-completion builtin but the xarray stuff may be of interest.

**Comment by zack-vii** [comment]
I added it to http://www.mdsplus.org/index.php/User_Contrib:downloads
@lamorton : Please keep your github version maintained.
