### ISSUE TITLE
Remove unneeded #ifdef __WIN32 code fragments

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1132]
Some, but not all, of the #ifdef __WIN32 code blocks can be removed from the code since all but the mdsobjects/cpp code is now compiled using only MinGW64 cross compilers. Each case must be carefully reviewed to ensure that it is no longer needed and can be removed. If the code in questions is not tested by an existing test either a new test should be added or at a minimum the code should be manually tested to ensure that removing the case doesn't break something.

**Comment by zack-vii** [comment]
addressed by pr #1136
