### ISSUE TITLE
valgrind crashes on fc25 32bit

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1151]
valgrind: m_scheduler/scheduler.c:1611 (vgPlain_scheduler): the 'impossible' happened.
valgrind: VG_(scheduler), phase 3: run_innerloop detected host state invariant failure

host stacktrace:
==23339==    at 0x3802B76E: ??? (in /usr/lib/valgrind/helgrind-x86-linux)
==23339==    by 0x3802B8C7: ??? (in /usr/lib/valgrind/helgrind-x86-linux)
==23339==    by 0x3802B9DC: ??? (in /usr/lib/valgrind/helgrind-x86-linux)
==23339==    by 0x3808A68A: ??? (in /usr/lib/valgrind/helgrind-x86-linux)
==23339==    by 0x3809CD57: ??? (in /usr/lib/valgrind/helgrind-x86-linux)

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable (lwpid 23339)

Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.

**Comment by tfredian** [comment]
This was due to a kernel bug in the fc23 host used to do the valgrind tests. It has been moved to a rhel7 host and now works.
