### ISSUE TITLE
Unable to create Tree using TCL in Windows 8.1

### ISSUE THREAD

**Issue by juhi1296** [MDSplus/mdsplus#1183]
I tried creating Tree using TCL in Windows 8.1 but I got the error. Following are the steps that i followed:

1. String Key in Regedit:
![screenshot 131](https://user-images.githubusercontent.com/20973858/34352192-1c22114a-ea47-11e7-81da-08361bfcf818.png)

2. Starting TCL and creating a new tree:
![screenshot 132](https://user-images.githubusercontent.com/20973858/34352258-7ceb9d3e-ea47-11e7-8e71-d6d91ecd79b9.png)

Please help!

**Comment by tfredian** [comment]
Make sure the C:\MYTREES folder exists and that you have write access. I just tried the following on my system:
'''
TCL> env my_tree_path=C:\mytrees
'my_tree_path'='C:\mytrees'
TCL> edit/new my_tree
Error: Unable to edit shot number -1 of the 'my_tree' tree
Error msg was: %TREE-E-FCREATE, Error creating new file.
mdsdcl: --> failed on line 'edit/new my_tree'
### Used Windows explorer and created the mytrees folder and then tried the command again ###
TCL> edit/new my_tree
TCL>
'''

The my_tree_path definition can be either a regular Windows User or System environment variable or one created in the registry like you did. The /new option is with a forward slash as you did in your first attempt. You can also use the help command in mdstcl for details.

Please close this issue if this solves your problem.
