### ISSUE TITLE
TDI Error

### ISSUE THREAD

**Issue by juhi1296** [MDSplus/mdsplus#1191]
Hello, I am learning TDI functions and I tried to create a simple function and use it, but its giving me the following error:

![screenshot from 2018-01-02 14-34-26](https://user-images.githubusercontent.com/20973858/34478991-0df84da4-efca-11e7-9538-d0e377d4febc.png)

![screenshot from 2018-01-02 14-36-00](https://user-images.githubusercontent.com/20973858/34479024-46c1bc2e-efca-11e7-9f1d-80de4765a7bd.png)

Please, help !!

**Comment by joshStillerman** [comment]
You had the syntax correct the on your first try,  You need the ().  Is 
your current default directory in your MDS_PATH environment variable ?  
This ENV is a ';' separated list of places to look for tdi (and python) 
functions.

Testing this I have found 2 things:

1 - t.py seems to supersede t.fun (i.e. it will use the .py if it is 
present)

2 - it tries hard to find / compile t.py before compiling t.fun. This 
results in a long delay, and a warning about not being able to find the 
module.

(2) is probably a bug.

(1) is something to be discussed at the next developer's meeting.

**Comment by juhi1296** [comment]
I created function in Python and still got the same error:
![screenshot from 2018-01-03 10-07-41](https://user-images.githubusercontent.com/20973858/34509268-25624b6c-f06e-11e7-8995-0eb6a4eba1d7.png)

![screenshot from 2018-01-03 10-08-03](https://user-images.githubusercontent.com/20973858/34509273-2e2b311e-f06e-11e7-805d-5e41401427a4.png)
![screenshot from 2018-01-03 10-08-32](https://user-images.githubusercontent.com/20973858/34509276-3442a302-f06e-11e7-853f-c12324f24e94.png)

**Comment by tfredian** [comment]
Your MDS_PATH definition is incorrect. First of all, the parts of MDS_PATH need to be separated by a semi-colon, not a colon. Second, the search for tdi functions is done by looking down the whole directory tree of the parts of the MDS_PATH environment variable so you should not need anything more than MDS_PATH=${MDSPLUS_ROOT}/tdi.

Also if you installed MDSplus using the repositories there should be a /etc/profile.d/mdsplus.sh which should automatically define most of the needed environment variables for MDSplus. If you have not installed from repositories then you can add the following line to your .bashrc

'''source /usr/local/mdsplus/setup.sh
'''

**Comment by tfredian** [comment]
Also the testing section of Josh's comment is not completely correct. It is true that python tdi functions supercede .fun files with the same name but that is the intended behavior. His problem with slowness was due to the fact that when he tested he define MDS_PATH to point to his home directory which caused MDSplus to search though huge numbers of directories over nfs which caused the poor behavior. Since MDSplus searches the directory trees under MDS_PATH parts, care should be taken to define MDS_PATH to point to directories containing only tdi functions.

**Comment by zack-vii** [comment]
@juhi1296: Did setting the MDS_PATH fix the problem for you?
