### ISSUE TITLE
Python thick-client error on compound signal with multiplier containing external function

### ISSUE THREAD

**Issue by lamorton** [MDSplus/mdsplus#1194]
On the NSTX-U MDSplus tree, the beam power signal is defined as a compound signal that references three other nodes:

> In[108]: node.getData()
> Out[108]: Build_Signal(\CALC_NB_1A_IACCEL * \CALC_NB_1A_VACCEL * \N1A_POWER:POWERFAC_1A, *, DIM_OF(\CALC_NB_1A_IACCEL))

Trying to get the actual data fails:

> In[109]: node.data()
> Traceback (most recent call last):
>     node.data()
>     File /p/fdp/anaconda/lib/python2.7/site-packages/mdsplus-7.0.70-py2.7.egg/MDSplus/mdsdata.py, line 537, in data
>     return self.execute("data($)",(self,)).value
>   File "/p/fdp/anaconda/lib/python2.7/site-packages/mdsplus-7.0.70-py2.7.egg/MDSplus/mdsdata.py", line 494, in execute
>     return _mimport('_tdishr',1).TdiExecute(expr,args)
>   File "/p/fdp/anaconda/lib/python2.7/site-packages/mdsplus-7.0.70-py2.7.egg/MDSplus/_tdishr.py", line 74, in TdiExecute
>     ans = TdiExecute(expression,args[0])
>   File "/p/fdp/anaconda/lib/python2.7/site-packages/mdsplus-7.0.70-py2.7.egg/MDSplus/_tdishr.py", line 91, in TdiExecute
>     raise TdiException(_mdsshr.MdsGetMsg(status,"Error compiling expression"))
> TdiException: %TDI-E-TdiUNKNOWN_VAR, Unknown/undefined variable name

I traced the problem to the node \N1A_POWER:POWERFAC_1A, which does the following:

> In[110]: pownode.getData()
> Out[110]: .001 * NB_POWERFAC(\CALC_NB_1A_VACCEL)

The type of this object is `MDSplus.tdibuiltins.builtins_other.MULTIPLY`.

When I try `pownode.data()`  I get the same error as above.  

Further, 

> In[127]: pownode.getData().args[1]
> Out[127]: NB_POWERFAC(\CALC_NB_1A_VACCEL)

Type:

> MDSplus.tdibuiltins.builtins_other.EXT_FUNCTION

However, using the thin-client mode I can directly get the data from the original `node` (evaluates to an float array) or from `pownode` (evaluates to a scalar float). `pownode` seems to be where the problem is located, because the thick-client interface can access any of the other expressions in the original compound signal. My guess is that `NB_POWERFAC` is some kind of function defined on the server-side, but I don't know much about how the NSTX-U tree is set up.

**Comment by joshStillerman** [comment]
In order to use the value of this node on your computer in thick client 
mode you would need to be able to evaluate the NB_POWERFAC function.  I 
do not know what is in that function - I assume it is nb_powerfac.fun or 
nb_powerfac.py.

1 - do you have that on your computer  ?
2 - is it in you MDS_PATH ?
3 - if 1 and 2, does it do a call external (use an image->routine()) in 
its contents ?
4 - if 3 - do you have the image on your computer ?

Thick client means that the server just does the IO for you.  You have 
to evaluate the expressions on your computer.
-Josh

**Comment by lamorton** [comment]
Josh,
Thanks, I understand the problem now. For my purposes, the solution is just to use the thin-client interface. 
Lucas
