### ISSUE TITLE
Patches for building with conda

### ISSUE THREAD

**Issue by smithsp** [MDSplus/mdsplus#1201]
I have built a conda package for MDS+.  Along the way, I had to make some patches to the MDS+ build system.  The conda-forge maintainers asked that I make you aware of them.  See the files at https://github.com/conda-forge/staged-recipes/pull/4560/files
with `patch` in the name.  If you would prefer to see the changes as pull requests in this repo, let me know and I can open a separate request for each one.

**Comment by kgerickson** [comment]
Please submit this as a pull request, and explain the justification for the changes so we can evaluate how to best incorporate them with our overall requirements.

**Comment by joshStillerman** [comment]
Building the MDSplus shared executable code is complex, and the build system is accordingly also complex.  We have removed the MDSplus package form pypi for this reason.  If you want to use the native mdsplus libraries, please use the MDSplus installation.  If you only need a python client for mdsplus, consider mdsConnector which provides remote MDSplus python objects.  It is available from PyPi
