### ISSUE TITLE
Get last shot number in LabVIEW

### ISSUE THREAD

**Issue by tyyao** [MDSplus/mdsplus#1205]
Hello all,

Is there a way in LabVIEW to obtain the last shot number saved to a tree? When I run my VI, I want to be able to know what the previous shot number was to continue counting consecutively in creating the next shot.

Many thanks,
Tiffany

**Comment by tfredian** [comment]
I assumed you discovered how to do this and then closed the issue. In case you still need this you could try evaluating the expression 'current_shot("tree-name")'

**Comment by tyyao** [comment]
Yes, that is correct. Thank you for the help!
