### ISSUE TITLE
Using Visual Studio to build Windows applications using MDSplus

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1213]
The MDSplus Windows installer include special DLL's for use with VS projects because of slight differences in the exception handling done my MinGW64 and VS. Recent updates to the MinGW64 compiler removes these differences for 64-bit applications so it should be possible to remove the special MDSplus Visual Studio built 64-bit c++ MDSplus DLL from the distributions. This would greatly simplify the process for generating Windows installers for MDSplus. There may also be some workarounds for 32-bit applications for dealing with these exception handling differences.

Before the special 64-bit DLL is removed from the MDSplus installers it will be necessary to test an VS application using the MingW64 built DLL to ensure that it is indeed compatible with VS applications. It might also be a good idea to put together a simple VS c++ tutorial project (possibly a separate github repository) which demonstrates how to access MDSplus from a Visual Studio application.

**Comment by tfredian** [comment]
The plot thickens on this issue. Over a year ago the build scripts were altered and the building and including of the special VS built dll's was omitted! So as it stands now users can't use the special  MdsObjectsCppShr-VS.dll's anyway. The downside of this is that the current header files do not compile with Visual Studio so currently you couldn't even build an application with Visual Studio to access MDSplus.  So this issue should include the fixing of the header files to make them compatible with VS and then try to make the MdsObjectsCppShr.dll compatible with applications built with VS.

**Comment by kgerickson** [comment]
Or we could drop support of VS :)

**Comment by tfredian** [comment]
We decided to drop the provision of a Visual Studio MdsObjectsCppShr-VS.dll for windows. The C++ code has evolved in MDSplus and no longer appears to be compatible with most versions of Visual Studio. The distribution of MdsObjectsCppShr-VS.dll unintentionally stopped about a year ago and there were no complaints so it is very likely that no users were writing C++ applications with Visual Studio to access MDSplus anyway. If this is incorrect and there is a pressing need to have this then we can revisit this issue. Access to MDSplus via Visual Studio applications using the C interfaces is still supported and the library dll's and the .lib files provided in the devtools\mingw directory remain compatible with Visual Studio.

**Comment by HerveAncher** [comment]
Hello all,
I currently begin the integration of the MDSplus library in IMAS platform for ITER under Windows.
I try to link my C++ low level API with the precompiled binaries of MDSplus, but unfortunately, it failed to find some symbols:

"void __cdecl MDSplus::deleteData(class MDSplus::Data *)"

So I try to recompile MDSplus under VS2017, and I need a VS solution, or a Msbuild script.
I also try to recompile by myself, but the "config.h" for Windows was missing, and I don't find any information to generate it correctly.

Please continue to maintain the Visual Studio solution, the VS2017 version supports C++11, C++14 and most of C++17 pretty well.

Regards.

**Comment by tfredian** [comment]
We are looking into using VS2017 to build the MdsObjectsCppShr-VS.dll and hopefully include it future installers.

**Comment by HerveAncher** [comment]
Thanks a lot, i will do my best to adjust the current VS solution to fit our requirements.

**Comment by tfredian** [comment]
Both alpha and stable releases should provide dll's and lib's compatible with VS2017.
