### ISSUE TITLE
LabVIEW MDSplus Connection VIs

### ISSUE THREAD

**Issue by tyyao** [MDSplus/mdsplus#1220]
Hello all,

I wish to stream data from my computer to a tree stored on a server using an IP connection. However, I am limited to using the VIs within the MDSplus Connection Library (please see picture below).
![connectionmdsplusvis](https://user-images.githubusercontent.com/33073657/35464415-615129d6-02bb-11e8-84d8-ce85f68b5751.png)
Is there any place I can go to obtain additional VIs that can take Connection DVR inputs and outputs? Or is there a way I can write my own VIs to convert the rest of the VIs in the MDSplus library into VIs that can connect to Connection DVRs?

For example, there is a Connection Put Data VI and a Tree Node Put Data VI. However, I need a Connection Put Row VI and I only have a Tree Node Put Row VI (see image below).
![mdspluslibrary](https://user-images.githubusercontent.com/33073657/35464380-35f36e70-02bb-11e8-83fa-997a6b02579e.png)

Many many thanks,
Tiffany

**Comment by GabrieleManduchi** [comment]
You need to install the most recent MDSplus version. The Connection VI has a method getNode that returns a TeeNode VI. You then use that VI as any other TreeNode VI obtained bu a Tree VI, with the difference that tree operations are performed over thin client mdsip. Be aware that not all the TreeNode methods are available with this kind of TreeNode, but the most common ones, including putRow, are included.  In LV2015 directory there is an example showing how using TreeNodes over thin client mdsip (MakeSegmentThinClientExample.vi)

**Comment by tyyao** [comment]
This is the workaround I have been using so far to open a tree on another server and stream the data:
![ip_connect](https://user-images.githubusercontent.com/33073657/35524252-a7b8be5c-04e6-11e8-872e-48157351df1e.png)

I will follow your advice to make sure that I have the most recent MDSplus version, and I will implement the method you explained. Thanks again!

**Comment by tyyao** [comment]
My team and I decided to go with the Distributed Client Mode, and therefore, I have been able to stream data from one of the clients to the server without the need to use any of the Connection VIs. I would still like to learn how to use the Thin Client Mode in case we use it for future applications. I have installed the latest available MDSplus 7.7-12. However, I was not able to find method getNode or the MakeSegmentThinClientExample.vi. How do I get to the two items above?

**Comment by alkhwarizmi** [comment]
Hi all,

sorry for the very late reply. I noticed that the new directory LV2015 is in the alpha branch but not in the last stable (7.7.12).

This is confirmed from my site. I had to pass my original LV2015 directory to them.

Sincerely,

**Comment by joshStillerman** [comment]
Tom is very close to releasing a new stable based on the current alpha.  
This will probably happen around May 1, 2018.  At that point it should 
include everything.

-Josh
