### ISSUE TITLE
Wrong behavior of TreeGetXNci / TreSetXNci in given sequences

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1267]
When adding the mdsobject support to extended attributes I observed a strange behavior. If things occur in the following sequence:

SetXNci  on node 1

SetXNci on node 2

then GetXNci on node 1 fails while GetXNci on node 2 succeeds

HOWEVER if I repeat the sequence, both GetXNci work.

In summary it appears that something wrong occurs in the sequence of two XSetNci for nodes without that attribute already set.

**Comment by tfredian** [comment]
I will look into this. It appears that extended attributes are now completely broken. I suspect the location of the extended attribute info written to the tree is not being calculated properly and all nodes are using the same location:

[twf@fc27 ~]$ mdstcl
TCL> edit/new twf
TCL> add node one
TCL> add node two
TCL> set attribute one/name=attr 42
TCL> show attribute one/name=attr
42 <<< correct
TCL> show attribute two/name=attr
Error: Unable to get attributes for node 'two'
Error message was: %TREE-E-FAILURE, Operation NOT successful
mdsdcl: --> failed on line 'show attribute two/name=attr'  <<< correct
TCL> set attribute two/name=attr 100
TCL> show attribute two/name=attr
100 <<< correct
TCL> show attribute one/name=attr
100 <<< wrong!

**Comment by tfredian** [comment]
I'll add some extended attribute tests to tditest too if I figure out a solution.
