### ISSUE TITLE
FindNodeWild does not traverse all the nodes 

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1285]
Hi Josh,
    there are some problems in the latest alpha with the new findNodeWild version. You can reproduce the issue using the simple pulse file (attached) shown below

![4tnatgwz](https://user-images.githubusercontent.com/8696392/38491849-6571e544-3bed-11e8-82a6-f0e6bde1d6c2.gif)

[testfind.zip](https://github.com/MDSplus/mdsplus/files/1889397/testfind.zip)

The attached python program does not explore all the nodes as it should do:

[mdsplus@rat3]$ ls
testfind_model.characteristics  testfind_model.datafile  testfind_model.tree  testfind.py
[mdsplus@rat3]$ export testfind_path=`pwd`
[mdsplus@rat3]$ python
Python 2.7.5 (default, Aug  2 2016, 04:20:16)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import testfind as tf
>>> tf.test('testfind','***','numeric')
==== All nodes ====
\TESTFIND::TOP.CHILD1
\TESTFIND::TOP.CHILD2
\TESTFIND::TOP.CHILD1:CHILD12
\TESTFIND::TOP.CHILD2:CHILD21
\TESTFIND::TOP.CHILD2:CHILD22
\TESTFIND::TOP.CHILD1:CHILD12:CLD12_NODE1
\TESTFIND::TOP.CHILD1:CHILD12:CLD12_NODE2
\TESTFIND::TOP.CHILD2:CHILD21:CLD21_NODE1
\TESTFIND::TOP.CHILD2:CHILD21:CLD21_NODE2
\TESTFIND::TOP.CHILD2:CHILD22:CLD22_NODE1
\TESTFIND::TOP.CHILD2:CHILD22:CLD22_NODE2
===================
===== Node Usage numeric======
\TESTFIND::TOP.CHILD1:CHILD12:CLD12_NODE1
\TESTFIND::TOP.CHILD1:CHILD12:CLD12_NODE2
\TESTFIND::TOP.CHILD2:CHILD21:CLD21_NODE1
\TESTFIND::TOP.CHILD2:CHILD21:CLD21_NODE2
\TESTFIND::TOP.CHILD2:CHILD22:CLD22_NODE1
\TESTFIND::TOP.CHILD2:CHILD22:CLD22_NODE2
==================================
>>>

The sons of  CHILD1:CHILD11 appear not to be traversed!!

**Comment by joshStillerman** [comment]
Gabriele  -

   I have 'fixed' this.  The problem was the assumptions I made about 
usage: Namely that all nodes of usage structure are children.  Most of 
our tools force this behavior, but it is possible to create your tree 
(no surprise since you made it) where there is a member of usage 
structure.  I did not add a test case for this because it is difficult 
to make such a tree in python or TCL.

-Josh
