### ISSUE TITLE
Missing Tree.close() python method in Windows + different MDSplus array index behavior

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1290]
Using the latest alpha Windows distribution I observed the following two things when using python 2.7 under windows:

1) method Tree.close()   is missing

2) the  use of index -1 in MDSplus arrays does not work (it works under Linux).  E.g.

>>>timeBase = np.zeros(1000)
>>> t0 = 9
>>> timeBaseJava = Int64Array(timeBase*1e3) + Int64(t0)*1000
>>> timebaseJava[0]
>>> timeBaseJava[0]
9000Q
>>> timeBaseJava[-1]
9000Q under Linux,  index exception under Windows

**Comment by zack-vii** [comment]
hmm, are you sure you are using the right python files..
if i run 
```python
from MDSplus import Int64Array,Int64,Tree
import numpy as np
timeBase = np.zeros(1000)
t0 = 9
timeBaseJava = Int64Array(timeBase*1e3) + Int64(t0)*1000
print(timeBaseJava[0])
print(timeBaseJava[-1])
print(Tree.close)
```
i get the output
9000Q
9000Q
<function Tree.close at 0x000001B97F52F598>

also why should there be a close method under linux but not under windows when they are using the same python files.

Can anyone confirm this issue.

**Comment by tfredian** [comment]
This was caused by not having the alpha 7.40.0 version of the python module installed.
