### ISSUE TITLE
Problems with MdsDataProvider (jScope) with alpha 7.40.0

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#1295]
Dear all,

I noticed that a number of scopes of mine which were previously (7.7.12) working are not working anymore after my recent upgrade to the latest alpha (7.40.0).

Local access is working but I have a problem which could be related in the way the MdsPlusData provider handles the names of "relative" signals, that is signals that do not start with "\\\<experiment name\>::TOP.".

In fact this jScope configuration:

![image](https://user-images.githubusercontent.com/5898559/39293564-79cc1060-4939-11e8-845b-faf5ff3dd47f.png)
prodces this:
![image](https://user-images.githubusercontent.com/5898559/39293943-9f780458-493a-11e8-8246-f7b3ba5964d3.png)

while fully qualifying the signals allows to show both of them!

![image](https://user-images.githubusercontent.com/5898559/39294124-2dc6e044-493b-11e8-90f3-dd3c650c8c63.png)
![image](https://user-images.githubusercontent.com/5898559/39294343-cceee4b4-493b-11e8-9ad0-769432fc66f5.png)

It is possible that this was intended fix other misbehaviours. It seems a bit strange (what would be the purpose of specifying the experiment name globally then?) but I don't know.

I liked the idea of "relative" signals because I could test different trees (in fact two equal tree on different machines) just by letting the jScope point to the other experiment.

Let me know if I have to change my scopes or you think it is a regression to be fixed.

Sincerely,

P.S. Attached the source code of a scope reproducing the problem

[MdsDataProviderProblem.txt](https://github.com/MDSplus/mdsplus/files/1950348/MdsDataProviderProblem.txt)

**Comment by GabrieleManduchi** [comment]
I cannot reproduce the issue, that may depend on the current default position on tour tree.

 In any case it is necessary to specify the complete  pathname (or tag)  in jScope dialog. Relative path names required the definition of the default node field.

**Comment by alkhwarizmi** [comment]
Thank you Gabriele!

I'm trying to set the default node like shown below but nothing changes. 

![image](https://user-images.githubusercontent.com/5898559/39537523-2dd1acaa-4e3a-11e8-86b2-15c7280a0184.png)
