### ISSUE TITLE
Failure creating new tree on Ubuntu server

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#1322]
Dear all,

trying to create a new tree on a remote linux-based MDSplus server from my PC i get a %TREE-E-MOVEERROR error when I give the tree.write() command (see below).

I have noticed that I am left with an extra file `inspire2_model.tree#` and a `inspire2_model.tree` file of zero size after the operation. If I delete manually all the files and start from scratch, nothing changes. The access rights seems a bit different from the past (now the group, `"domain users"`, is write enabled).

When I am logged on the server, the python commands works perfectly.

Below you can find some info about the PC and server system I am running.

Tried to solve this myself for quite a long time now without success. Although it sound a trivial problem maybe it is not.

Sincerely,

 
```
from MDSplus import  *
tree = Tree("inspire2", -1, "NEW")
tree.write()

Traceback (most recent call last):

  File "<ipython-input-22-2136e2d4de42>", line 1, in <module>
    tree.write()

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.40.0-py3.6.egg\MDSplus\tree.py", line 1036, in write
    _C.c_int32(int(self.shot))))

  File "C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.40.0-py3.6.egg\MDSplus\mdsExceptions.py", line 87, in checkStatus
    raise MDSplusException(status)

TreeMOVEERROR: %TREE-E-MOVEERROR, Error replacing original treefile with new one.
```

PC config

```
Machine and OS information

Machine: AMD64
Processor: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
System: Windows
Release: 10
Version: 10.0.17134
Distribution: ('10', '10.0.17134', 'SP0', 'Multiprocessor Free')


Python information

Python: 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


MDSplus information

Version: 7.40.0
Python module: C:\Anaconda3\lib\site-packages\mdsplus_alpha-7.40.0-py3.6.egg\MDSplus\__init__.py
```

Server config
```
Machine and OS information

Machine: x86_64
Processor: x86_64
Operative system: Linux
Release: 4.13.0-43-generic
Version: #48-Ubuntu SMP Wed May 16 12:18:48 UTC 2018
Distribution: ('Ubuntu', '17.10', 'artful')


Python information

Python: 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]


MDSplus information

Version: 7.7.13
Python module: /usr/local/lib/python3.6/dist-packages/mdsplus-7.7.13-py3.6.egg/MDSplus/__init__.py
```

**Comment by tfredian** [comment]
Is your connection from the windows system being mapped to your account on the ubuntu server? For a windows client you probably need an explicit mapping in /etc/mdsip.hosts for your windows ip address mapped to your linux username in /etc/mdsip.hosts such as:

`<windows-ip-address> | <username>`

You might also check the permissions on the directory on the server as well as the permission and owner of the files being created. It is also possible that the problem is related to default umask settings on the server. You might need to add a umask option to the /etc/xinetd.d/mdsip configuration to change the default protection masks on files created by the mdsip service.

Cheers,
Tom

**Comment by tfredian** [comment]
Sorry the markup messed up my ip adress to username mapping example:

`<windows-ip-address> | <username>`

**Comment by alkhwarizmi** [comment]
Hallo Tom,

quite strange: I didn't touch the `mdsip.hosts` file but MDSplus was somehow redirecting to my private user correctly.

I tried to set up a new system user `mdsplus` but things do not change: the command (on the PC)
```
tree = Tree("inspire2", -1, "NEW")
```
creates the following files (on the server)
```
-rw-rw-r-- 1 mdsplus mdsplus  588 May 30 13:53 inspire2_model.characteristics
-rw-rw-r-- 1 mdsplus mdsplus    0 May 30 13:53 inspire2_model.datafile
-rw-rw-r-- 1 mdsplus mdsplus    0 May 30 13:53 inspire2_model.tree
-rw-rw-r-- 1 mdsplus mdsplus 1024 May 30 13:53 inspire2_model.tree#
```
and the command
```
tree.write()
```
gives the same error.

I added a very permissive umask option to the `/etc/xinetd.d/mdsip` file but it doesn't seem to have any effect.

At the moment, the file reads:
```
# default: off
#       standard mdsip.hosts and logs into /var/log/mdsplus.
service mdsip
{
        disable         = no
        socket_type     = stream
        wait            = no
        cps             = 10000 1
        instances       = UNLIMITED
        per_source      = UNLIMITED
        user            = root
        umask           = 000

### NOTE: If you installed MDSplus to a different location than
###       /usr/local/mdsplus make sure you change the following
###       line to use the directory where you installed MDSplus.

        server          = /usr/local/mdsplus/bin/mdsipd
        server_args     = mdsip /var/log/mdsplus/mdsipd
        log_on_failure  += HOST
        log_on_success  += HOST
        flags           = KEEPALIVE NODELAY NOLIBWRAP
}
```

I tried to see what happens changing user from `root` to `mdsplus` but in this case even the Tree constructor stops working.

Sincerely,

**Comment by tfredian** [comment]
The mdsip.hosts file is used on the server side of the connection and the default mdsip.hosts file contains:

```
* | MAP_TO_LOCAL
* | nobody 
```
so if the username of the client exists on the server it will map to that account. You should not change the user in the /etc/xinetd.d/mdsip file because the mdsip service process reads in /etc/mdsip.hosts and attempts to switch to the user account based on the rules in that file which requires root privileges.

I'm still perplexed about the error though. The next test I would recommend is to try using mdstcl to edit the tree to see if it is a python problem. 


```
TCL> edit/new inspire2
TCL> add node mynode
TCL> write
```
and see if that works. Also, can you determine if the same problem occurs when using a different client platform? To me it seems most likely that this is a problem on the server side.

-tom

**Comment by alkhwarizmi** [comment]
Halo Tom,

locally it seems to be working both with TCL and Python.

Remotely, it does not work from my PC and from another machine running Windows Server. No way to test from another linux machine.

I noticed that the constructor commands, when run locally do not create the file `inspire2_model.tree#` while the remote commands do so.

I agree with you that it seems a problem of the server, though. I don't know exactly when you create that file and what it is. If it is a lock file, could it be that somehow a second process is starte conflicting with the first one?

In this case maybe the configuration of xinetd would have some problems.

Sincerely,
  Anton

**Comment by tfredian** [comment]
ok, one more question. What is the inspire2_path environment variable set to? Is it

`inspire2_path=hostname::`

or:

`inspire2_path=hostname::/dir-spec`

**Comment by alkhwarizmi** [comment]
On the client it is something like
```
inspire2_path=<hostname>:8000::\data\MDSplusTrees\inspire2
```
note the Windows like directory separators.

Sincerely,

**Comment by tfredian** [comment]
Sorry for all the questions.... I was finally able to reproduce this problem here and will try to fix it. It actually appears to be a problem on the client side and seems to be a Windows only problem. Locally I have the latest alpha release installed on my windows system and on the server system and the problem occurs here. It does not occur when editing a tree with a linux client running the latest alpha release.

**Comment by alkhwarizmi** [comment]
!! how unexpected !!

Don't worry Tom, and thank you for your patience.

Sometimes I ask myself if I have been genetically modified to be a "problem finder"... :)

I will look forward for the patch.

Sincerely,

**Comment by tfredian** [comment]
Ok, I think I found the problem. For some reason we are handling the windows directory specifiers for opening trees on linux but are not doing so with tree editing. In general I would not recommend using backslashes in the directory spec at all. I think if you change your path to be:

inspire2_path=<hostname>:8000::/data/MDSplusTrees/inspire2

it will probably work. Let me know if it does.

I have mixed emotions about us supporting the backslash delimited directory specifiers at all when accessing a non windows server but it would probably be a good idea to be consistent for all operations.

**Comment by alkhwarizmi** [comment]
Hallo Tom,

yes, using the linux style for directory separation solves the problem. When I set up the linux machine I have copy-pasted the environment variable without paying to much attention on that because in the past I partecipated to a discussion where I got the idea that MDSplus supported or was about to support both styles.

In my opinion, that would simplify management and diffusion of the program, but I don't know if you can rely on external portable libraries to implement that or you have to implement everything from scratch. Inpython and LabView there are "Path" objects that take care of this sort of problems.

Certainly, it is not good that some parts of MDSplus support the feature and others don't. In this case I would have expected an error message like "Impossible to open tree file xxxx" already from the constructor if the tree name is not parsed correctly.

Thank you very much for the debugging.

Sincerely,

**Comment by alkhwarizmi** [comment]
Hallo Tom,

it seems that I was too precipitous in writing my last comment. Just changing the backslash to slash has a strange side effect:

If the environment variable is defined as:
```
inspire2_path=<hostname>:8000::/data/MDSplusTrees/inspire2
```
with no trailing slash, the the tree files are created like:
```
/data/MDSplusTrees/inspire2\inspire2_model.<mdsplus ext>
```
that is in the directory one level above than expected with the file names being`inspire2\inspire2_model.<mdsplus ext>`

If the environment variable is defined as:
```
inspire2_path=<hostname>:8000::/data/MDSplusTrees/inspire2/
```
with trailing slash, the the tree files are created like:
```
/data/MDSplusTrees/inspire2/\inspire2_model.<mdsplus ext>
```
that is in the expected directory but still with wrong file names, being them `\inspire2_model.<mdsplus ext>` (note the leading backslash)

Creating a variable like
```
inspire2_path=<hostname>:8000::/data/MDSplusTrees/inspire2\
```
with a final backslash, has the same behaviour as withot any trailing character.

Sincerely,
