### ISSUE TITLE
Documentation: TreeCreatePulseFile.fun

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#1326]
Hello all,

trying to create a pulse file remotely via the thin client mechanism (as a workaround to #1322) I found some difficulties calling to `TreeCreatePulseFile.fun`.

The Python user expects to call that function with one parameter only, the new shot number, because so he/she does in the documented mdsobjects API.

The fun instead has three parameters and their function is not documented. One seems to be a node ID but it is not clear to me what it is used for. The third parameter is totally obscure.

I had to look at the Python source code to understand that it is safe to call it with the last two parameters set to 0.

Sincerely,

**Comment by tfredian** [comment]
The TreeCreatePulseFile.fun was implemented for internal use (mdsip thin client). It should have included documentation in the fun to indicate that intention. The additional arguments provide the added capability of the TCL> CREATE PULSE command which enables you to only include specific subtrees or exclude specific subtrees. With the trailing to arguments set to 0 it behaves like CREATE PULSE without those qualifiers. I suspect a more traditional way to accomplish what you were trying to do would be to use the tcl() function. I will look into adding "internal use only" comments to these treeshr fun's. When thinking about using the tcl() function for creating pulses I thought perhaps the tcl() fun could be enhanced to support arrays of strings for the commands: tcl(['set tree mytree','create pulse 1']) which might be useful for some applications. This feature might be useful for other languages such as python too.
