### ISSUE TITLE
MATLAB javaapi does not support Q or QU

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1335]
If you e.g. do
```matlab
mdsconnect('mds-server');
mdsvalue('1000000000000')
ans =
            -727379968
```
which is only to lower 4 bytes.

0xE8D4A51000 -> 0xD4A51000

**Comment by tfredian** [comment]
I'm not sure this is a javaapi problem or a problem at all:

>> mdsconnect('alcdaq6')      

ans =

     1

>> mdsvalue('1000000000000QU')

ans =

        1000000000000

>> mdsvalue('1000000000000Q') 

ans =

        1000000000000

>> mdsvalue('1000000000000') 

ans =

Java exception occurred: 
MDSplus.MdsException: %TDI-E-TOO_BIG, Conversion of number lost significant digits
        at MDSplus.Connection.get(Native Method)
        at MDSplus.Connection.get(Connection.java:90)
        at MDSplus.Connection.get(Connection.java:95)

or it was fixed since this issue was submitted.
