### ISSUE TITLE
Reply port selector 8800+

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1379]
Is there any particular reason why the reply port for an mdsip session is selected manually in the range of 8800 - 9055 and not chosen by the os using port 0.

servershr/ServerSendMessage.c CreatePort

**Comment by zack-vii** [comment]
One has to open that range in the iptables because it is opening a new listener port. instead one could eventually reuse the established connection.
PR #1377 was meant to fix some actmon issues but add a feature that allows to set the range via an env var which defaults to:
MDSIP_PORT_RANGE=8800-9055

**Comment by joshStillerman** [comment]
Should this now be closed then ?

**Comment by zack-vii** [comment]
i will open an new issue with my vision of where this is going ;)
