### ISSUE TITLE
MDSconnector python 3

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1385]
MDSconnector does not work with with python3  - especially if the python versions / server / client are not the same.

**Comment by joshStillerman** [comment]
Tom says - try to default the python in .bashrc
Does Zerodeploy allow you to specify the python to use ?

**Comment by tfredian** [comment]
fixed. Future mdsConnector issues should be posted to the MDSplus/mdsconnector repository not this one.
