### ISSUE TITLE
d-taq ACQ2106_xxxx support

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1391]
Support for the new d-tacq chassis and cards is not available in the distro.  It seems like the W7x ACQxxxx devices should be in W7xDevices.

Existing device support in that kit that are obsolete should be removed and the new code should be put in W7x Devices.

This device support is pretty complicated so a description of how to add, configure and use them should be included.

Does the new code support streaming ?

We just received a acq2106 with 4 acq423 modules in it.  Presumably the acq423 should be a small perturbation on the existing cards.

**Comment by zack-vii** [comment]
#1629
