### ISSUE TITLE
Unable to push under stable or creating a new branch

### ISSUE THREAD

**Issue by HerveAncher** [MDSplus/mdsplus#1394]
Hello,

I have pulled the stable branch on my computer under Windows and I have made some adjustment to compiling correctly with MinGW-w64.

Now I try to push on stable, which is  - I think - not permitted, or creating a new branch like 'windows-mingw' to after create a pull request based on this new branch.

How I have to proceed to push my modification?

Thank, Hervé.

**Comment by joshStillerman** [comment]
Hi -

   Who are you and where do you work ?  You are welcome to join in 
MDSplus development.  THANKS!  We work with pull requests not pushes.

you should:

1 - fork the repo

2 - with your repo:

3 - make a branch for your changes

4 - push the branch to github

5 - make a pull request against MDSplus for it.

-josh

**Comment by HerveAncher** [comment]
Sorry, I work at the CEA, in south of France, we develop the IMAS Data Access Layer to manage and store data from our Tokamak WEST.

We used MDSplus as backend inside our Access Layer, and I work on porting the current Linux code under Windows.

I will follow your explanation and post a result alter, Thanks.

**Comment by HerveAncher** [comment]
I have created a new local branch named "windows-mingw":

```
$ git log
commit 7fd65d520113f7e6bc50d1ec4243c98df051cbcc (HEAD -> windows-mingw, stable)
Author: Hervé Ancher <herve.ancher@cea.fr>
Date:   Thu Sep 20 11:41:44 2018 +0200

    Adjustment for Windows MinGW-w64
```

Now I want to push this new branch on this git, but I get error:

```
$ git push
fatal: La branche courante windows-mingw n'a pas de branche amont.
Pour pousser la branche courante et définir la distante comme amont, utilisez

    git push --set-upstream origin windows-mingw
```

I try to used the preconized command:

```
remote: Permission to MDSplus/mdsplus.git denied to HerveAncher.
fatal: unable to access 'https://github.com/MDSplus/mdsplus.git/': The requested URL returned error: 403
```

What is going on?

**Comment by tfredian** [comment]
You cannot push branches to the official MDSplus repositories.
As Josh mentioned you have to fork the repository into your own account first. Go to https://github.com/MDSplus/mdsplus and click on the Fork button on the top left. This will create an mdsplus repository in your own account. After you have a fork of the repository in your account you can try the following commands locally in your mdsplus clone directory. You may want to make a copy of the files you have modified in case you run into problems doing these commands to ensure that your changes don't get lost. If there are problems you could just clone your forked repository in another directory, copy the modified files into the new clone, create a new branch, merge and push to your forked repository. The following commands should work and be an easier method though:

```
$ git checkout alpha # switch back to the alpha branch
$ git pull    # to update your copy to the latest commits
$ git checkout windows-mingw # to get back to your branch
$ git rebase alpha # to move your commits to the head of the alpha branch
$ git remote add HerveAncher https://github.com/HerveAncher/mdsplus.git # to add your fork to your clone
$ git push --set-upstream HerveAncher windows-mingw # to push your branch to your forked repo
```
After doing the above commands then go to https://github.com/HerveAncher/mdsplus in your browser and you should be able to perform a pull request with your windows-mingw branch. This will add a pull request to the official mdsplus repository and we will be able to review and test your changes and hopefully merge them into the official alpha release.

**Comment by HerveAncher** [comment]
OK, I haven't understand that I need to fork in MY account.
A new pull request is opened.

Thanks.

**Comment by tfredian** [comment]
Ok I see the PR but have some comments and questions.

1) You need to change configure.ac and run autoconf to generate the configure file and not modify configure directly. Include changes to configure.ac in the pr.

2) Can you explain what exactly these changes are supposed to fix? We having been building mdsplus distributions nightly using the mdsplus/docker:windows image which uses MinGW-w64 and are unaware of any problems with the windows distributions. If you have docker installed and running on your system I think you can also build unsigned mdsplus kits for windows using the commands:

```
$ mkdir ~/mdsbuild
$ cd ~/mdsbuild
$ ~/mdsplus/deploy/build.sh --os=windows --release=n.n.n --branch=branchname
```
This is basically how the MDSplus build system builds all of it's linux and windows distributions and as I said have not had any reports of problems with the windows distributions.

**Comment by HerveAncher** [comment]
Well, I don't use the Docker image, I use MinGW-w64 installed by MSYS2 tool.
When I try to directly compile MDSplus by launching `../configure` inside a subdirectory `build` followed by a `make`, some makefile failed, like `mdsdcl` or `mdsshr` mostly about the libxml2 path.

I think that the Docker image for MinGW doesn't defined the same path than mine.

The adaptation a have made in the `configure` file can be reported inside the `configure.ac` but actually I haven't launch `autoconf` before configure, my mistake.

I think I will push a new commit for `configure.ac`
