### ISSUE TITLE
Python Tree.getNode() crashes when empty string is passed as argument

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1408]
Very easy to replicate

>>>from MDSplus import *
>>> t = Tree('rfx',35100)
>>> n=t.getNode('')
Segmentation fault (core dumped)

**Comment by tfredian** [comment]
This is a problem with the refactor of TreeFindNode in treeshr. Even TCL> DIR "" will segfault. Josh will be looking into this.
