### ISSUE TITLE
Move device specific tdi functions used only during data access to kernel package

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1426]
Some device specific tdi functions were created to help in accessing data stored by devices. Perhaps these functions should be moved to the kernel package enabling data access without the need to install the device support packages which possibly can require other packages not available on some platforms.

This will require going through the functions in tdi/*devices/ and moving them to perhaps a subdirectory of  tdi/dev_support (i.e. tdi/dev_support/mit) so they will be included in the kernel package instead of the xxxdevices package and correcting the expected package contents.

**Comment by zack-vii** [comment]
or we export them together with all device drivers to a device repository where everyone can share and version there own contributions. i.e. dont ship them via the install packages but allow users do download their personal choice. Most drivers wont be updated otherwise because they cannot be tested and one fears incompatibility with old code. We could add a new git repo under the mdsplus group calles MdsDevices. which holds all device related stuff well sorted by vendor/series/model/version.

**Comment by tfredian** [comment]
This issue is different than possible changes to device support packaging.  Was it is referring to is that some devices (perhaps just older device but not sure) store signals containing references to tdi functions. We should probably refrain from doing this in the future but for those tdi functions referenced by the stored data they should be move out of the device packaging entirely to enable clients to access the stored signals without needing the data acquisition modules installed on their system. I think the number of these functions are hopefully quite small. We should definitely come up with a workaround for new device support to separate what is needed to acquire data vs look at stored data.

**Comment by zack-vii** [comment]
I got that, my idea would be keep those routines with the driver and let the admins of sites using those devices manage the distribution of those function. You only seem to need them when accessing data of those specific devices. you done need to compile and install the entire driver you would simply download the tditools  to that specific device and add it to your MDS_PATH.
The core system should not bother with device specific - i would want to call them - plugins.

**Comment by zack-vii** [comment]
On that matter, we should eventually add a node type that can be used to define functions.
eventually like EXT_FUNCTION(NODE:PATH:TO:FUNCTION,NODE:TO:ARG1,NODE:TO:ARG2,...)

**Comment by tfredian** [comment]
Actually, storing and referencing tdi funcs can be easily done now. Perhaps we need a similar trick for python funs. I just tried the following.
```
[twf@fc28 mdsplus-alpha]$ python
Python 2.7.15 (default, Oct 15 2018, 15:24:06) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from MDSplus import *
>>> t=Tree('twf',-1)
>>> t.TEST.record
FUNS, myfun(1 : 100 : *)
>>> t.FUNS.record
Fun PUBLIC myfun (IN _val) {
        Return (2 * _val);
}
*, 1;
>>> t.TEST.record.data()
array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200], dtype=int32)
>>> t.FUNS.record.data()
1
```
So the device support could store the required data access funcs in a node in the device and then stored data could reference that node to load the tdi functions from the tree.
It is true that collaborators needing to access data from an experiment remotely generally use thin client to access the data and therefore would reference the special functions on the remote server but it would be nice to avoid the need to have those fun's installed manually anywhere. btw, I just used Numeric usage types for the FUNS and TEST nodes above. Perhaps there is a way (or one could be developed) to enable python fun's to be loaded similarly. We do have the py() tdi function to execute python commands but that might be a tedious mechanism for doing this.

**Comment by tfredian** [comment]
This may provide some ideas for adding py funs defined in tree nodes or strings: https://stackoverflow.com/questions/5362771/how-to-load-a-module-from-code-in-a-string

This may be worth adding another "feature" issue. It would be great if py fun's were cached once loaded similar to tdi fun's and also provide a mechanism for loading py fun's using a string array or possibly also a DTYPE_T with proper line feed chars in the string.

**Comment by zack-vii** [comment]
addfun can be used now to define python code as tdi function, on the fly.
```tdi
addfun("myfun","def myfun(a):\n return a*2")
"MYFUN"
myfun(1:10)
[2,4,6,8,10,12,14,16,18,20]
```
