### ISSUE TITLE
Segfaults occuring in threadsUnitTest.py in alpha build

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1427]
For some reason we are now getting segfaults during the alpha release builds.

runTest (python.tests.threadsUnitTest.Tests) ... Error: Command failed - 'type test'
Error message was: %SERVER-E-PATH_DOWN, Path to server lost
Error: Command failed - 'type test'
Error message was: %SERVER-E-PATH_DOWN, Path to server lost
Error: Command failed - 'type test'
Error message was: %SERVER-E-PATH_DOWN, Path to server lost
ASAN:DEADLYSIGNAL
=================================================================
==8357==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7f52766f7ba0 sp 0x7f52766f63d8 T47)
==8357==Hint: pc points to the zero page.
==8357==The signal is caused by a READ memory access.
==8357==Hint: address points to the zero page.

**Comment by zack-vii** [comment]
happened under windows randomly
```url
windows/1633/artifact/tests/64/mdsobjects/python/tests/threadsUnitTest.log
```
```Traceback 
Traceback (most recent call last):
  File "Z:\mdsplus-docker\jenkins2\workspace\windows\src\mdsobjects\python\tests\treeUnitTest.py", line 338, in nciInfo
    test()
  File "Z:\mdsplus-docker\jenkins2\workspace\windows\src\mdsobjects\python\tests\treeUnitTest.py", line 326, in test
    self.assertEqual(part.original_part_name,':COMMENT')
  File "Z:\mdsplus-docker\jenkins2\workspace\windows\src\testing\MDSplus\tree.py", line 1356, in getter
    return self._getNci(name,False)
  File "Z:\mdsplus-docker\jenkins2\workspace\windows\src\testing\MDSplus\tree.py", line 1305, in _getNci
    _C.byref(itmlst)))
WindowsError: exception: access violation writing 0x0000000000000000
```

**Comment by zack-vii** [comment]
I finallly got it to fail in a gdb:
```gdb
#0  0x0000000000000000 in ?? ()
#1  0x00007fffec020bda in LibCallg (arglist=0x7fffd3783540, routine=0x0) at /git/mdsplus/mdsshr/librtl.c:152
#2  0x00007fffeb3c5d5f in TreeDoFun (funname=0x7fffd3784080, nargs=2, args=0x7fffd3784428, out_ptr=0x7fffd3784f10)
    at /git/mdsplus/treeshr/TreeDoMethod.c:114
#3  0x00007fffeb3c830b in _TreeDoMethod (dbid=0x60e000087880, nid_dsc=0x7fffd3784f50, method_ptr=0x7fffd3784f90)
    at /git/mdsplus/treeshr/TreeDoMethod.c:233
#4  0x00007fffeb3d9d02 in _TreeGetNci (dbid=0x60e000087880, nid_in=16777237, nci_itm=0x61a00172c880)
    at /git/mdsplus/treeshr/TreeGetNci.c:356
#5  0x00007fffeb3d5eb6 in TreeGetNci (nid_in=16777237, nci_itm=0x61a00172c880) at /git/mdsplus/treeshr/TreeGetNci.c:74
```
 if I up into TreeDoFun routine would be  TdiEvaluate but TdiEvaluate is not null. This reminds me on issues we had with a too small stacksize. Could that be it?

**Comment by tfredian** [comment]
I believe this was due to a race condition in obtaining the address of the TdiEvaluate function and has been fixed.
