### ISSUE TITLE
MdsConnectionTest not working and not returning failure if test fail

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1438]
The MdsConnectionTest should probably only test local and tcp protocols. It currently is attempting to test ssh but without any credentials for ssh'ing to a server. Both the local and the ssh protocols use the "Tunnel" protocol so testing local should be sufficient. Currently the tests are failing but the final result is success.

**Comment by zack-vii** [comment]
largely improved in possibly even fixed in PR #1440
