### ISSUE TITLE
Add feature to make the mdsip tunnel protocol the default

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1439]
Several mdsip transport protocols use the tunnel protocol. This is currently accomplished by either creating a symlink to the tunnel protocol shared library with the name libMdsIp{PROTOCOL}.so. Since specialized mdsip protocols require shared library implementations, mdsip could default to using tunnel protocols if a library matching the protocol name cannot be found. This would enable implementing tunnel based protocols simpler requiring just shell scripts such as mdsip-client-PROTOCOL and/or mdsip-server-PROTOCOL. This would remove the necessity to make copies or symlinks to the tunnel protocol shared library.

**Comment by zack-vii** [comment]
done in PR #1440
