### ISSUE TITLE
jScope local data provider does not work on mac

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1441]
The  local data provider on macintosh, when invoked by jScope, does not open trees.  It seems to reply with values for expressions that do not involve trees.

All data seems to be returned empty.

When I put $shot in the title it responds 'tree not open'.

However:
  The local data provider does work in tditest.
```
$ tditest
mdsconnect('local')
-1
mdsvalue('getenv("HOME")')
"/Users/jas"
treeOpen('cmod', 1)
265388067
mdsvalue("treeOpen('cmod', 1)")
265388067
mdsvalue('\\ip')
Build_Signal(Build_With_Units(\MAGNETICS::MAG_ROGOWSKI.SIGNALS:ROG_FG + 2100F0 * \MAGNETICS::BTOR, "ampere"), *, DIM_OF(\MAGNETICS::BTOR))
```
Could the problems be

- text fields are not being sent through the data provider ?
- the expression returned is not being evaluated ?

**Comment by GabrieleManduchi** [comment]
Try: 
$ tditest
mdsconnect('local')
-1
mdsvalue('getenv("MDS_PATH")')


As in jScope everything goes through expressions, including opening a tree, inability to activate expressions prevents opening trees, too

**Comment by GabrieleManduchi** [comment]
The funs called by jScope are in mdsplus/tdi/java

**Comment by joshStillerman** [comment]
They are fine as is:

mdsvalue('treeopen("cmod", 1)')
265388067

(I have a local copy of a cmod shot number 1)

**Comment by GabrieleManduchi** [comment]
Does 
jScope -s localhost 
work with a mdsip server running on mac?

**Comment by joshStillerman** [comment]
It just exits after putting up the splash screen, no output

**Comment by GabrieleManduchi** [comment]
...and what if the server is on a Linux machine?

**Comment by GabrieleManduchi** [comment]
Josh,
 I just tried installing the latest alpha on a mac (with macOS 10.13 and  jdk 8.191) and both 
jScope -s localhost   (with a mdsip running locally) and
jScope -l 
work, even displaying tree contents

**Comment by joshStillerman** [comment]
I was just about to write to you.  I did the same on my laptop, and it 
works !  Sorry for the confusion.  I will close the issue.

-Josh
