### ISSUE TITLE
Include device definitions of pydevices within the DEVICE HEAD node

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1446]
Instead of the import statement the head node of python devices could contain the entire device definition. AN exec call in an enclosed environment could handle the code and either reveal the device object via an import command (current behavior) or simply as definition:
```python
import MDSplus
def MyDevice(MDSplus.Device):
    parts = [
        """ node definition """
    ]
    def init():
        """do init stuff"""
    ...
```
one would adapt the python api in such way that it would always grep use the statement in head to get the definition (should be cached) from the head node. 
* The device driver (MyDevice.py) would only be required for adding a device. 
* Users would always end up with the correct version o .py file and tree structure. 
* It is no longer required to distribute the device driver to obtain ORIGINAL_NAME (or HELP).
* The lowercase node access dev.subpath_to_device_node will not get mixed up due to a eventual version clash of MyDevice.py.
* eventual device method that are intended to be used to read or post process data are shipped with the tree.
* a special node expression could make use of device methods and process node data.
* possibly more

**Comment by tfredian** [comment]
This has a lot of good potential but it would make it essential to be very careful about how various classes or methods of the MDSplus module are referenced or used to ensure that enhancements to MDSplus do not break the device code stored in the tree. Currently the py device code tracks the MDSplus release version. This is somewhat similar to the problem of using MDSplus python modules that are not consistent with the MDSplus libraries. Something to consider when implementing this new feature....

It might be useful to implement a small set of pydevice-in-tree devices to gain some experience before converting all pydevices over to this method.

**Comment by zack-vii** [comment]
WE have this feature in alpha since PR #1544
