### ISSUE TITLE
DWSCOPE not updating on events

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1453]
It appears that with 

MDSplus version: 7.54-2

DWSCOPE does not update on events.  I know the system is not blocking event messages, as wfevent and setevent work.

It could be that I am confused (it is getting late) but wanted to write this down before the long weekend

**Comment by tfredian** [comment]
I just tried it on cmodws106 and it worked fine. Don't forget, event updates only happen on panels displaying data from shot 0.

**Comment by joshStillerman** [comment]
I did forget that.  Thanks.JoshOn Nov 10, 2018 8:53 AM, Tom Fredian <notifications@github.com> wrote:I just tried it on cmodws106 and it worked fine. Don't forget, event updates only happen on panels displaying data from shot 0.
