### ISSUE TITLE
[Question] Node specification in TDI functions?

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1458]
Hello,

I have a question concerning the best way to use node specifications in TDI function.

The following function is an example of an actual function for one TCV diagnostic.
```
fun public pd_calibrated(in _diode)
/* Changed by Umar & Benoit on 28-04-2016 */
  Return(
        getnci("\\BASE::PD:PD_"//iii(_diode),"RECORD") /
        tcvpd2_gain(_diode,\VSYSTEM::DIAG2DB_I["PD_SURVEY:OUT_"//iii(_diode)])
        );
```
Notice the use of the unquoted node specification \VSYSTEM::DIAG2DB_I.

We can encounter errors when successively executing this function for shots with a large time separation (and where the tree structure might have changed ...). As can be seen in the following tdic sequence.
```
TDI> TreeOpen("tcv_shot",29892)
265388041
TDI> pd_calibrated(1)
Build_Signal(Build_With_Units(Set_Range(111751,.00252995 /*** etc. ***/), "V"), *, DIM_OF(\BASE::TRCH_PD_001:CHANNEL_001))
TDI> TreeOpen("tcv_shot",61293)
265388041
TDI> _y=pd_calibrated(1);
%TDI Error in LONG(*)
%TDI Error in SUBSCRIPT(\HYBRID::WAVE_GEN_B:OUTPUT_16:OFFSET, "PD_SURVEY:OUT_" // iii(_diode))
%TDI Error in EVALUATE(\HYBRID::WAVE_GEN_B:OUTPUT_16:OFFSET["PD_SURVEY:OUT_" // iii(_diode)])
%TDI Error in EXT_FUNCTION(*, "tcvpd2_gain", _diode, \HYBRID::WAVE_GEN_B:OUTPUT_16:OFFSET["PD ...)
%TDI Error in DIVIDE(GETNCI("\\BASE::PD:PD_" // iii(_diode), "RECORD"), tcvpd2_gain(_diode, \HYBRID::WAVE_GEN_B: ...)
%TDI Error in EVALUATE(GETNCI("\\BASE::PD:PD_" // iii(_diode),  ...)
%TDI Error in RETURN(GETNCI("\\BASE::PD:PD_" // iii(_diode),  ...)
%TDI Error in EVALUATE((Return (GETNCI("\\BASE::PD:PD_" // iii( ...)
%TDI Error in EXT_FUNCTION(*, "pd_calibrated", 1)
%TDI Error in EVALUATE(pd_calibrated(1))
%TDI Error in EQUALS(_y, pd_calibrated(1))
%TDI Error in EVALUATE(_y = pd_calibrated(1))
%TDI Error in EXECUTE("_y=pd_calibrated(1);")
```
Now we think we understand why this happens. At the time of the first execution, the function is compiled and the unquoted node specification is replaced with its corresponding NID. However for the second execution, this NID does not correspond anymore to \VSYSTEM::DIAG2DB_I but to \HYBRID::WAVE_GEN_B:OUTPUT_16:OFFSET (based on the error log) due to the changes in the data structure. To get this function to execute properly for shot 61293 we would have to force a new compilation with the use of reset_public() for example. But of course then it would not work anymore for shot 29892.
```
TDI> reset_public()
*
TDI> _y=pd_calibrated(1);
TDI> TreeOpen("tcv_shot",29892)
265388041
TDI> _y=pd_calibrated(1);
%TDI Error in SUBSCRIPT(\HYBRID::WAVE_GEN_A:INIT_ACTION, "PD_SURVEY:OUT_" // iii(_diode))
%TDI Error in EVALUATE(\HYBRID::WAVE_GEN_A:INIT_ACTION["PD_SURVEY:OUT_" // iii(_diode)])
%TDI Error in EXT_FUNCTION(*, "tcvpd2_gain", _diode, \HYBRID::WAVE_GEN_A:INIT_ACTION["PD_SURVEY:OUT_" // iii(_diode)])
%TDI Error in DIVIDE(GETNCI("\\BASE::PD:PD_" // iii(_diode), "RECORD"), tcvpd2_gain(_diode, \HYBRID::WAVE_GEN_A: ...)
%TDI Error in EVALUATE(GETNCI("\\BASE::PD:PD_" // iii(_diode),  ...)
%TDI Error in RETURN(GETNCI("\\BASE::PD:PD_" // iii(_diode),  ...)
%TDI Error in EVALUATE((Return (GETNCI("\\BASE::PD:PD_" // iii( ...)
%TDI Error in EXT_FUNCTION(*, "pd_calibrated", 1)
%TDI Error in EVALUATE(pd_calibrated(1))
%TDI Error in EQUALS(_y, pd_calibrated(1))
%TDI Error in EVALUATE(_y = pd_calibrated(1))
%TDI Error in EXECUTE("_y=pd_calibrated(1);")

```
We have already encountered this type of errors in the past and we worked around it by replacing this unquoted node specification with accessing the record via getnci and a quoted node specification as follows.
```
fun public pd_calibrated(in _diode)
/* Changed by Umar & Benoit on 28-04-2016 */
  Return(
        getnci("\\BASE::PD:PD_"//iii(_diode),"RECORD") /
        tcvpd2_gain(_diode,getnci("\\VSYSTEM::DIAG2DB_I","record")["PD_SURVEY:OUT_"//iii(_diode)])
        );
```
This implementation works well for all shots without requiring any recompilation.

So my question is: is our solution the only workaround for this type of problem, would you recommend a different approach? I am only asking because I feel like ours is not that elegant ...

Thanks,
Antoine.

**Comment by tfredian** [comment]
Hi Antoine,
You have run into a common issue with node references in tdi functions. You should always avoid the use of node references in fun's exactly for this reason. There are other possible solutions to this problem. One simple solution is to use the build_path(str) function.  Here is an example of your function using this approach:
```
fun public pd_calibrated(in _diode)
 Return(build_path("\\BASE::PD:PD_"//iii(_diode)/tcvpd2_gain(_diode,build_path("\\VSYSTEM::DIAG2DB_I")["PD_SURVEY:OUT_"//iii(_diode)])

        );
```
Another solution is to use the execute(str) function:
```
fun public pd_calibrated(in _diode)
  Return(execute("\\BASE::PD:PD_"//iii(_diode)//"/tcvpd2_gain($1,\\VSYSTEM:DIAG2DB_I)['PD_SURVEY:OUT_'"//iii(_diode)//"])",_diode));
```
Obviously the build_path solution is cleaner in this example but in some cases the execute option might be easier.

Hope this helps!

**Comment by merlea** [comment]
Hi Tom,

Yes this helps!
And I like the build_path solution very much.

Antoine.
