### ISSUE TITLE
SSH connections broken on OSX 

### ISSUE THREAD

**Issue by amicitas** [MDSplus/mdsplus#1484]
I have run into an OSX specific problem with SSH connections. (OS X 10.14.1 Mojave)

When using the OSX package _MDSplus-alpha-7-59-1-osx.pkg_ It is not possible to connect to mdsplus servers using the ssh protocol.  SSH keys have been setup and I can make normal SSH connections to the server without any issues.  Connection to this server works fine when not using the ssh protocol.

**Example code (in python):**

```
import MDSplus
MDSplus.setenv('qsw_eval_path', 'ssh://10.44.4.11::/w7x/eval/~t;')
mdstree = MDSplus.Tree('qsw_eval', -1, 'READONLY')
```

**Output**

```
Protocol SSH is not supported.
Error in connect
Error connecting to host /ssh://username@10.44.4.11/ in io_open_remote
```
```
TreeFOPENR: %TREE-E-FOPENR, Error opening file read-only.
```

**Note:**

This code works as expected when tested on Linux.

**Versions Tested:**

-7.59.1 result: Failure
-7.54.3 result: Failure
-7.49.0 result: Failure

**System:**

- OS X 10.14.1 
- Python: 3.7.1

**Comment by joshStillerman** [comment]
For SSH, it works on my system.  if you type:
```
ls -l /usr/local/mdsplus/lib/libMdsIpSSH.dylib

```
do you get:
```
lrwxr-xr-x  1 root  wheel  20 Oct 16 09:36 /usr/local/mdsplus/lib/libMdsIpSSH.dylib -> libMdsIpTunnel.dylib
```

**Comment by amicitas** [comment]
The problem was that my system was not running the `/usr/local/mdsplus/setup.sh` script.  Once this script is loaded though standard bash resolution sequence (or is manually sourced) SSH connections work as expected.

**Comment by amicitas** [comment]
I have opened an issue related to the installation script and/or documentation: #1487 .
