### ISSUE TITLE
New 'hop' specifications for tree definitions not working

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1494]
In release:

```MDSplus version: 7.60.2
Git branch: alpha
  Git tag: alpha_release-7-60-2
  View:
    https://github.com/MDSplus/mdsplus/tree/alpha_release-7-60-2
  Download:
    https://github.com/MDSplus/mdsplus/archive/alpha_release-7-60-2.tar.gz
  Git commit: 4142debbfb738215094eacfe3ce3bbe735bd372a
  Build date: Fri Jan  4 03:09:41 UTC 2019
```
Changes to treeshr breaks trees with paths like:
```$ echo $cable_path
sparc-daq1::/sparc/trees/new/~t/;sparc-daq1::/sparc/trees/models/~t/;sparc-daq1::/sparc/trees/archives/~i~h/~g~f/~e~d/~t```
The ip address of corresponding to sparc-daq1 is:
```sparc-daq1.sparc.local has address 172.20.200.110```
But the connection fails with:
```
TCL> set tree cable
Error connecting to host: -84.20.-56.110, port 8000 error=Name or service not known
Connect failed to host: -84.20.-56.110:8000
Error connecting to host /sparc-daq1/ in io_open_one_remote
Error connecting to host: -84.20.-56.110, port 8000 error=Name or service not known
Connect failed to host: -84.20.-56.110:8000
Error connecting to host /sparc-daq1/ in io_open_one_remote
Error connecting to host: -84.20.-56.110, port 8000 error=Name or service not known
Connect failed to host: -84.20.-56.110:8000
Error connecting to host /sparc-daq1/ in io_open_one_remote
Error: Failed to open tree 'cable' shot -1
Error message was: %TREE-E-FOPENR, Error opening file read-only.
mdsdcl: --> failed on line 'set tree cable'
TCL> 
```
reverting TreeShr to alpha_release-7-60-1 fixes this problem

**Comment by zack-vii** [comment]
Hi Josh, can you find out the mdsplus version running on the sparc server. thanks

**Comment by joshStillerman** [comment]
alpha_release-7-60-2On Jan 5, 2019 5:13 AM, Timo Schroeder <notifications@github.com> wrote:Hi Josh, can you find out the mdsplus version running on the sparc server. thanks

**Comment by zack-vii** [comment]
so checking if it is client and/or server.
alpha_release-7-60-2 connecting to alpha_release-7-60-2 fails?
alpha_release-7-60-1 connecting to alpha_release-7-60-2 is ok?
alpha_release-7-60-1 connecting to alpha_release-7-60-1 is ok?
alpha_release-7-60-2 connecting to alpha_release-7-60-1 is ok?

**Comment by zack-vii** [comment]
might be the reuse check and the strange -56 in the ip.
#1496 might fix that.

**Comment by joshStillerman** [comment]
Sorry misread your previous question.  The server is running:

> [jas@sparc-daq1 ~]$ mdstcl
> TCL> sho version
>
>
> MDSplus version: 7.60.0
> Git branch: alpha
>   Git tag: alpha_release-7-60-0
>   View:
>     https://github.com/MDSplus/mdsplus/tree/alpha_release-7-60-0
>   Download:
> https://github.com/MDSplus/mdsplus/archive/alpha_release-7-60-0.tar.gz
>   Git commit: 3d2a8d5b2b05611e7bb77b73d685b0b6e7dc37a5
>   Build date: Thu Dec 20 03:10:33 UTC 2018
and the client 7.60-2.  Reverting the Treeshr on the client to 7.60-1 
fixes it.

**Comment by joshStillerman** [comment]
I can test that one in a few minutes.  These changes look interesting 
and related.  But note that reverting ONLY Treeshr fixed things.

-Josh

**Comment by zack-vii** [comment]
treeshr had its own method to resolve the hostname, i changed to use the ones feom mdstcpip to have one implementation for the same job. it is using reusecheck to get the final host string. so it might be it.
________________________________

**Comment by zack-vii** [comment]
if #1496 fixed this problem it would mark this issue for closure
