### ISSUE TITLE
MAXLOC as described in documentation is missing the rank argument

### ISSUE THREAD

**Issue by oasunta** [MDSplus/mdsplus#1511]
I tried the example in the documentation (http://www.mdsplus.org/index.php/Documentation:Reference:TDI_M2#maxloc):

TDI> _a = [[0, -5, 8, -3],[3, 4, -1, 2],[1, 5, 6, -4]]
[[0,-5,8,-3], [3,4,-1,2], [1,5,6,-4]]
TDI> shape(_a)
[4,3]
TDI> maxloc(_a)
2
TDI> maxloc(_a, _a lt 6)
%TDI Error in MAXLOC(_a, _a < 6)
%TDI Error in EVALUATE(MAXLOC(_a, _a < 6))
%TDI Error in EXECUTE("maxloc(_a, _a lt 6)")

Conclusion: In 7.49-1, MAXLOC gives a wrong answer, and doesn't understand the extra constraint. I also tested this in 7.7.9 and saw the same behaviour.

**Comment by zack-vii** [comment]
Actually this has been fixed in the exact release:
you are missing the rank argument to fit with the example.
maxloc(_a) returns the overall maxloc of the flattened array.
The example should be:
```tdi
_a = [[0, -5, 8, -3],[3, 4, -1, 2],[1, 5, 6, -4]]
[[0,-5,8,-3], [3,4,-1,2], [1,5,6,-4]]
shape(_a)
[4,3]
maxloc(_a)
2
maxloc(_a,1)
[1,2,0,1]
maxloc(_a,0)
[2,1,2]
maxloc(_a, ,_a lt 6)
9
maxloc(_a,0,_a lt 6)
[0,1,1]
maxloc(_a,1,_a lt 6)
[1,2,1,1]
```

**Comment by zack-vii** [comment]
hm maybe the last answer should be
```tdi
[1,2,2,1]
```

**Comment by oasunta** [comment]
Neither the example, nor the definition of MAXLOC, mentions rank argument. I see it in MAXVAL, though. Fixing the documentation will help, although having MAXLOC behave as currently described in the documentation would've been nice.

**Comment by zack-vii** [comment]
If you put a blank or '*' for the rank, you get the functionality you desire.
```tdi
maxloc(_a,,_a lt 6)
9
maxloc(_a,*,_a lt 6)
9
```

**Comment by zack-vii** [comment]
@joshStillerman can you send me the details on how to edit the documentation on mdsplus.org

**Comment by tfredian** [comment]
To edit the documentation on mdsplus.org you click on the "Log in" button on the bottom left. From that page you can request a login account for the wiki if you don't already have one. Once your request is granted then your enter your username and password and you should then be able to edit pages in the wiki.

**Comment by zack-vii** [comment]
[MAXLOC](http://www.mdsplus.org/index.php/Documentation:Reference:TDI_M2#maxloc) and [MINLOC](http://www.mdsplus.org/index.php/Documentation:Reference:TDI_M2#minloc) documentation updated.
