### ISSUE TITLE
Latest releases break previous tdi expressions

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1518]
The following was reported by MDSplus user:

```
TDI> psu.bvl:i
Build_With_Units(Build_Param(21810.3 * COMPILE(find_analogue_signal("I_BVL_PSU", "ain")) / 10., "PSU current", *), "A")
```
Both used to work perfectly in 7.7.-4. Do you see something obviously wrong with either one of them? Because neither returned any data in 7.49-1.el7, and the second one actually froze TDIC (and MATLAB, and iPython). I know they look a bit messy, but never mind. find_analogue_signal() simply finds the name of the node where the raw data is, the rest is just variables and standard TDI.

After downgrading from 7.49-1.el7 back to 7.49-0.el7, at least both of the above work in TDI. However, Python still fails with the latter, and MATLAB, while it works for me fails for another user. Very strange...

**Comment by zack-vii** [comment]
would be nice to have a small tree to work with.
definition of find_analogue_signal() (tdi or py)
where is teh maxloc or minloc used which would be the only thing that has changes between 7.49-1.el7 back to 7.49-0.el7.   odd

**Comment by tfredian** [comment]
replaced by #1519
