### ISSUE TITLE
Utilization of xnci feature for storing useful metadata in nodes.

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1532]
Some interesting ideas came up yesterday in our discussions. I was thinking more about the device features we were talking about like device node help and eventually device setup gui's etc.
The use of "standard" xnci's for node metadata is an interesting idea. For example, one could imaging including a description field in the parts structure for nodes in a python device and when a device is added to the tree it adds the nodes and sets a description xnci if the parts struct include one for the node. A traverser could be enhanced to pop up description's when the mouse hovers over a node for some period and the node has a description xnci. The traverser as well as TCL could be enhanced to allow the user to enter/modify the description xnci for any node in the tree possibly.

It would also be cool if we could implement a device class property which would contain some sort of setup gui specification (i.e. layout of gui "widgets" which could do things similar to the our existing device setups. The "widgets" could be selecters of a set of options, expression text fields, simple text, float, integer fields etc. One could even imagine that a single setup description could be parsed by some pyqt5 application, javascript or java so until we standardize on a single traverser app we could provide device setup on any of them.

Timo adds:
"We could even allow user to write their own xnci.. since our internal nci name are regular names (e.g. "SegmentScale" or "attributenames") we could add a prefix (e.g. '$') to the user's attribute name when reading/writing so there will be no clash. We in the future just have to make sure new internal names do not start with that prefix.

user wants to store myattribute=value and we will store value under $myattribute, easy peasy."

**Comment by zack-vii** [comment]
turned into milestone
