### ISSUE TITLE
Reading large data from segmented records over distributed client fails

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1535]
Having written 403 segments each of which returns 16000 doubles distributed client chokes when reading the data back.  It is fine with local IO  and fine with thin client.

The segments are defined as:
```
Build_Signal(.DAQ_HARDWARE:ACQ423_6_1:INPUT_001:COEFFICIENT * $VALUE + .DAQ_HARDWARE:ACQ423_6_1:INPUT_001:OFFSET, Word([38,... (16,000 of them) ], 0D0 : .9999375D0 : 62.5D-6)
```
Reading the entire data with local IO is no problem:
```
>>> data = n.data()
>>> len(data)
6448000
>>> 
```
when attempting to do this from a client computer with distributed client it chokes.
I have not yet investigated why, or tracked down the conditions that trigger this error.  

For smaller cases (200 of these segments) it works fine.

**Comment by zack-vii** [comment]
Should be fixed as of alpha 7.61.6
