### ISSUE TITLE
Open tree stack in treeshr getting corrupted

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1546]
TreeShr keeps a stack of open trees (defaults to 8 trees but can be changed) so an application can easily switch between the the trees in non object oriented api's. There appears to be a bug in the stack maintenance when an open tree is opened with a new access mode (i.e. readonly, edit or normal) causing
a tree to be dropped from the stack.

**Comment by zack-vii** [comment]
fixed by #1547
