### ISSUE TITLE
Different values of MAX_DIM

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1548]
Should we limit the number of dimensions to 7 (the number supported by the mdsip protocol)
Currently its 8 but i have seen higher numbers in different libs before.. (stable should still have them)

**Comment by joshStillerman** [comment]
I know that we have been telling people 8 for many years.  I doubt that 
anyone has used 8 though.  If it is easy to change mdsip to accommodate 
8, that would be better than making it 7 everywhere.

**Comment by zack-vii** [comment]
Actually teh message looks like this.. so the fill value would be the eighth dim no sweat, right? 
```c
typedef struct _msghdr {
  int msglen bits32;
  int status bits32;
  short length bits16;
  unsigned char nargs;
  unsigned char descriptor_idx;
  unsigned char message_id;
  unsigned char dtype;
  signed char client_type;
  unsigned char ndims;
#if defined(__CRAY) || defined(CRAY)
  long dims[(MAX_DIMS_R + 1) / 2];
#else
  int dims[MAX_DIMS_R];
  int fill;
#endif
} MsgHdr;
```

**Comment by zack-vii** [comment]
I will make a PR so we can test it for different client/server version combinations

**Comment by zack-vii** [comment]
tested it with tditest and our old version server mds-data-2, looks like the server sets ndims to 8 if 8 is teh number of dims however it can only set 7 dims so the client can reconstruct the 8th dim from the message length if it is a multiple of the numbytes value upto the 7th dim. now you can even read 8dim array from old servers.

**Comment by zack-vii** [comment]
MAX_DIM := 8
