### ISSUE TITLE
Memory error in RemoteAccess.c

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1556]
A memory error has been (I guess recently) introduced, intermittently crashing the mdsip server on my system (and likely any other program using distributed client configuration)

I tracked the error and it is due to a wrong dimension in malloc()  at line 1488 of RemoteAccess

code  
	    *fullpath = malloc(strlen(host)+2+strlen(tmp) ); 
	    sprintf(*fullpath,"%s::%s",host,tmp);

must be replaced by 

	    *fullpath = malloc(strlen(host)+2+strlen(tmp) + 1 ); 
	    sprintf(*fullpath,"%s::%s",host,tmp);

to account for the string terminator.

Who reports the fix?

**Comment by zack-vii** [comment]
@GabrieleManduchi : if you would approve the PR once it finished the tests we can merge it.

**Comment by GabrieleManduchi** [comment]
going home now, I will do it this evening.
