### ISSUE TITLE
Threads started by devices can loose their tree contexts

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1563]
The streaming acq devices create a thread on init to handle the stream.  When these are dispatched to the same action server the stream can find that self.tree is either not defined or not open (not sure yet).  

This is not a problem with a simple tcl script that inits the devices in a row.  There must be some non thread-safe handling to tree contexts. 

It is possible that this problem is not new, and we are just seeing it now that we are doing 'streaming devices' which fire up threads.  In the past most devices like this (cameras etc...) ran on dedicated servers which would have masked this problem

**Comment by zack-vii** [comment]
maybe we can add something like #1569 to Device class that would simplify this procedure

**Comment by joshStillerman** [comment]
I thought I had it: PR #1571 seemed to work.  However I am finding intermittent behavior when the actions are run by an mdsip server.  With the code as committed
```
do /meth node init
```
works fine.  While 
``` 
dispatch node:init_action
```
The server spits out (sometimes)
```
[jas@cmodws102 pydevices]$ mdsip -s -p 9999 -h /etc/mdsip.hosts 
Cannot setuid - run server as root!Fri Feb 22 16:25:42 2019 (7) (pid 14514) Connection received from jas@cmodws102.psfc.mit.edu [198.125.183.102]
Connected: jas
Fri Feb 22 16:25:43 2019, Doing \TEST::TOP:J:INIT_ACTION in TEST shot 3
Warning:
  The MDSplus python module version (7.62.7) does not match
  the version of the installed MDSplus libraries (1.0.0).
  Upgrade the module using the mdsplus/mdsobjects/python directory of the
  MDSplus installation.
doing \TEST::TOP:J(ACQ435ST).INIT()
Python error in ACQ435ST.INIT:
'ACQ435ST' object has no attribute 'copy'

Traceback (most recent call last):
  File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 58, in PyDoMethod
    return domethod(methodobj,args)
  File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 33, in domethod
    return methodobj(*args)
  File "/home/jas/mdsplus/pydevices/HtsDevices/acq435st.py", line 161, in init
    thread = self.Worker(self)
  File "/home/jas/mdsplus/pydevices/HtsDevices/acq435st.py", line 102, in __init__
    self.dev = dev.copy()
  File "/usr/lib/python2.7/site-packages/mdsplus_alpha-7.62.7-py2.7.egg/MDSplus/tree.py", line 3043, in __getattr__
    return super(Device,self).__getattr__(name)
  File "/usr/lib/python2.7/site-packages/mdsplus_alpha-7.62.7-py2.7.egg/MDSplus/tree.py", line 1396, in __getattr__
    return super(TreeNode,self).__getattr__(name)
  File "/usr/lib/python2.7/site-packages/mdsplus_alpha-7.62.7-py2.7.egg/MDSplus/mdsdata.py", line 169, in __getattr__
    return self.__getattribute__(name)
AttributeError: 'ACQ435ST' object has no attribute 'copy'
Traceback (most recent call last):
  File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 65, in PyDoMethod
    raise PyUNHANDLED_EXCEPTION
MDSplus.mdsExceptions.PyUNHANDLED_EXCEPTION: %PY-E-UNHANDLED_EXCEPTION, Python device raised an exception, see log files for more details
%PY-E-UNHANDLED_EXCEPTION: Python device raised an exception, see log files for more details
Fri Feb 22 16:25:44 2019, Done  \TEST::TOP:J:INIT_ACTION in TEST shot 3

```
copying self to persistent, or copying the thread to persistent did not change the behavior.  This is not a great surprise as the thread creator (as opposed to its run method) is executed synchronously by the init method of the device.  So the object being copied is still in scope.

I wondered about Device.__deep_copy__  which just returns self. But again, even if this is wrong, the init method of the thread is not finding the device's copy method.

I added some debug prints to display id() the original object, the thread object, and the thread's dev member and it started working.

Then I removed these extra prints and it continued to work.

**Very Very Frustrating**
My feeling at this point, since I can not reproduce these errors reliably is go go back to using processes and scripts to accomplish this.

**Comment by joshStillerman** [comment]
One possibility is to create the thread with:
Worker(self.copy())
and then have the Worker copy it again.
I am still not sure I will trust it though

**This does work, but I don't see why**

**Comment by tfredian** [comment]
I suspect the MDSplus python module you were using did not yet have the new copy that Timo had just implemented which had not yet been included in a new release.

**Comment by joshStillerman** [comment]
Then why did do/ method work and find the copy method. And why did it start working after adding and removing debugs?On Feb 23, 2019 8:34 AM, Tom Fredian <notifications@github.com> wrote:I suspect the MDSplus python module you were using did not yet have the new copy that Timo had just implemented which had not yet been included in a new release.

**Comment by tfredian** [comment]
If you look at the releases the new copy implementation was in 7.63.0 which is newer than the version you were using. I'm pretty certain all py classes have a default copy method so it wouldn't complain. The do/meth worked because there was no problem with tree ctx then.

**Comment by joshStillerman** [comment]
But ... It was complaining.  See
```
[jas@cmodws102 pydevices]$ mdsip -s -p 9999 -h /etc/mdsip.hosts 
Cannot setuid - run server as root!Fri Feb 22 16:25:42 2019 (7) (pid 14514) Connection received from jas@cmodws102.psfc.mit.edu [198.125.183.102]
Connected: jas
Fri Feb 22 16:25:43 2019, Doing \TEST::TOP:J:INIT_ACTION in TEST shot 3
Warning:
  The MDSplus python module version (7.62.7) does not match
  the version of the installed MDSplus libraries (1.0.0).
  Upgrade the module using the mdsplus/mdsobjects/python directory of the
  MDSplus installation.
doing \TEST::TOP:J(ACQ435ST).INIT()
Python error in ACQ435ST.INIT:
'ACQ435ST' object has no attribute 'copy'
...
```

**Comment by zack-vii** [comment]
you need at least version 
    alpha_release-7-63-0
So you are running an old version.

**Comment by joshStillerman** [comment]
Timo -
  With 7.63.4 I still get the error:

> TCL> set tree test
> TCL> create pulse 4
> TCL> set tree test /shot=4
> TCL> do /meth j init
> doing \TEST::TOP:J(ACQ2106_423_6ST).init()
> Python error in ACQ2106_423_6ST.init:
> __new__() takes at least 2 arguments (1 given)
> 
> Traceback (most recent call last):
>   File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 58, in PyDoMethod
>     return domethod(methodobj,args)
>   File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 33, in domethod
>     return methodobj(*args)
>   File "/home/jas/mdsplus/pydevices/HtsDevices/acq2106_423st.py", line 137, in init
>     thread = self.Worker(self)
>   File "/home/jas/mdsplus/pydevices/HtsDevices/acq2106_423st.py", line 98, in __init__
>     self.dev = dev.copy()
>   File "/usr/lib64/python2.7/copy.py", line 96, in copy
>     return _reconstruct(x, rv, 0)
>   File "/usr/lib64/python2.7/copy.py", line 329, in _reconstruct
>     y = callable(*args)
>   File "/usr/lib64/python2.7/copy_reg.py", line 93, in __newobj__
>     return cls.__new__(cls, *args)
> TypeError: __new__() takes at least 2 arguments (1 given)
> Traceback (most recent call last):
>   File "/usr/local/mdsplus/tdi/dev_support/PyDoMethod.py", line 65, in PyDoMethod
>     raise PyUNHANDLED_EXCEPTION
> MDSplus.mdsExceptions.PyUNHANDLED_EXCEPTION: %PY-E-UNHANDLED_EXCEPTION, Python device raised an exception, see log files for more details
> %PY-E-UNHANDLED_EXCEPTION: Python device raised an exception, see log files for more details
> Error executing device method
> Error message was: %PY-E-UNHANDLED_EXCEPTION, Python device raised an exception, see log files for more details
> mdsdcl: --> failed on line 'do /meth j init'
> TCL> show version
> 
> 
> MDSplus version: 7.63.4
> Git branch: alpha
>   Git tag: alpha_release-7-63-4
>   View:
>     https://github.com/MDSplus/mdsplus/tree/alpha_release-7-63-4
>   Download:
>     https://github.com/MDSplus/mdsplus/archive/alpha_release-7-63-4.tar.gz
>   Git commit: 70b7580e6fded89ae13a07f8dc873743ba7d0299
>   Build date: Wed Feb 27 23:10:48 UTC 2019
> 
>

**Comment by zack-vii** [comment]
We updated the device driver in PR #1592 : the reason for the issue was an from copy import copy command in the scope of the subclasses. This overrode the original copy method. to copy lists you can either use
```python
list_copy = list(list_orig)
```
or involve the list in a sum of lists to append new elements
```python
list_copy = list_orig + [
    first_new_element,
    ...
    ]
```
