### ISSUE TITLE
tditest broken in recent releases

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1583]
Several shell scripts using tditest are in use in cron jobs which do something like:
```
#!/bin/sh
tditest <<EOF > /dev/null
<tdi-commands>
EOF
```
These now result in segfaults. The tdi commands do get executed but there is a segfault when the EOF is reached. A simple test which could be added to the test suite which exhibits the behavior is:

```
#!/bin/sh
tditest <<EOF
42
EOF
```

**Comment by zack-vii** [comment]
this has been fixed in PR #1565 but josh still has problem getting it to work on his machine
