### ISSUE TITLE
Distributed client fails in createPulse() (and other operations)

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1590]
With the latest alpha, distributed client fails when in create pulse.
The issue is at the server side and appears only in alpha branch (on stable it works with the same configuration)

**Comment by GabrieleManduchi** [comment]
More info: this happens only with RedPitaya client (running alpha)

**Comment by GabrieleManduchi** [comment]
In summary: RedPitaya client alpha, mdsip server stable  -> works
RedPitaya client alpha, mdsip server alpha -> error

**Comment by tfredian** [comment]
I have no idea how to debug this since I don't have a RedPitaya client. Can you debug the problem there?

**Comment by zack-vii** [comment]
the problem is if the client calls TreeCreatePulse.fun in RemoteAccess.c. TreeCreatePulse has swapped args. please update the client and the server.

alpha and stable alone does not help much if you dont provide the version number

**Comment by zack-vii** [comment]
@GabrieleManduchi : can you provide some feedback please.
