### ISSUE TITLE
new Devices repository

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1603]
Can someone add a new repository named Devices where we can hold contributed devices.

I would like to organize the repo the following:
python/<VENDOR>/<DEVICE_CLASS>/<MODEL>.py
tdi/<VENDOR>/<DEVICE_CLASS>/<MODEL>/<MODEL>_<method>.fun

**Comment by zack-vii** [comment]
I added it to MDSplus.org User Contributions

**Comment by tfredian** [comment]
MDSplus/Devices repository created.
