### ISSUE TITLE
Problem with tdi ident in python not retaining context

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1606]
A user analyzing MDSplus data ran into another tree context issue when using python to access data stored in an MDSplus tree. In this case the node he was accessing contained tdi expressions which referenced other nodes in the tree and used tdi variables:

```
_SIG = .GAS.MKS:B_BOT_CAL * .GAS.MKS:B_BOT_RAW, _DAT = [_SIG], _DIM = DIM_OF(_SIG), Build_With_Units(Build_Signal(_DAT - SUM(_DAT[0 : 99 : *]) / 100, *, _DIM), "mtorr")
```
The python used to access this node does the following:

```
>>> time=tree.getNode(('\\b_bot_mks')).dim_of().data()
```

This results in a TREE-W-NOT_OPEN error. Since the dim_of() method is returning the _DIM tdi variable it appears that idents defined in a node expression are not retaining the tree context.

There is a quick fix:

```
>>> time = pressure.tdiExecute('data(dim_of(\\b_bot_mks))').data()
```

but I believe the previous code in the analysis script used to work and this context issue should be fixed if possible.

**Comment by zack-vii** [comment]
Idents are scalars. yes i think they need some special treatment as scalars are considered atomic.
