### ISSUE TITLE
Windows 10 installation is not working

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1649]
The new alpha version for Windows does not work on Windows 10 (it works on Windows7)

After installation every MDSplus command gives an error about symbol not found in the corresponding MDSplus dll in c:\Windows\System32

**Comment by GabrieleManduchi** [comment]
This happens on every Windows10 system, while the stable works.

On Windows 7 both stable and alpha work

**Comment by zack-vii** [comment]
can you be more specific I am using windows 10 and alpha and i have no problems. Is is possible you did not close all applications during installation. make sure no file remained in bin64 of the installation folder. they should have been moved to System32

**Comment by GabrieleManduchi** [comment]
When MDSPlus alpha is installed on a Windows10 system already hosting a previous MDSplus version (that gets de-installed duting the installation of the new one), then every MDSplus program fails  with an error about symbol not found in the corresponding MDSplus dll in c:\Windows\System32.
This has been replicated on two different machines (no MDSplus tool running during installation)

HOWEVER there is a magic recipe:  after installing failing alpha, re-install stable and then re-install again alpha. From that point onwards, MDSplus works (even if alpha is further re-installed).   Again, this has been replicated on two different systems.

So, even if the reason for this remains a mystery, I would consider this issue closed
