### ISSUE TITLE
Problems and changed behavior in python treenode nci properties

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1655]
The data types of the nci properties of TreeNode instances in the MDSplus python module has changed between stable and alpha. This has the potential of breaking user code which might depend on nci properties being returned as MDSplus data type instances. It also can cause problems if one tries to use these in python based tdi fun's since sometime they produce errors when trying to convert the nci property back into an MDSplus data type which tdi fun's need to do.

Here is an example of the behavior currently in the alpha branch:

```
>>> n=Tree('mytree',-1).MYNODE
>>> type(n.rfa)
<type 'long'>
>>> type(n.time_inserted)
<type 'int'>
```

but in the stable branch:

```
>>> type(n.rfa)
<class 'MDSplus.mdsscalar.Uint64'>
>>> type(n.time_inserted)
<class 'MDSplus.mdsscalar.Uint64'>
```

If one of these values is returned by a python based tdi fun it is automatically converted to an MDSplus data type but the current alpha has problems doing this:

```
>>> makeData(n.rfa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/MDSplus/mdsscalar.py", line 108, in __init__
    self._value = self._ntype(value)
OverflowError: Python int too large to convert to C long
```

One of the advantages of nci properties being returned as MDSplus data types is one used to be able to do things such as:

```
>>> print n.time_inserted.date
17-APR-2019 12:33:59.44
```

It is fairly trivial to convert MDSplus data types to native python data types if needed so it is difficult to justify such a change in the API/ABI of the python module. If there is a consensus to keep the new behavior at a minimum the problem above regarding makeData(n.rfa) needs to be addressed.

**Comment by zack-vii** [comment]
I agree on the makeData part can you tell me what rfa is.. a long but what value
the issue lies within int/long conversion int mdsplus types. is this on python2 i assume

**Comment by tfredian** [comment]
The rfa field is defined in treeshrp and is 48 bits so needs to be returned as a 64-bit value. As the error message shows above it is python2.7

**Comment by zack-vii** [comment]
can you give me the return value of n.rfa please

point is if i do the above i have no problem with makeData on python2
the error should only occur if _ver.bit_length(value)<=31 but value still does not fin in int32.. i wonder when that should be.

**Comment by tfredian** [comment]
with stable:
```
>>> n.rfa  
4294966784QU
```
with alpha:
```
>>> n.rfa
18446744073709551104L
>>> makeData(n.rfa)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/MDSplus/mdsscalar.py", line 108, in __init__
    self._value = self._ntype(value)
OverflowError: Python int too large to convert to C long
```

**Comment by tfredian** [comment]
This overflow is likely caused because getnci does not check the data_in_nci flag when returning the rfa and if I recall correctly when the data is stored in the nci it probably writes in the rfa field of the nci. I don't know if this error would occur with reasonable rfa values but I think the handling of this should be fixed. We may want to check the data_in_nci flag in TreeGetNci and return 0 for rfa if set to be cleaner.

**Comment by zack-vii** [comment]
i think the problem is that scalar.__new__ decides to use Int64 as datatype but should have used Uint64, we could add a test for value>=0x8000000000000000 in which case we have to use Uint64,
well maybe nci should retunr MDSplus.Types to avoid such conversions
