### ISSUE TITLE
DIII-D Pointname Accessible from PSFC Network, but not DIII-D Network

### ISSUE THREAD

**Issue by kjmontes** [MDSplus/mdsplus#1656]
Hi @joshStillerman and others,

I encountered an issue today that I am not sure how to debug when trying to access the `limloc` pointname using the MATLAB mdsplus commands. I executed the following lines of code in MATLAB on both a C-Mod and MFE workstation at the PSFC, and on the IRIS head node at DIII-D:

```
mdsconnect('atlas.gat.com');
mdsopen('efit03',175697);
a = mdsvalue('\top.results.aeqdsk.limloc');
```
On the PSFC workstations, this returns a cell array of data that should be stored at this pointname:
```
>> whos a
  Name         Size             Bytes  Class    Attributes

  a         1239x1             145592  cell
```
However, when executed at DIII-D the following error is returned:
```
>> a

a =

    'Java exception occurred: 
     MDSplus.MdsException: Unexpected returned data type in mdsip connection
     	at MDSplus.Connection.get(Native Method)
     	at MDSplus.Connection.get(Connection.java:61)
     	at MDSplus.Connection.get(Connection.java:66)'
``` 
Many other pointnames in this tree can be read from both the PSFC and GA to produce the same results, hinting that this is a problem with `limloc` only? Do you know what may be causing this? 

Thanks,
Kevin Montes

**Comment by joshStillerman** [comment]
Do things that work at GA return cell arrays?On Apr 18, 2019 7:12 AM, Kevin <notifications@github.com> wrote:Hi @joshStillerman and others,
I encountered an issue today that I am not sure how to debug when trying to access the limloc pointname using the MATLAB mdsplus commands. I executed the following lines of code in MATLAB on both a C-Mod and MFE workstation at the PSFC, and on the IRIS head node at DIII-D:
mdsconnect('atlas.gat.com');
mdsopen('efit03',175697);
a = mdsvalue('\top.results.aeqdsk.limloc');

On the PSFC workstations, this returns a cell array of data that should be stored at this pointname:
>> whos a
  Name         Size             Bytes  Class    Attributes

  a         1239x1             145592  cell

However, when executed at DIII-D the following error is returned:
>> a

a =

    'Java exception occurred: 
     MDSplus.MdsException: Unexpected returned data type in mdsip connection
     	at MDSplus.Connection.get(Native Method)
     	at MDSplus.Connection.get(Connection.java:61)
     	at MDSplus.Connection.get(Connection.java:66)'

Many other pointnames in this tree can be read from both the PSFC and GA to produce the same results, hinting that this is a problem with limloc only? Do you know what may be causing this?
Thanks,
Kevin Montes

**Comment by kjmontes** [comment]
Actually no, it looks like that might be the issue. All the pointnames that I have retrieved successfully so far at GA are single or double arrays. I just tried this with the `qmflag` pointname as well, which returns a cell array when executed from MIT but returns the same error as above when executed from GA:

```
mdsconnect('atlas.gat.com');
mdsopen('efit03',175697);
a = mdsvalue('\top.results.aeqdsk.qmflag');
```

**Comment by joshStillerman** [comment]
Kevin,
  On the computer at GA type
$ mdstcl
TCL> show versin

And tell me the output

**Comment by kjmontes** [comment]
Here is the output on GA:
```
[montesk@irisc ~]$ mdstcl
TCL> show version
MDSplus, beta version
```

**Comment by kjmontes** [comment]
@joshStillerman it looks like this issue was never resolved. I still see that it works from MIT and not from GA. Any updates on the status? Thanks!

**Comment by zack-vii** [comment]
it might have been resolved in 7.96.9, no?

**Comment by joshStillerman** [comment]
I would like to re-open this conversation.  Is this still a problem ?

**Comment by zack-vii** [comment]
seems to be fixed then
