### ISSUE TITLE
initd service 8000 does not accept clients on alpha

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1682]
Connection to alpha 7.74.1 from any version the client complains:
```tdi
mdsconnect("localhost")

GetMdsMsg shutdown connection 0: bad msg header, header.ndims=108, client_type=0
Error in connect
mdsopen: Could not open connection to MDS server
0
```

while the server logs:

```log
Error resolving ip of socket 0, error: Transport endpoint is not connected 
error getting hostinfo: Transport endpoint is not connected
Access denied: user
Error sending data to remote server: Broken pipe
```

**Comment by zack-vii** [comment]
I updated from 7.71.2. after downgrading back to 7.71.2, the functionality of mdsipd service is restored.

**Comment by tfredian** [comment]
I tried this on systems running rhel6, fc23, fc28 and Ubuntu18.04 and all the redhat os's worked fine but the Ubuntu system got the same error you posted. It turns out that the problem is that xinetd.d/mdsip runs the /usr/local/mdsplus/bin/mdsipd script which runs /bin/sh and not /bin/bash. On redhat systems /bin/sh is a symlink to bash but debian/ubuntu systems it is a different shell which seems to be incompatible with the  /usr/local/mdsplus/setup.sh script which is sourced by mdsipd. Try changing mdsipd to use /bin/bash and see if that fixes your problems. If so, we can put in a PR to make that change.

**Comment by zack-vii** [comment]
The error seems to be introduced between 7-73-0 and 7-74-0.

**Comment by tfredian** [comment]
works fine here. Weird. and the /bin/sh in mdsipd was there for decades! Weird.

**Comment by tfredian** [comment]
```
twf@MFEWS02:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
twf@MFEWS02:~$ uname -a
Linux MFEWS02 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
twf@MFEWS02:~$ tditest
mdsconnect('localhost')
1
tcl('show version')

MDSplus version: 7.74.1
Git branch: alpha
  Git tag: alpha_release-7-74-1
  View:
    https://github.com/MDSplus/mdsplus/tree/alpha_release-7-74-1
  Download:
    https://github.com/MDSplus/mdsplus/archive/alpha_release-7-74-1.tar.gz
  Git commit: 0fa215c050c86d62a9400adc689e6be4c916b227
  Build date: Sat May 11 19:13:19 UTC 2019

```
Only after changing /bin/sh to /bin/bash in mdsipd.

**Comment by zack-vii** [comment]
i think its the change in setup.sh which has a new dependency

**Comment by tfredian** [comment]
Could be. Try doing; telnet localhost 8000
I did that and it did have problems with setup.sh which switching to bash fixed.

**Comment by zack-vii** [comment]
Confirmed the edgecase in setup.sh commit breaks it for debian

**Comment by zack-vii** [comment]
line 100 and 106 has an  unexpected operator for /bin/sh

**Comment by zack-vii** [comment]
got it its the == in test which should be a single =.

**Comment by tfredian** [comment]
good find!

**Comment by tfredian** [comment]
PR coming or should I?

**Comment by zack-vii** [comment]
comming
