### ISSUE TITLE
Twf use weakref for active tree #155 raises errors when tree ref  is gone

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#169]
Since TreeNode.tree is a proxy instead of a ref checking its validity using

```
TreeNode.tree is None
```

fails and the following use of tree in the Context of a Tree type will reise an error:

> ReferenceError: weakly-referenced object no longer exists

In order to change tree to a weakref you need to either

use weakref.ref and replace each "read" appearance of TreeNode.tree with TreeNode.tree()

or change the condition "TreeNode.tree is None" to something that check if the proxy ist still valid

**Comment by tfredian** [comment]
I went through all this when changing to weakref and thought I fixed all 
the problems that produced this error. Can you tell me under which 
circumstances you still get this error? I tested this with python27 and 
python34 and it just worked.

Thanks,
Tom

**Comment by zack-vii** [comment]
The error occurs is a treenode is passed down by a user function. All references within the function are closed but the treenode keeps its .tree attribute which is called when decompiling for **repr**:
full error:

```
  File "E:\PortableProgs\Python\python-2.7.10\Lib\site-packages\MDSplus\mdsdata.py", line 507, in decompile
    return _tdishr.TdiDecompile(self)
  File "E:\PortableProgs\Python\python-2.7.10\Lib\site-packages\MDSplus\_tdishr.py", line 54, in TdiDecompile
    return _ver.tostr(_TdiShrFun(TdiShr.TdiDecompile,"Error decompiling",expression))
  File "E:\PortableProgs\Python\python-2.7.10\Lib\site-packages\MDSplus\_tdishr.py", line 29, in _TdiShrFun
    arguments = [_C.pointer(descriptor(expression))]+parseArguments(args)+[_C.pointer(xd),_C.c_void_p(-1)]
  File "E:\PortableProgs\Python\python-2.7.10\Lib\site-packages\MDSplus\_descriptor.py", line 214, in __init__
    value.restoreContext()
  File "E:\PortableProgs\Python\python-2.7.10\Lib\site-packages\MDSplus\treenode.py", line 1000, in restoreContext
    self.tree.restoreContext()
ReferenceError: weakly-referenced object no longer exists
```

I made a pull request for a suggestion. I am not sure if it conserves the desired behaviour introduced by weakref

**Comment by zack-vii** [comment]
I think the old way fixed the reference problem with the cleanup. the suggestion in #171 restores the faulty behaviour. but eventually it is possible to turn tree into a property. I did not know how to deal with these static methods.

**Comment by tfredian** [comment]
This should now be fixed.
