### ISSUE TITLE
segfault on tcl do /meth if method has arguments

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1718]
When invoking TCL DO/METHOD if the method has a string argument TdiIntrinsic segfaults:

```
TCL> do /meth lh_encoder set_event/arg="""LH2_START"""
Segmentation fault (core dumped)
```
This is because the third argument to TdiIntrisic is declared as:
```
struct descriptor *list[]
```
and the code in TclDoMethod is passing the address of a descriptor.

However, making a pointer to that and passing its address, while preventing the seg_fault does not have the desired effect.

**Comment by joshStillerman** [comment]
Passing the address of the pointer, fixes the problem.  Now I just need to find out why the event lookup function is undefined

**Comment by zack-vii** [comment]
is this still an issue? where to find teh lh_encoder  device?

**Comment by joshStillerman** [comment]
This works now - don't remember which PR fixed it.
