### ISSUE TITLE
Unable to find tkvx4244.h

### ISSUE THREAD

**Issue by sulemanzp** [MDSplus/mdsplus#174]
Hi... I was looking for VX4244 library.. I only found tkvx4244.c and DLL file.. But where is tkvx4244.h file which is mentioned in the include of tkvx4244.c file..

**Comment by tfredian** [comment]
This is in  the kbsi device modules which was to support a Tektronix 
VX4244 digitizer. Looking at the module comments it seems this was a 
header file provided with the driver (possibly for Windows) for that 
device. The kbsidevices library is not distributed as part of the 
MDSplus package but the source code was included in the repository as 
provided by KBSI. A web search for this header only comes up with hits 
on MDSplus so my guess is that this device and  header is probably obsolete.
