### ISSUE TITLE
Uncomprehended behaviour with executable using statically linked MDSplus libraries

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1745]
Hello,

I am getting some error when trying to use only static MDSplus libraries. The problem appears when I am reading a node containing an expression which calls a TDI function containing a call to an MDS library (in the form libname->function(args)).
In this case the TDI function is GetSegment.fun and the library is TreeShr. If I link my executable using the shared version of TreeShr, it works fine. If instead I use the static version, the code fails (it ultimately triggers a floating point exception when processing the rest of the expression).
Before I try to extract a simpler test case, has anyone experienced something similar? Is that a known issue/limitation? I was using stable_release_7-46-1 and have not tested this yet with stable or alpha ...

Thanks,
Antoine.

**Comment by merlea** [comment]
I have made tests with stable and alpha, and this behaviour seems to have disappeared.
I guess this means we can close the issue, but I am still curious as to what was causing this ...

**Comment by tfredian** [comment]
Is it possible that the applications using the static libraries were out of sync with the version of the shared libraries installed on the system? There was a change in the MDSplus internals a while back which changed the MdsEND_ARG value used to indicate the end of a variable length argument list for tdishr entry points. If the static applications were built from a version of the source code which differed from the source code used for the installed shared libraries this could have caused such a problem.
