### ISSUE TITLE
Question about getNode methods and _TreeFindNode

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1749]
Hi,

My question relates to the getNode methods in the object oriented interfaces when the base object is a TreeNode (i.e. we are looking for a node relative to the current one).
The C++ interface does this by setting temporarily the default node of the tree to our current node but this seems like there could be a race condition if two searches are happening at the same time on the same tree context. The Python interface does this by modifying the relative path into an absolute path and although this is probably thread-safe, this seems inefficient to me.

After looking at the _TreeFindNode C function, I see that the underlying Search function accepts a start argument and _TreeFindNode passes the default node for that argument. How about also having a start argument for the _TreeFindNode function such that we can pass this information from the OO methods? Alternatively, if we do not want to change the existing interface we could also define a new function with that new argument?

What do you think?

Best,
Antoine.

**Comment by tfredian** [comment]
Hi Antoine,

Interesting idea. We will look into this further. I suspect we would probably choose to add a new function which the _TreeFindNode routine could call and then change many of the existing internal MDSplus references to _TreeFindNode to the new routine providing a more thread safe implementation.

Thanks,
Tom

**Comment by merlea** [comment]
Great, let me know if I can help.
