### ISSUE TITLE
java projects to maven - set up jenkins server?

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1752]
I was thinking after being inspired by a colleague if we should start building our java projects with maven.. we could even publish some one maven-central so users can include our api in their projects. The benefit for us would be an easy way to implement junit tests (at least for non-gui functionality). I was thinking of some extra make commands
```sh
make maven-compile # compile source
make maven-test    # perform tests
make maven-package # create jars
make maven-deploy  # publish on maven-central (requires credential only on jenkins server)
```
so we can maintain original make behavior, allowing to build w/o maven.

What are your opinions about this? I think the mds interface is sexy as well as the plotting interface (but we should disentangle it from mdsplus specifics)

**Comment by GabrieleManduchi** [comment]
Seems  interesting, but I have no specific knowledge on Maven, being only a user for maven projects (such as ITER CCS).
Regarding the plotting interface, jScope is already disentangled from MDSplus except for the MdsDataProvider DataProvider instance (of course)

**Comment by zack-vii** [comment]
i will play with it a bit. i already have some junit tests for javatraverser2 if it works smoothly i will putt together a pr and maybe we can integrate it in jenkins. jenkins would nee an account on sonatypes jira for this to work. but there is lots of time for that to happen. i will be on vacation for a month soon ;)

**Comment by zack-vii** [comment]
I am currently trying to get an account.
https://issues.sonatype.org/browse/OSSRH-50399

**Comment by zack-vii** [comment]
@GabrieleManduchi: On that matter do think it makes sense to gather all java projects into one folder e.g.
```
./javaclient      -> ./java/client
./javadevices     -> ./java/devices
./javascope       -> ./java/jscope
./javatraverser   -> ./java/jtraverser
./javatraverser2  -> ./java/jtraverser2
./mdsobjects/java -> ./java/mdsobjects
./javamds         -> ?
```

**Comment by zack-vii** [comment]
Hm maybe we can set up our own nexus server on mdsplus.org. Or someone else needs to to the account. they asked me to do one of the two
I dont quite get what you mean.

* Add a TXT record to your DNS referencing this JIRA ticket: OSSRH-50399 (Fastest)
* Setup a redirect to your Github page (if it does not already exist)

I don't quite get what they mean by the first option but if I understand correctly they want me to register some reference on the DNS which is probably only in the hand of MIT IT.
And we definitely dont want to redirect mdsplus.org to github. So our own nexus would be easier i think. I will set one up locally and if you all approve we can settle down for a PR.

**Comment by zack-vii** [comment]
woop we got approved. https://oss.sonatype.org/content/repositories/snapshots/org/mdsplus/mdsplus-api/

**Comment by zack-vii** [comment]
I succeeded in deploying a first project 'mdsplus-api' to groupid 'org.mdsplus'. eventually i will have a working procedure ready that we can launch from jenkins by the day after tomorrow. otherwise in september ;)

**Comment by zack-vii** [comment]
now we could install maven on the jenkins server and set up an account on https://issues.sonatype.org so we can create a job that will publish to maven-central. it could be execute manually for now and later eventually run the job on a conditional trigger.
E.g.:
```
if (git diff <last release> --name-only | grep /mdsplus-api/)
```

**Comment by tfredian** [comment]
I know absolutely nothing about maven, maven-central or sonatype.org. We do pay for the use of mdsplus.org dns domain though. We could define other hosts (i.e. maven.mdsplus.org) if needed that point to any server. Currently the jenkins2 server is behind a firewall and the jenkins2.mdsplus.org dns actually points to our www-internal.psfc.mit.edu web server and all http connections to jenkins2 get forwarded by apache on www-internal.psfc.mit.edu to our mdsplus-jenkins2.psfc.mit.edu where jenkins is running.

I have no idea how a maven server is accessed or what would need to connect to it. If it would only need to be accessed by jenkins jobs it seems like it could be installed on the jenkins server and accessed by jobs targeted to a mdsplus-jenkins2 slave. If it needs to be accessed by other hosts then it might be best to set it up elsewhere and assign an mdsplus.org dns entry to point to it.

**Comment by zack-vii** [comment]
well basically maven-central is like a repo. yes we could make our own server but publishing on https://issues.sonatype.org is free of charge and has the benefit that the user does not have to setup anything other that the default. I can make an account for jenkins2 basically then i would need to put the credential in /mdsplus/certs and everything else could run in a minimal docker image provide by maven.
```
$ cat deploy/os/maven.opts
--platform=maven --dockerimage=maven:3.6.1-jdk-8
```
I can start setting it up and see how far i can go before hitting the limitations of groovy.

**Comment by zack-vii** [comment]
finalized by #1791
