### ISSUE TITLE
trim_last_segment

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1755]
I ran into a problem with the recent MDSplus in ITER IMAS. In that project I define segmented nodes with a complicated expression describing the segment start, end and dimension.

Several programs that worked before now crash very deep in TDI call frames. After some investigation, I realized that this is due to the code below in this piece of code of trim_last_segment()  (TreeSegments.c)

fallback: ;
    status = LibFindImageSymbol_C("TdiShr", "_TdiExecute", &_TdiExecute);
    if STATUS_OK {
       STATIC_CONSTANT DESCRIPTOR(expression, "execute('$1[$2 : $2+$3-1]',$1,lbound($1,-1),$2)");
      DESCRIPTOR_LONG(row_d, &filled_rows);
      status = _TdiExecute(&dbid,&expression,dim,&row_d,dim MDS_END_ARG);
    }
  return status;
}

the reason may be some inconsistent definition from users of the dimension expression, but I wonder why not simply calling _TdiCompile in place of TdiExecute (this is what I did to solve the problem in this specific application). After all getSegment() is not expected to resolve the dimension, just return an expression that describes it. Very often GetSegment() is called just to get the segment data, regardless the returned dimension, and indeed this is the typical use case in ITER IMAS applications.  Of course, if the dimension is not correctly defined it will fail (possibly not crash!!) when evaluated, but I see no reason for blocking getSegment() when dimension must not be evaluated.

**Comment by zack-vii** [comment]
fixed by #1757
