### ISSUE TITLE
Build pipeline does not respect --with-java_target

### ISSUE THREAD

**Issue by alexrobomind** [MDSplus/mdsplus#1792]
When running a build with CONFIGURE_PARAMETERS=--with-java_target=6 I would expect the build pipeline to generate jar files compatible to java 1.6. However, this is not the case (loading the jars causes the error "unsupported class file version 52.0" (which indicates a java 1.8 class file).

Digging a bit into the build pipeline, I found the following lines in configure.ac:

```
AC_ARG_WITH([java_target],
	    [AS_HELP_STRING([--with-java_target=version],
                            [specify version of compiled mdsobjects classes (i.e. 6)])],
            [AS_VAR_SET([JAVAVERSION], ["-source $withval -target $withval"])],
            [AS_VAR_SET([JAVAVERSION], [])])
```

However, when looking into the java/mdsobjects/makefile.in I find these lines
```
JAVAVERSION = @JAVAVERSION@

...

echo '$(CLASSPATH_ENV) $(JAVAC) -d $(JAVAROOT) $(AM_JAVACFLAGS) $(JAVACFLAGS) '"$$list2"; \
	  $(CLASSPATH_ENV) $(JAVAC) -d $(JAVAROOT) $(AM_JAVACFLAGS) $(JAVACFLAGS) $$list2; \
```

JAVAVERSION is unreferenced in the compilation command.

I have fixed this locally by making the following two modifications:

Change the javac compilation call to
```
echo '$(CLASSPATH_ENV) $(JAVAC) -d $(JAVAROOT) $(AM_JAVACFLAGS) $(JAVACFLAGS) $(JAVAVERSION) '"$$list2"; \
	  $(CLASSPATH_ENV) $(JAVAC) -d $(JAVAROOT) $(AM_JAVACFLAGS) $(JAVACFLAGS) $(JAVAVERSION) $$list2; \
```

and modifying the directive in configure.ac to only modify the target binary version, but not the source language version

```
AC_ARG_WITH([java_target],
	    [AS_HELP_STRING([--with-java_target=version],
                            [specify version of compiled mdsobjects classes (i.e. 6)])],
            [AS_VAR_SET([JAVAVERSION], ["-source 1.8 -target $withval"])],
            [AS_VAR_SET([JAVAVERSION], [])])
```

Is there an interest to have this patched? I can submit a pull request.

Edit: Formatting

**Comment by tfredian** [comment]
Timo, can you look into this? It is hard to tell with your java reorg when the java target version option support got dropped.

**Comment by zack-vii** [comment]
i will, i hope i can squeeze it in JAVACFLAGS or figure out if autoconf does already support this feature

**Comment by zack-vii** [comment]
@alexrobomind : I think I found a solution that satifies our needs.
