### ISSUE TITLE
python post-installer broken

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1824]
I am not sure how we are with python on linux and the PYTHONPATH way of integrating MDSplus. In order to support newer versions of debian, the current debian postinstall script should be updated as follows:
* The post-install should check for libreadline6 and if not existent try linking libreadline6 to 7
```sh
      libreadline6=$(find /usr/lib -name libreadline.so.6)
      libreadline7=$(find /usr/lib -name libreadline.so.7)
      if ( test -z $libreadline6 && ! test -z $libreadline7 )
      then ln -sfT ./libreadline.so.7 ${libreadline7/so.7/so.6}
      fi
```
* It should only run 'setup.py install' if the user agrees with 'y'. If it was previously installed that way the script may default to yes in non-interactive mode.
* In case' setup.py install' went wrong. It should skip 'setup.py install' with a warning (non-interactive) or query the user again. 'setup.py install' may fail on debian-buster if 'python3-distutils' is not installed.

**Comment by zack-vii** [comment]
We could start building on jessie which seems to be compatible upto most recent buster.
Eventually there is a libreadline7 for wheezy by now. its just at the end of its lifecycle so its a bit of work to get a working repo from an archive

**Comment by zack-vii** [comment]
can we then eventually disentangle wheezy32 and wheezy in that process.
in Docker repo i would sort it as
```
debian/wheezy/32
debian/wheezy/64
debian/jessie/32
debian/jessie/64
```
and in mdsplus repo, I would like to split the os parameter debian_wheezy into to  {debian7-32,debian7-64,debian8-32,debian8-64}

**Comment by tfredian** [comment]
Whatever you think is appropriate. We don't have any debian usage at the PSFC as far as I know and you might have one of the biggest debian deployment there.

**Comment by zack-vii** [comment]
Thanks, I will set up the jessie docker images and setup deployment accordingly.

**Comment by zack-vii** [comment]
well for compatibility i had to follow thru with the distname but we could think of creating links similar to alpine
old
```
deb http://www.mdsplus.org/dist/DebianWheezy/repo MDSplus alpha
```
new
```
deb http://www.mdsplus.org/dist/debian/wheezy/repo MDSplus alpha
deb http://www.mdsplus.org/dist/debian/jessie/repo MDSplus alpha
deb http://www.mdsplus.org/dist/debian/stretch/repo MDSplus alpha
deb http://www.mdsplus.org/dist/debian/buster/repo MDSplus alpha
deb http://www.mdsplus.org/dist/debian/cid/repo MDSplus alpha
```
whereas buster and cid map to stretch and jessie maps to wheezy.

So on jenkins we need to do this once:
```
cd /publish
mkdir debian
ln -sfT ../DebianWheezy debian/wheezy
ln -sfT ../DebianWheezy debian/jessie
ln -sfT ../DebianStretch debian/stretch
ln -sfT ../DebianStretch debian/buster
ln -sfT ../DebianStretch debian/cid
```

**Comment by zack-vii** [comment]
OK i updated jenkins. once alpha and stable have built for stretch i can update the links

**Comment by zack-vii** [comment]
builds now for Debian Stretch, i.e. debian9-64. I will close this for now. as it is not broken anymore but just does not work so well for newer versions
