### ISSUE TITLE
M4sh syntax typos in configure.ac

### ISSUE THREAD

**Issue by Louwrensth** [MDSplus/mdsplus#1828]
See lines 439 and [440 of configure.ac](https://github.com/MDSplus/mdsplus/blob/fabd8d730e1b8ccb15687a8b0773b1be6536cf30/configure.ac#L440) for example (there are several instances like it):
```
       JRE = "/jre";
       UIL = "/usr/bin/X11";
```
They produce errors like `JRE: command not found` when running `./configure`, which is ugly.

These sections are bash code, so it should have been:
```
       JRE="/jre";
       UIL="/usr/bin/X11";
```

**Comment by zack-vii** [comment]
Hi Louwrensth,
as far as I know, we removed those lines a while ago, at least in alpha. Did we miss any?
Cloud you please refer to the version and some line numbers? If it is fixed in alpha it will eventually be fixed in stable soon. Please verify if this issue is valid for current alpha.

**Comment by zack-vii** [comment]
Should have been fixed in alpha by #1767

**Comment by Louwrensth** [comment]
I found it in the latest release 7.84.8... 
https://github.com/MDSplus/mdsplus/blob/stable_release-7-84-8/configure.ac#L400

**Comment by Louwrensth** [comment]
I didn't see it in alpha: https://github.com/MDSplus/mdsplus/blob/alpha/configure.ac
So I guess you're good to go
