### ISSUE TITLE
Please change the Debian package dependency of mdsplus-java from 'default-jre' to 'java-runtime'

### ISSUE THREAD

**Issue by jonathanschilling** [MDSplus/mdsplus#1841]
Right now, the `mdsplus-java` package in Debian depends on `default-jre`:
```
jons@sv-e5-da-1:~$ apt-cache depends mdsplus-java
mdsplus-java
  Depends: mdsplus-java-bin
  Depends: mdsplus-kernel
  Depends: default-jre
```

I have the Oracle version installed via the `webupd8team` approach similar to this one:  [Installing the Oracle JDK](https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-debian-9) and therefore have a package called `oracle-java8-jdk` for Java, which I want to use for MDSplus as well.

In Debian, there is a virtual package called `java-runtime`, which is provided by `default-jre` as well as `oracle-java8-jdk`:
```
jons@sv-e5-da-1:~$ aptitude search "?provides(java-runtime)"
p   default-jre                       - Standard Java or Java compatible Runtime                       
p   default-jre-headless              - Standard Java or Java compatible Runtime (headless)            
p   gcj-6-jre                         - Java runtime environment using GIJ/Classpath                   
p   gcj-6-jre-headless                - Java runtime environment using GIJ/Classpath (headless version)
p   gcj-jre                           - Java runtime environment using GIJ/Classpath                   
p   gcj-jre-headless                  - Java runtime environment using GIJ/Classpath (headless version)
i   oracle-java8-jdk                  - Java Platform, Standard Edition 8 Development Kit
```

Here are the dependencies of `default-jre` and `default-jre-headless`:
```
jons@sv-e5-da-1:~$ apt-cache depends default-jre
default-jre
  Depends: default-jre-headless
  Depends: openjdk-8-jre
```

```
jons@sv-e5-da-1:~$ apt-cache depends default-jre-headless
default-jre-headless
  Depends: openjdk-8-jre-headless
  Depends: java-common
  Suggests: default-jre
  Replaces: <openjdk-6-jre-headless>
```

As you can see, using `default-jre` leads to the forced inclusion of OpenJDK, even if someone decides to prefer the Oracle version. Can this please be changed as I would like to have as few Java installations on my machine as possible (preferably 1).

**Comment by zack-vii** [comment]
Is under investigation. First tests have shown that at least under some versions default-jre is something similar but less virtual so eventually not compatible to wheezy.

**Comment by zack-vii** [comment]
attempt #1849

**Comment by zack-vii** [comment]
#1849 has been merged

**Comment by jonathanschilling** [comment]
@zack-vii Thanks for implementing this change. I tested it and at least in Debian 9 it works exactly as envisaged :-) :+1:
