### ISSUE TITLE
Feature: Conversion to defaults timebase

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1847]
I think instead of fiddling with existing code we should make this feature a plugin.
( Somewhat inspired by this guy, Bob Martin, 
https://www.youtube.com/results?search_query=Bob+Martin )
Something that wrapps around the existing code instead of infiltrating it. This way teh use has potential control over the conversion and its conditionals.
E.g.: A simple way would be tdi function tant tabs into a database linking (expt,shot,nid) -> (fromdef(d), todef(d)).
```python
import MDSplus
class database:
    @staticmethod
    def getConvert(node):
        if str(node.path).startswith("\\QSR02::"):
            return (lambda x: (x.data()*1e9).astype('int64')),(lambda x: (x.data()/1e9).astype('float64'))
        return (lambda x: x),(lambda x: x)
def defaultdim(node):
    todef,fromdef = database.getConvert(node)
    tree = MDSplus.Tree();
    tctx = tree.getTimeContext()
    ntctx = list(tctx) # copy elements
    for i in range(3):
        if tctx[i] is None: continue
        ntctx[i] = fromdef(tctx[i])
    if ntctx[i] is not None:
        ntctx[i] = ntctx[i] - fromdef(MDSplus.Data(0))
    tree.setTimeContext(*ntctx)
    try:
        sig = node.evaluate()
        if isinstance(sig,MDSplus.Signal):
            sig[2] = todef(sig.dim_of())
        return sig
    finally:
        tree.setTimeContext(*tctx)
```

**Comment by tfredian** [comment]
This might be a path forward but needs more information such as:
Where is this tdi fun referenced?
Should it be called on every node referenced in the course of evaluating a dimension or should we have some nci flag to trigger it?
Do we need a db or could we add some standard xnci options to nodes in the trees? We discussed using a db to provide tree start times for gluing signals together in time but not using a db for managing time conversions.

**Comment by tfredian** [comment]
Also, to do this efficiently it seems one would need to trigger a time conversion very close to the operation of retrieving a node in the tree which contains the timing information instead of attempting to convert when evaluating some expression which happens to reference a node with timing info. Gluing shots together based on absolute time of the data is a very complicated operation which is exactly why it has yet to be implemented even though it has been discussed for many years. :wink:

**Comment by tfredian** [comment]
Maybe autoconversion of timebases is too complicated to implement efficiently. Perhaps a better solution is to just provide a an abstime() fun whose arguments are abstime(dim,timetype,t0). An abstime() call with no args could return an array of supported timetype strings. Apps like jscope could provide a pulldown conversion selector and a t0 field. The pulldown conversion selector would include a "None" option to skip the abstime() call. The t0 field would be filled in only if the times of the signal are in relative times. Then sites could provide info on which settings should be used when displaying various signals. This would enable sites to have custom time types without requiring MDSplus code changes as you initially suggested. Similar settings and fun could be used to use relative times.

**Comment by zack-vii** [comment]
Infact, I planned on calling this automatically. but it is called in the merging expression instead. The shot merger would be a python script too. this would allow users to temper with our sample code to fit their needs, without compiling anything. I would put the database as a tdi-sql bridge with the essential queries. But again just as an example, no claim to be the best solution to all sites. Similar to what we do with the dispatcher/FiniteStateMachine. Ideally this solution should have only little c code dedications.

**Comment by zack-vii** [comment]
tutned into milestone
