### ISSUE TITLE
_TdiCompile not doing what expected

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#1851]
When compiling a node reference, _TdiCompile () crashes. This is due to the fact that no default Tree context is set before (tree context is passed to _TdiCompile()), but TreeFindNode(), called by TdiLexPath, looks for a default context and therefore crashes. 

What I understood from our discussion was that _TdiCompile() does not rely on any default context, being it passed as argument.  Am I wrong??

**Comment by tfredian** [comment]
Perhaps you are passing the ctx wrong? I just did a simple test and it worked fine for me.

```
#include <string.h>
#include <ctype.h>
#include <stdio.h>
#include <tdishr.h>
#include <treeshr.h>
#include <mdsdescrip.h>
#include <mds_stdarg.h>

int main(int argc, char **argv) {
  void *dbid = NULL;
  int status = _TreeOpen(&dbid,"test",-1,0);
  EMPTYXD(xd);
  DESCRIPTOR(foo_d,"foo");
  status = _TdiCompile(&dbid,&foo_d, &xd MDS_END_ARG);
  printf("status = %d, dtype=%d\n",status,xd.pointer->dtype);
  return status;
}

[twf@fc30 ~]$ ./t
status = 1, dtype=192

```

**Comment by GabrieleManduchi** [comment]
Hmm, maybein your example the default context has been set.  TdiLexPath, make a call to TreeFindNode, not _TreeFindNode.    I will make anyway some more check

**Comment by GabrieleManduchi** [comment]
Indeed  TdiLexPath() called by TdiLexYacc makes calls to TreeFindNode() and TreeAbsPath(), BUT NOT to _TreeFindNode()

**Comment by GabrieleManduchi** [comment]
..called by TdiYacc...

**Comment by tfredian** [comment]
_TdiCompile "pushes" the dbid ctx to a threadsafe structure and pops it when it completes. TreeCtx() used by the treeshr routines gets that threadsafe ctx. As you can see by my example it seems to work.

**Comment by GabrieleManduchi** [comment]
ah....I will check tomorrow......

**Comment by GabrieleManduchi** [comment]
My fault....it works perfectly. I close the issue
