### ISSUE TITLE
python3: intermittent ValueError encountered in openTree()

### ISSUE THREAD

**Issue by eldond** [MDSplus/mdsplus#1856]
I encountered a `ValueError` when checking status in `openTree` at `if (status & 1)==0:` because `status` was apparently not a scalar. I can't reproduce this; presumably status is normally a scalar exit code. Was status recently expanded to carry more information? If so, I suppose this check should be robust to differently shaped `status` values.

``` python
print(MDSplus.__version__)
print(sys.version_info)

server = 'atlas.gat.com:8000'
treename = 'WALL'
shot = 175192
TDI = 'IRTV.IRTV.LODIV_60RP2.DIGITAL_CAM.HEAT_FLUX2D'

conn = MDSplus.Connection(server)
conn.openTree(treename, shot)
data = conn.get(TDI, timeout=-1)
```
Results of print statements related to versions:
```
7.84.8
sys.version_info(major=3, minor=7, micro=5, releaselevel='final', serial=0)
```
Tail of exception report:
```
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 220, in openTree
    _exc.checkStatus(self.get("TreeOpen($,$)",tree,shot))
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 90, in checkStatus
    if (status & 1)==0:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I installed the python bindings for MDSplus with `pip3`.

**Comment by tfredian** [comment]
I suspect atlas is running a very old version of MDSplus. In theory self.get("TreeOpen($,$)",tree,shot) should always return an MDSplus.mdsscalar.Int32 instance. Does this problem only happen when it fails to find/open the tree and shot specified?

Could you try the following in your test program? 
```
>>> ans=conn.get('TreeOpen($,$)',treename,shot)
>>> print(ans)
```
Testing this locally, the ans returned is always an Int32 scalar whether the open succeeds or fails.

**Comment by tfredian** [comment]
The plot thickens... I just tried your test from a workstation at the MIT PSFC and it seemed to work fine.
Not sure what might be causing the problem. In theory the issue is in what is getting returned from atlas and should be independent from the version of MDSplus or python on the client end. The workstation I tried this from is running the alpha version of MDSplus and an earlier version of py3:

7.92.0
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)

I tried this several times with no errors. If I try it from my home I get an "Access Denied" during the connect which is expected.

**Comment by eldond** [comment]
Your hypothesis that atlas is running an old MDSplus version is definitely plausible.
The intermittency of the issue makes it hard to troubleshoot. I haven't figured out how to reliably reproduce it yet. I will post an update in case I do.

``` python
server = 'atlas.gat.com:8000'
treename = 'WALL'
shot = 175192
TDI = 'IRTV.IRTV.LODIV_60RP2.DIGITAL_CAM.HEAT_FLUX2D'

conn = MDSplus.Connection(server)
ans=conn.get('TreeOpen($,$)',treename,shot)
print(ans)
```
Outputs:
```
265388041
```

**Comment by tfredian** [comment]
Weird indeed. If we can track down what get of TreeOpen is returning to produce that error there might  be some chance of understanding what is causing it and how we might deal with it. Don't know if it is plausible but perhaps one could catch the error and retry. Obviously it would be better if we can prevent it though.

**Comment by eldond** [comment]
Can we blame it on cosmic rays hitting my RAM in the middle of the operation? I don't know where to start looking for more clues. Even if it randomly reproduces, I don't know how to get more information out of such an event because it worked properly when I repeated it after getting the error the first time.

**Comment by tfredian** [comment]
Sounds good to me! :wink: Not sure if it is worth it but you could put that latest test in a loop and repeat it while len(ans) < 1 and print(ans) after the loop.

**Comment by eldond** [comment]
``` python
server = 'atlas.gat.com:8000'
treename = 'WALL'
shot = 175192
TDI = 'IRTV.IRTV.LODIV_60RP2.DIGITAL_CAM.HEAT_FLUX2D'

ans = 265388041
i = 0
while len(np.atleast_1d(ans)) <= 1:
    conn = MDSplus.Connection(server)
    ans = conn.get('TreeOpen($,$)', treename, shot)
    print('got ans = {} for i = {}'.format(ans, i))
    i += 1
print(ans)
```
```
...
got ans = 265388041 for i = 575
got ans = 265388041 for i = 576
got ans = 265388041 for i = 577
got ans = 265388041 for i = 578
got ans = 265388041 for i = 579
got ans = 265388041 for i = 580
```
And then I killed it.
