### ISSUE TITLE
LIB->ROUTINE:T needs a LIB->ROUTINE:C that frees the returned pointer after copying into mds descriptor

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1865]
We could reduce memory leaks if we allow another TdiCall Type specifier that will trigger a CLASS_D return value. API methods like TreeGetMinimumPath, TreeGetPath, TreeGetTags suffer from this issue.

**Comment by zack-vii** [comment]
or we should deprecate them and add *Dsc versions

**Comment by zack-vii** [comment]
i did that, we should eventually switch to using them in tdi to show a good example.

**Comment by zack-vii** [comment]
Seems there is now way to free a returned string reference as the pointer is lost when converting the result to mdsplus descriptors.
use for lib->routine:D() remains for external lib calls.

**Comment by joshStillerman** [comment]
Sounds good

**Comment by zack-vii** [comment]
D was already used for Double. C is available (C-String) .. open for suggestions though.
