### ISSUE TITLE
User survey in progress

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1892]
**We are collecting information about  MDSplus Users**

The MDSplus project is alive and well.  The core development team is collecting information on who is using MDSplus and what parts of MDSplus they are using. We will not share the details of the information provided, but will use it to:

- Insure ongoing funding for the project from the US Department of Energy
- Create/Update a map of where MDSplus is used (opt out available)
- Invite new developers to the team
- Gather input on desired new features
- Gather input on problems / awkwardness using MDSplus

**Please fill out the survey**
[MDSplus user survey](https://docs.google.com/forms/d/e/1FAIpQLScSsA-fY2yTsW076bBreJmNbBqY9jsd-m4vmAdPvfCxXidiOQ/viewform?usp=sf_linkl)

**Comment by zack-vii** [comment]
the link should go in the wiki or the front of mdsplus.org, then this issue can be closed?
