### ISSUE TITLE
MDSIP does not configure on Windows 10

### ISSUE THREAD

**Issue by antneff** [MDSplus/mdsplus#1902]
Hello,

I have a new PC running Windows 10 Pro v. 1903. I downloaded the latest MDSplus stable version (7.92-0) for windows. I would like this system to be a small server to house some MDSplus data. Following install and checking Start->Programs, the MDSplus folder does not contain an option to setup up MDSIP. I installed with all features activated. I have tried installing/running MDSIP through windows PowerShell with no success. After entering the MDSplus\bin64 folder, I type mdsip-service and press enter I do not get a warning but nothing seems to happen but when I type mdsip, I get this error, "Mdsip single connection server can only be started from windows service." What is the best way to configure MDSIP manually, since the install did not put shortcuts in the Start Menu? 

Additionally from another post here on this page, none of the files from bin64 were inside the system32 folder following installation. I moved them there after I read the post but it does not appear to have helped. Would that affect it?

I also tried this with the alpha version 7.93-0 but nothing changed. Should I try the latest alpha version? 

Thanks,

**Comment by zack-vii** [comment]
Hi anteff,

Given that your binaries are located in MDSplus\bin64, it seems you installed a per user copy. in order to use the mdsip service you need to install mdsplus for all users with administrator privileges.

Uninstall the current version of MDSplus.
Then run the installer with elevated rights (e.g. right click: "Run as Administrator")
Select install for all users.

Please report back if this was helpful or if you need more assistance.

Cherrs

Timo

**Comment by antneff** [comment]
Thank you. That worked.

Best,
Anton



Neff, Anton L.
Postdoctoral Research Fellow
Confinement Experiments Group
Fusion Energy Division
Oak Ridge National Laboratory
(865) 576-8624
neffal@ornl.gov<mailto:neffal@ornl.gov>

On Jan 13, 2020, at 2:12 PM, Timo Schroeder <notifications@github.com<mailto:notifications@github.com>> wrote:


given that your binaries are located in MDSplus\bin64 it seems you installed a per user copy. in order to use the mdsip service you need to install mdsplus for all users with administrator privileges.

Uninstall the current version of MDSplus.
Then run the installer with elevated rights (e.g. right click: "Run as Administrator")
Select install for all users.

**Comment by zack-vii** [comment]
added hint under Software->Downloads : Windows (Latest_Windows_Distributions)
