### ISSUE TITLE
stable vs. alpha release numbers

### ISSUE THREAD

**Issue by drsmith48** [MDSplus/mdsplus#1909]
How do release numbers for stable and alpha releases relate?  For instance, is the code base for stable v7.92.0 identical to alpha v7.92.0?  Is it correct to assume that alpha 7.0.X precedes stable 7.1.X?  Thanks.

**Comment by zack-vii** [comment]
yes, when we promote alpha to stable, the version number  
of stable jumps to whatever version number alpha is at. we only do bugfixes on stable so the major version should not change otherwise.

**Comment by drsmith48** [comment]
Thanks!
