### ISSUE TITLE
Blacklist syntax (!) in mdsip.hosts is broken in 7.96-9

### ISSUE THREAD

**Issue by sflanagan** [MDSplus/mdsplus#1926]
The syntax for blacklisting mdsip connections (!) in /etc/mdsip.hosts is broken in stable-7.96-9.  

I'm not sure which revision lost this feature, but I can confirm it was working in stable-7.92-0.  

For example, with the following entry in mdsip.hosts on my dev server:

`!flanagan@*.gat.com`

I'm still allowed to connect:

```
IDL> mdsconnect,'mdsplusdev
IDL> 
```

Not urgent.  

But I do use it occasionally, so it might as well be posted here until someone is bored enough to tackle it.

**Comment by joshStillerman** [comment]
I did not know about this feature but will look into how and why it broke.On Feb 11, 2020 4:02 PM, Sean Flanagan <notifications@github.com> wrote:The syntax for blacklisting mdsip connections (!) in /etc/mdsip.hosts is broken in stable-7.96-9.
I'm not sure which revision lost this feature, but I can confirm it was working in stable-7.92-0.
For example, with the following entry in mdsip.hosts on my dev server:
!flanagan@*.gat.com
I'm still allowed to connect:
IDL> mdsconnect,'mdsplusdev
IDL> 

Not urgent.
But I do use it occasionally, so it might as well be posted here until someone is bored enough to tackle it.

**Comment by zack-vii** [comment]
found the issue. resolved in alpha PR #1927

**Comment by zack-vii** [comment]
Thanks for reporting this
