### ISSUE TITLE
Problems with MATLAB interface

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1953]
Hi Bob,

There is a bug inside mdstoMatlab.m file and the file is read-only. Could
you fix the problem?

Jinxiang

![image](https://user-images.githubusercontent.com/7458917/77335537-aa1ff180-6cfc-11ea-9f07-93d3594e440f.png)

**Comment by zack-vii** [comment]
Well thats unfair. in newer versions \"\" seems to be ok and treated just like \'\'. i will replace the double quotes with single quotes
