### ISSUE TITLE
Deprecated use of github api

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#1955]
It appears that a jenkins plugin we're currently using may break soon. I seem to recall seeing something in jenkins implying that the pull request builder plugin may be the culprit and there might be alternative options for monitoring pull requests in jenkins. It could also be one of the plugins just needs to use a different type of credential instead of a username/password. In any event this needs to be investigated before things stop working all together.

From github:

```
Hi @MDSplusBuilder,

On March 20th, 2020 at 00:42 (UTC) you used a password to access an endpoint through the GitHub API using Java/1.8.0_232:

https://api.github.com/repositories/25997031/pulls/1952/commits

Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

Thanks,
The GitHub Team
```

**Comment by zack-vii** [comment]
We updated all plugins but one used by @AndreaRigoni 's reports ().
I doubt though if this fixed the issue as the PullRequest plugin still only accepts pw logins from the available credential.
i did some token magic and tranferred ti to MDSplusBuilder. I would need teh password to finish it up or doit under my account
