### ISSUE TITLE
Update MATLAB documentation

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1956]
Thank you for responding to the MDSplus user survey!  The MATLAB interface has gone through 3 major versions and many minor revisions.  It started with a .mex file written by Basil Duval.  It was remade using the MATLAB -> JAVA connection for MDSplus object based interface. More recently we have added the option for using MATLAB->python connection.  All of these have configuration issues, which are somewhat dependent on the MATLAB version.  These have gotten easier for newer versions.  I am making an issue in our github to change the docs to accurately describe how to configure this connection for MATLAB, and mark the old configuration directions as (old).  We can put something at the top of MDSplus.org and look into adding a message at the end of the mdsplus-matlab package.

-Josh

**Comment by zack-vii** [comment]
could you add the original request, i thought i updated the docs already .. maybe at the wrong place
http://www.mdsplus.org/index.php?title=Documentation:Reference:Matlab

**Comment by joshStillerman** [comment]
I will look.  If it is already done - GREAT, thanks.  I will write the 
user...

**Comment by joshStillerman** [comment]
I have found that there are directions (varying) at:

[http://www.mdsplus.org/index.php/Downloads#How_to_use_MDSplus_with_MATLAB](http://www.mdsplus.org/index.php/Downloads#How_to_use_MDSplus_with_MATLAB)

[http://www.mdsplus.org/index.php/Latest_Macintosh_Distributions#Configuring_MATLAB_to_access_MDSplus](http://www.mdsplus.org/index.php/Latest_Macintosh_Distributions#Configuring_MATLAB_to_access_MDSplus)

[http://www.mdsplus.org/index.php/Documentation:Tutorial:MdsObjects#MATLAB_Specific_Issues](http://www.mdsplus.org/index.php/Documentation:Tutorial:MdsObjects#MATLAB_Specific_Issues)

[http://www.mdsplus.org/index.php/Documentation:Reference:Matlab#Setting_the_Matlab_Search_Path](http://www.mdsplus.org/index.php/Documentation:Reference:Matlab#Setting_the_Matlab_Search_Path)

we should look into consolidating reconciling them.

**Comment by zack-vii** [comment]
MATLAB setup is pretty much automatic now.. the magic happens in javaActivate..
