### ISSUE TITLE
jTraverser2 meets device beans

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#1958]
Requirements:
- devicebeans must be elevated to package devices, i.e. moved to java/jdevices/src/main/java/devices
- either devicebeans should wrap around mdsplus-api or need to get their API calls adapted

**Comment by zack-vii** [comment]
@GabrieleManduchi : well given that the devicebean are generate from form. i would need to change theese forms so they would generate the correct java files. how is this done. Can we add this to the bootstrap procedure. we could eventually keep the forms but intercept the generation procedure to do the required conversion.

On the other hand. would it be sufficient to drop the forms and just do a one time conversion of the java files.

**Comment by GabrieleManduchi** [comment]
The .form files generated by Netbeans are tool specific and I don't think they bring enough information to generate the Java code. Note that the generated java code is enough for device setup, the form is required by the bean builder tool (Netbeans specific) and I decided to keep in MDSplus repositpry in order to be able to make later changes to device forms. Otherwise it would not be possible to modify later a given device form using NetBeans

**Comment by zack-vii** [comment]
but do you want to keep them now. i can do the conversion of the java files. and you could adapt the forms if you wish to keep them .. is that a way to go from here? I could integrate them in jtraverser2 such that if you wish to modify them it should be easy and convenient to do so in java. This way i can leave jdevices untouched.

**Comment by GabrieleManduchi** [comment]
The java code produced by Netbeans is totally unmanageable by hand(have a look to realize it). We may think of porting the generig MDSplus device beans support code (used both by Java device forms and the Bean builder tool) in jTraverser2 and keep jdevices as it is. The only thing jTraverser2 needs to do would be to call a method named <device type>Setup(). If jdevices is in CLASSPATH it is found, otherwise jTraverser2 may resort to other ways to handle device setup.

**Comment by zack-vii** [comment]
well thats not exactly true as the device classes inherit from DeviceSetup and co which depend on jTraverser classes and api. So I at least would need to clone the Device* classes.

**Comment by zack-vii** [comment]
well i wanted to check devices setup from jtraverser but ran unto a bug with python3 PR #1959. If you could review it. I will see waht i cna do. about the java .. i was envisioning something similar as the Device* objects but little more userfriendly. i will put up one device and send it to you as a sample.

**Comment by GabrieleManduchi** [comment]
You mean because it is in jTraverser2 package?  Ok,this can be changed by hand for the existing devices  (just the import statement) and set correctly for the next ones.

**Comment by GabrieleManduchi** [comment]
Ok, approved you may merge as soon as it passes the tests.

If you change existing Device beans component you will affect all existing devices unless you keep the same API:

**Comment by zack-vii** [comment]
hm i failed to add MARTE_CONFIG from jtraverser. mdstcl and jtraverser2 worked. 
when i try setup Device, jtraverser gives me

Error in device setup: java.lang.ClassNotFound
MARTE_CONFIGSetup
[OK]

does it not work out of the box? or just not under windows... or more python3 stuff?

**Comment by zack-vii** [comment]
I will try to just implemement teh Device* classes in jtraverser2 as kind of plugin.. if the devicebeans java classes only directly inherit from Device* classes it should be fine. but there were too many to say for sure.. i will try that first then.

eventually tehn its just moving the classes into a package. and done

**Comment by GabrieleManduchi** [comment]
The Setup form is not available for that (it is a comon superclass of MARTe2 devices). Be aware that not all MARTe2 devices yet have a Setup form developed (several are still experimental)

**Comment by GabrieleManduchi** [comment]
I would add new Device components rather than changing the existing ones. The improved ones will be used in the new device forms

**Comment by zack-vii** [comment]
damn so i just choose a bad example

**Comment by GabrieleManduchi** [comment]
Take MARTE2_NI6259 for example

**Comment by zack-vii** [comment]
hm same issue.. seems the startup link is not including jDevices.jar
works if i add it though

**Comment by GabrieleManduchi** [comment]
It should

**Comment by GabrieleManduchi** [comment]
I use it regurarly

**Comment by zack-vii** [comment]
the package issue can be solved by adding 
```java
import devices.*;
```
to the top of each generated java class

**Comment by zack-vii** [comment]
What does setAllOnUnchecked do?

**Comment by GabrieleManduchi** [comment]
I will look into it....it is more that 15 years since I wrote it. There are several features that have not been used then....

**Comment by GabrieleManduchi** [comment]
It sets al jTraverser node On.  Checked/Unchecked was used to avoid accessing NCI to detect whether the node was on or off,

**Comment by zack-vii** [comment]
api specific code is in 
MARTE2_SUPERVISORSetup
NI6683RECSetup
RFXTimigSetup
RFXVConfigSetup
SPECTRO_CFGSetup

**Comment by zack-vii** [comment]
I removed the setAllOnUnchecked  calls as they have no api call in jTraverser 2 . maybe thats ok..
