### ISSUE TITLE
Can not evaluate an expression which is a reference to a node with same name as keyword

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1966]
We have a tree with a node named `\efit_geqdsk:case`.
If I pass this string to the expression evaluator everything proceeds as normal.
If however the current tree default is `\efit_geqdsk` and I ask for the value of the expression `case`, I get an error.
```
IDL> mdsopen,'analysis',1120725012
IDL> help, mdsvalue('\efit_geqdsk:case')
<Expression>    STRING    = Array[87]
IDL> mdssetdefault,'\efit_geqdsk'
IDL> help,mdsvalue('case')
% MDSVALUE: %TDI-E-SYNTAX, Bad punctuation or misspelled word or number
<Expression>    STRING    = '*'
IDL> 
```
The problem is the parser is finding the lex token CASE before seeing if it is a node.  Apparently this used to work.

**Comment by zack-vii** [comment]
is this a bug though . you can access it with
```tdi
.CASE
:CASE
```
according to the original patterns in tdilex the preceding . or : defines a path.

**Comment by joshStillerman** [comment]
It is a bug if you could before. I have not checked, but I would guess from the people involved, and the age of the data in the node, that it used to work. The node has vax f floating point constants in it.On Apr 1, 2020 6:53 PM, Timo Schroeder <notifications@github.com> wrote:
is this a bug though . you can access it with
.CASE
:CASE

according to the original patterns in tdilex the preceding . or : defines a path.

**Comment by zack-vii** [comment]
I though it might be tuff so i hoped i get arround it.. turns out ulables including CASE are fine. some are not because of ambiguity.
