### ISSUE TITLE
Test revisit mdsConnector

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#1981]
The mdsConnector remote MDSplus objects should be tested / fixed with respect to python3
The new pypy stuff may also cause concerns

**Comment by zack-vii** [comment]
well it not new stuff it more like more compatible stuff.  well mdsConnector should still work with pyhton2.7 as the MDSplus module still does. but testing it might not hurt.. maybe we could extend this to figuring out the limitations that prevent it from working with python3

**Comment by zack-vii** [comment]
can we close this?
