### ISSUE TITLE
Issue with subscripting signals with text dimension

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#1987]
Hi,

I think we have found a problem when subscripting signals with text dimension. It appears when trying to access an element which is not present. Here is an example:
```
TDI> _s = build_signal([1,2,3,4,5],*,["OH_001","OH_002","E_001 ","E_002 ","F_001 "])
Build_Signal([1,2,3,4,5], *, ["OH_001","OH_002","E_001 ","E_002 ","F_001 "])
TDI> _s["G_001 "]
Build_Signal([], *, ["\000\000\000\000\002\000","\707\702\000\000\000\000","\760\713\777ZAV","\000\000\001\000\000\000","\000\000\000\000\770\713","\777ZAV\000\000","u\000\000\000\000\000","\000\000\004\000\b\001","\000\000\000\000\b\714","\777ZAV\000\000","\004\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000Q\000","\000\000\000\000\000\000","p\742\777ZAV","\000\000\020\760\772Z","AV\000\000 *",', ["\\0',"00\\000","\\000\\0","00\\002",'\\000",','"\\707\\',"702\\00","0\\000\\","000\177\000\000","q\000\000\000\000\000","\000\000\760\703\777Z","AV\000\000\020\760","\772ZAV\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\000\000\000\000","\000\000\600\000\000\000","\000\000\000\000!\000","\000\000\000\000\000\000","\640\715\777ZAV","\000\000\020\703\777Z","AV\000\000\000\000"])
```
As you see the data part of the signal is correct, but the dimension is wrong.

I tested this on both stable and alpha branches and the result is identical.

Let me know if you need more details,
Antoine.

**Comment by zack-vii** [comment]
Hi Antoine, 
do you by chance recall when this worked. I did not even know that this is a thing. Since it is also broken in alpha it must have been broken quit a while ago.

**Comment by zack-vii** [comment]
Looks like its more a problem with decompile
Tdi1Subscript returns
```c
{
 length = 6,
 dtype = DTYPE_T,
 class = CLASS_A,
 pointer = 0x6510bc "\\000\",\"\\000\\!\004",
 scale = 0 '\000',
 digits = 0 '\000',
 aflags = {
  binscale = 0,
  redim = 1,
  column = 1,
  coeff = 1,
  bounds = 0},
 dimct = 1 '\001',
 arsize = 0,     // <- this should result in shape == [0]
}
```
And technically it does
```tdi
shape(_s["G_001 "])
[0]
```

**Comment by merlea** [comment]
Hi Timo,

> do you by chance recall when this worked. I did not even know that this is a thing. Since it is also broken in alpha it must have been broken quit a while ago.

No I don't and I am not sure it ever worked. We spotted this while we were working with a quite old version (I think from around 2015 might be before 7.0), and there it was I believe not requiring an exact match when doing this so it was returning `Build_Signal(3,*,"E_001 ")`. Then I tried with the latest and I saw this error.

Regarding your second comment, I don't know. The answer should be `Build_Signal([],*,[])`. I don't understand from what you show why the size of dim_of(_s["G_001"]) is not 0.

**Comment by zack-vii** [comment]
You are right i did shape on the signal, my bad

**Comment by zack-vii** [comment]
Alright i scratch the above, looks like teh coeff = 1 flag screws things up its is originated in 
```tdi
X_TO_I(["OH_001","OH_002","E_001 ","E_002 ","F_001 "], ["G_001 "])
```
X_TO_I is broken if there is no exact match

**Comment by zack-vii** [comment]
I filed a pull request that should resolve this issue thru better support for empty arrays

**Comment by merlea** [comment]
Thank you very much. Looking forward to testing it once it makes its way to a release.

**Comment by merlea** [comment]
Thanks again Timo. Just tested the latest releases and it works.
