### ISSUE TITLE
Java jTraverser classes compilation failed under Windows / MinGW

### ISSUE THREAD

**Issue by HerveAncher** [MDSplus/mdsplus#2021]
Dear all, 

the files` java/jtraverser/javatraverser.bat` and `java/jtraverser2/javatraverser.bat` are not named properly according the files `Makefile.am`

Normally, these files should be named respectively:
 - `java/jtraverser/traverser.bat`
 - `java/jtraverser2/traverser2.bat`

Currently, compilation failed under MinGW.
Please renamed these files in the next stable release, or modify `Makefile.am` accordingly.

Regards.

**Comment by zack-vii** [comment]
No, I am not sure where in Makefile.am you are referring to but traverser{,2}.bat are the batch scripts that will be used to start the traversers e.g. from command line or start menu. 
javatraverser{,2}.{bat,mak} are there for historical reasons and are likely not up to date. They were meant to compile from withing a windows environment. For waht you are trying to accomplish i would suggest using the --disable-java switch as java compiles platform independent and there is no harm using the original files. I am not sure where the mak files were used (before me time) but we are currently working on jtraverser/2 code and i will try to remember to double check the javatraverser?.bat files if they compile.
