### ISSUE TITLE
python do method hides exceptions from called device method

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#2031]
In the current version of tdi/dev_support/pyDoMethod.py  (line 34), if the called device method issues a python exception, this exception is trapped possibly printing a message. This has two incovenients:

1) The message makes reference to non existing python variables (model, method) so that a new exception is generated referring to this problem

2) In any case trapping such an exception is not a good idea for me since it hides the original problem in the device method making it very hard to debug it (indeed I had to comment the exception management in order to discover the problem in my device method)

**Comment by zack-vii** [comment]
oh yes that dumb, the variables are defined in the calling method and out of scope.
i will fix it.. there was another problem that prevented the traceback from showing up in the mdsip log.. which is related to the c api, that i tried to fix before.
