### ISSUE TITLE
Whats the purpose of WaveDisplay.jar?

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#2037]
WaveDisplay should be independent of jScope and may become its one project in ./java/wavedisplay.
jScope could then simple add WaveDisplay.jar as DEPENDENCY.
I assume WaveDisplay is used by jTraverser to plot date provided by jTraverser.. no need for MdsDataProvider.

most of this would be modifying access private/package/protected/public or the introduction of methods e.g.:
((Signal)src).copy(Signal dst) or getter/setter methods

**Comment by zack-vii** [comment]
i worked towards a separation in #2035 but the packages are still quite interdependant.

**Comment by GabrieleManduchi** [comment]
Timo, wait a little.....I don't think WaveDisplay is used anymore. It was an old project to provide an expression for plotting signals, esecially in python. However now everybody uses pyplot and I don't think anyone more uses WaveDisplay.   
So I would not put efforts in further splitting jscope. jscope is indeed not required directly by jtraerser, but only by devicebeans for the wave edit bean and for the IDE components that inquiry a device fields when the java code is bult using the IDE (e.g. Netbeans)

**Comment by zack-vii** [comment]
But Device beans would only need the wave display part right.. i was thinking wavedisplay could be ignorant of mdsplus. and just knows a simple data feed read interface like dataxy. one could embed it in jtraverser/2 without the dataprovider stuff or the gui. thing is now its extra complicated do work with as settings and properties are scattered throughout the layers. at some point i would like to merge it with the jScopeW7X that i pitched in the beginning but was rejected because i had eclipses autoformating on. But its good to know that WaveDisplay.jar is not used.

**Comment by GabrieleManduchi** [comment]
You have been confused by the name. DeviceWaveDisplay bean uses class Waveform from jScope. 
WaveDisplay is no more used now.

**Comment by GabrieleManduchi** [comment]
jScope is already split: only MdsDataProvider knows about MDSplus and all the remaining classes are independent from MDSplus stuff. jScope has been used indeed to display data in experiments not using MDSplus at all

**Comment by GabrieleManduchi** [comment]
In principle one may further divide jScope classes in classes providing display (Waveform and MultiWaveform) and the other that assemble them in jScope application, but sincerely I don't see a real need for it.

**Comment by zack-vii** [comment]
Well kind of only though because you cannot remove MDSDataProvider form jScope as the dependencies from statics did not allow it. jScope is pretty modular in terms of class hierarchy making it quite complicated to find which code is actually executed. But then again these classes a not well separated making the most layers not reusable.

Anyway i agree with the low priority.
