### ISSUE TITLE
javamds/mdsobjects.c doAction should reuse core implementation

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#2041]
the current version reimplement it on low level while lacking functionality. instread it should use highlevel entries. e.g. reenacting what this tdi would do.
```tdi
execute(Using(tcl('do '//getnci($,'path')),,$,$), nid, shot, tree)
```

possibly with ctx this could be gathered in on api call.

**Comment by GabrieleManduchi** [comment]
ok, makes sense

**Comment by zack-vii** [comment]
In fact TdiDoTask(&niddsc, &retstatus_d MDS_END_ARG) does what you would want

 _TdiDoTask(ctx, &niddsc, &retstatus_d MDS_END_ARG) i will fiddle it in real quick
