### ISSUE TITLE
python TreeNode.doMethod is broken in current alpha (pyhton 2.7)

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#2050]
In current alpha method doMethod(method) is broken for TreeNode objects

>>>n.t.getNode('snapshots')
>>>n.doMethod('store')
error doing 20606(Int32).store

(using mdstcl it works)

What happens (at least in python 2.7) is that PyDoMethod receives an Int32, not a TreeNode instance

**Comment by GabrieleManduchi** [comment]
If line 42 device = n.conglomerate_nids[0] of pyDoMethod  is replaced by
device = TreeNode(n) 
it works whan called directly by pthon, but if it is in turn in a python program, another error is issued, I think because the tree reference is lost

**Comment by GabrieleManduchi** [comment]
It seems like it is expecring a device instance,....too intricated, I leave it to you........

**Comment by GabrieleManduchi** [comment]
Anyway this is not a  critical issue: in python device methods can be  called directly from the device instance.

In any case doMethod() is somewhat misleading: if we provide it, it must work, otherwise it is better to remove it.

**Comment by zack-vii** [comment]
hmm.. i think  n.conglomerate_nids[0] used to return a TreeNode .. it should probably be replaced with n.head.. i will check it out

**Comment by zack-vii** [comment]
WEll do method is supposed to work on all devices not just pydevices. it is invoking _TreeDoMethodA which accepts nid numbers can you please provide the complete the sample code ? what is n.

hmm wait I see the problem now. originally conglomerate_nids returned internally an array of int. no its an Int32Array. so it requires a cast to int. just using TreeNode(n) would work on pyhtondevices with overhead but no necessary on non python devices

**Comment by zack-vii** [comment]
Nevermid TreeShr.TreeDoMethod required DTYPE_NID as first arg, not INT32
