### ISSUE TITLE
jScope broken

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#2052]
Timo,
   I pulled the current alpha, but jScope is in an inconsistent state. Indeed jScope only starts with default configuration, when loading ay different data providers it breaks. Several classes make reference to package mds.connection that does not exists. Moreover the distinction between packages (mds.jscope, mds.Wavedisplay) does not make sense in my view. 

If we really want to separate packages, what makes sense in my view is to separate data providers from the remaining jScope classes. But this is no high priority in my view

**Comment by zack-vii** [comment]
any or just thevStreaming provider. i moved it from mdsobjects to jscope so the MDSplus. prefix must be dropped.

**Comment by zack-vii** [comment]
i agree though. mds.provider for all providers.
i wilk start working on a fix first

**Comment by GabrieleManduchi** [comment]
Having moved MdsConnection ti mdsobjects has made jScope dependent on mdsobjects. We do not want this because jScope is a pure Java application (no jni) and it must live alone (so that jScope can be imported in non mdsplus system)

**Comment by GabrieleManduchi** [comment]
Or in any case on systems that do not have MDSplus installed

**Comment by GabrieleManduchi** [comment]
jScope original classes are now scattered around. In my view this makes everything more complicated and it breaks the requirement for jScope to be self-consistent

**Comment by GabrieleManduchi** [comment]
Ok, I made jScope work again. Correct line 43 in MdsConnectionLocal  into

if(p!= null)   p.destroy

But I do not agree on the current class organization (so I did not report a PR yet)

**Comment by GabrieleManduchi** [comment]
On a different side.....jdispacher seems to be all ok, and my sample application worked perfectly :-)

In any case I will need more thorough tests, but I think I must wait a while until I can do it (experiment running for few months before a longer shutdown)

**Comment by zack-vii** [comment]
I can add in mds.connection package in jscope making it self sustained. ist just a link into mdsobjects. and a lin in makefile.
