### ISSUE TITLE
Manage server list in jScope

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2077]
After changing the server list in jScope it does not get written anywhere.  How do you interactively edit the list.

I think we have a way to specify the server on the command line, but it is WINDOZ - so scope comes from menu. 

It would be great to have a 'default server' or a way to make an icon for the users which was just 'right'

**Comment by GabrieleManduchi** [comment]
The Data Server can be specified in jScope command line. In ths case it takes precedence ove te server specified either on menu or in the used confguration file.

`jScope -l`    start jScope connected locally (it spawns a mdsip subprocess and communicates via pipes with it)
`jScope -s <mdsip server[:port]>`  start jScope connected to the specified server
`jScope -ssh <user@mdsip server>` start jScope connected via ssh to the specified server. Password is requested upon first data retrieval
