### ISSUE TITLE
libreadline not installed within dependencies in both redhat and ubuntu

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2082]
Hi

In both Ubuntu and redhat based distributions, when I install mdsplus with apt or dnf, I also need to manually install libreadline (readline-devel in redhat, libreadline-dev in ubuntu). Is there a specific reason this package can't be part of dependencies?

Thanks
Cenk

**Comment by zack-vii** [comment]
for debian there is a problem as mdsplus is only built for wheeze and debian9. adding readline as a general dependency would tie down the version. and mdsplus wont install on jessie or buster.

i think we currently have one shared packaging definition. one would need to introduce a os depoendency. or maybe one could loosely add a dependency. it would install readline but wont fail if it cant. or so it would not tie down the version.

**Comment by zack-vii** [comment]
depends now on readline except debian
