### ISSUE TITLE
getShape is slow

### ISSUE THREAD

**Issue by lamorton** [MDSplus/mdsplus#2087]
I've found that getShape takes about 110 ms (about the same amount of time as actually fetching the data), whereas other operations like getChildren take 0.1 ms (I'm using python thick client, over the net).  It seems to go slower for larger arrays.  

Ordinarily, this wouldn't matter, but [MDSmonkey](https://github.com/lamorton/MDSmonkey) uses 'getShape' to (A) determine whether a node actually has data (B) provide the shape information for browsing purposes. So, when traversing the tree, this call gets applied to every data node -- which bogs down. 

It would be nice if getShape could be sped up, but in any event, is there a better way to determine if a node has data?

**Comment by zack-vii** [comment]
Hi there. You can use the length nci (python node.length) instead. since getShape is a Data method it actually has to read the data which takes time. empty nodes have length=0. I am not certain but in case segmented nodes have a length=0 as well you can do getNumSegments on those.

**Comment by zack-vii** [comment]
well on B: you are can wrap a thin client request where the data still need to be read but is not transfered to the client.
```python
con = MDSplus.Connection(server_that_holds_the_tree)
con.mdsOpen(tree.tree, tree.shot)
con.get('SHAPE(%s)' % node.fullpath)
```
(out of my head and not tested)

edit: 
that said it may be worth implementing your traverser in thin client.

**Comment by lamorton** [comment]
Thanks Timo, it seems like `length` is about 4-5x faster than shape.  As it happens, `shape` and `length` are about the same speed (~20ms) on the thin client. So for now, I am just switching my traverser to use `length`, but I might wind up rebasing it on the thin client. I just don't like having to muck with the TDI expressions inside Python, which is why I went with the thick client.

**Comment by lamorton** [comment]
PS: would it be possible to do some hack where I look at the pointer to the current node vs the next one and estimate the length based on pointer arithmetic?

**Comment by zack-vii** [comment]
I dont think the hack would be possible as the order of the data is inordered in referenzevto the nodes. the datafile is filled as you write. so the pointers into the file are scattered. thats why we stored the byte length as a hint in the charateristics file. length is not necessarely accurate as it caps at 2GB and does not resolve segmented nodes. the vatue is writte on write and covers the size of the fully serialized descriptor.
please check java's jtraverser2/mdsplus-api sources for implementation hints with tdiexpressions.

What is the purpose of the traverser?
- is it possible to add code to the tree hosting server.

whats the typical size of the datafile?
- would it make sence to cache the tree locally? can be done with by prefixing the treepath and a tree.createPulse(new_tmp_number)

Is it loading all nodes at once or level by level?
- could it not read the btop level first and fetch the rest in a background thread with a priority fifo.

Do you really need the shape for all nodes? 
- it could be cached as xnci attribute for large records.

**Comment by lamorton** [comment]
The purpose of the traverser is to explore an unfamiliar MDSplus tree, in particular to find out where the data nodes are. I don't want the tree to be cluttered with nodes that are empty, so I need a way to test whether data is stored at the nodes. The scenario is that I'm just starting out to analyze data from a new device, so I don't have a way to add code to the server necessarily, I don't know how big the datafiles will be, and I need to look at all the nodes. I don't necessarily need the shape, I just want to know if the data exists.

I've set the traverser up to do a depth-first search. The idea is that if it goes down a branch and finds that there are no nodes with data that are descendants (of any order), then the branch is not returned -- it is pruned, basically, before the tree object is returned from the call to the constructor.

**Comment by zack-vii** [comment]
you could try a simple tdi script that combines 
```tdi
_nodes = TreeGetNodeWild("***"); # returns a list of all nodes
_return = [GetNci(_nodes, "NID_NUMBER"), GetNci(_nodes, "LENGTH")]
```
and make a thin client request.
```python
con = MDSplus.Connection(server)
con.openTree(tree.tree, tree.shot)
nid, length = con.get((
    '_=TreeFindNodeWild("***");'
    '[GETNCI(_,"NID_NUMBER"),GETNCI(_,"LENGTH")]'
)).data().tolist()
```
You can also pull other information this way but in case the data types differ other than here (L vs LU) you need to wrap the request in a serializeout and list
```python
nid, length, path = [a.tolist() for a in con.get((
    'serializeout(`(_=TreeFindNodeWild("***");List(,'
    'GETNCI(_,"NID_NUMBER"),'
    'GETNCI(_,"LENGTH"),'
    'GETNCI(_,"PATH")'
    ');))')).deserialize().data()]

```

**Comment by lamorton** [comment]
Wow, that's awesome, thank you. ~17 seconds versus 70 seconds for my thick-client version.  Now I just need to parse the list into a tree.
