### ISSUE TITLE
How does MDSPlus manage hundreds of thousands of data files

### ISSUE THREAD

**Issue by Merlencer** [MDSplus/mdsplus#2093]
At present, I have built a new tree (actually a folder) named my_ tree。 Since we have done more than 10000 experiments, there are tens of thousands of files in this folder. Obviously, these files are not easy to manage. How can we manage these tens of thousands of files (and even more in the future) more effectively, and also through my_ Trees access the data in these files.

**Comment by zack-vii** [comment]
MDSplus looks up tree files through the file name and path. so the number of files is only a problem ist the filesystem makes it a problem. you can reduce the number of files per folder by sectioning the tree_path by shot number using the ~a,.. wild cards as described here:
https://www.mdsplus.org/index.php?title=Documentation:TreeAccess
