### ISSUE TITLE
Windows installer deletes installation directory which may not be private!

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2105]
A user encountered the following (and I verified it)

When MDSplus is installed in a location other than the default location, it puts all of its files wherever the user says to put them.  On uninstallation, the uninstaller, deletes this directory which may contain the users files.  

For example the user installed MDSplus in C:\Users\<username> uninstalling MDSplus deleted all of their files. 

It seems like we have 2 choices here:

- Not delete the install directory - last item in the uninstaller
  - this has the problem of leaving the MDSplus directory there if the default location is used
- Always add MDSplus to the end of the install path, so this user would have gotten
   - C:\Users\<username>\MDSplus. which would have been OK to remove
- Prompt the user about the removal of the directory

The safest thing to do is to not remove the dir.

**Comment by zack-vii** [comment]
well if we dont remove the folder uninstall does not uninstall much as i think it only deletes file by file the stuff it put in system folders. so a warning if target is not empty should do the trick. that us common under windows installers and should prevent from accidentally choosing an existing path. i could fiddle with the installer generator and check what plugins are already available.

**Comment by zack-vii** [comment]
another thing worth looking into usbif we can teach tge installer to dynamically keep track of all diles created during install. then during uninstall we only wipe the *.pyc files and \_\_pycache\_\_ folder an do rmdir on the folders which will fail if not empty. seems the safest but probably most complex solution

**Comment by joshStillerman** [comment]
I think the first suggestion is the way to go.  If we change the removal of the directory to be non recursive, it will not remove it if there is stuff in it.  This is safe, and good enough.  Do you (Timo) want to work on this? or should I?
-Josh
