### ISSUE TITLE
jScope on Windows can't find mdsip-client-local.bat

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2109]
When opening jScope on Windows (fresh install of latest stable Windows version) I get a pop-up window with:

"Could not get IO for local java.io.IOException: Cannot run program "mdsip-client-local.bat": CreateProcess error=2, The system cannot find the file specified"

The script mdsip-client-local.bat is in C:\Windows\System32 which seems to be in my Windows path env var.

Any suggestions?

Thanks,
Brian

**Comment by mwinkel-dev** [comment]
Still need to test the “stable” release, however the problem does not exist in the “alpha” release.

With “alpha” installed, did the following steps:
- opened a Command window and entered jScope at the prompt, whereupon jScope displayed
- from the jScope menu, selected Network->Servers->Local
- in the Shot field entered a shot number and then clicked the adjacent Apply button
- confirmed that it did find the \Windows\System32\mdsip-client-local.bat file and run it
- no errors were displayed

For the “alpha” experiment, used this configuration.
MDSplus package = MDSplus-alpha-7.139-28.exe (created 1-May-2023)
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎1/‎13/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by mwinkel-dev** [comment]
Tested with the "stable" branch, and it also worked fine.
MDSplus package = MDSplus-7.132.0.exe (created 16-Dec-2022)

**Comment by joshStillerman** [comment]
Brian -
  I wonder if the context that you are running jScope in has the PATH set up.  Did you click on the ICON or type jScope in a terminal ?

**Comment by nelson-zapenergy** [comment]
Hi Josh,

This is an error from almost 2 years ago, which I no longer get (I think an MDSplus update fixed it; can't remember).  
For the record I usually start jScope from the Window "tray".

Thanks,
Brian

**Comment by joshStillerman** [comment]
Brian -

   Sorry for the *delayed* response!  We are just cleaning up old 
issues.  I hope things are going well for you.

**Comment by nelson-zapenergy** [comment]
No worries, going well thanks for all you do!

**Comment by mwinkel-dev** [comment]
Closing this issue as per Josh (and the above conversation with Brian).
