### ISSUE TITLE
Python conn.disconnect

### ISSUE THREAD

**Issue by pfbuxton** [MDSplus/mdsplus#2113]
Hi,

It appears to me that Python's MDSplus disconnect doesn't actually do anything? Is this a bug??

Here is an example - I have conn.closeAllTrees() which does indeed disconnect from all trees, but conn.disconnect() doesn't seem to work, in the example you can see after the disconnect I can still open and read from trees:
```python
MDS_Ip_address = 'IP_ADDRESS:PORT'
shot_no = 123
place_to_read = 'some data to read'
tree = 'a tree'

from MDSplus import Connection
conn = Connection(MDS_Ip_address)
conn.openTree(tree, shot_no)
data1 = conn.get(place_to_read)
print(data1)
conn.closeAllTrees() # close all trees
conn.disconnect # disconnect from MDSplus
# this should not work as we should be disconnected from MDSplus ??
conn.openTree(tree, shot_no)
data2 = conn.get(place_to_read)
print(data2)
```

I have tried this with the most recent stable release of MDSplus

**Comment by tfredian** [comment]
I'm surprised if just specifying

conn.disconnect

doesn't produce an error. Try

conn.disconnect()

**Comment by zack-vii** [comment]
No that ok conn.disconnect is valid syntax and will return the function pointer. But you are right this wont disconnect as you need to call that pointer as Tom suggested conn.disconnect()

**Comment by pfbuxton** [comment]
Hi @zack-vii @tfredian,

Unfortunately the same result occurs if you do `conn.disconnect()` you still don't disconnect.

Thanks,
Peter

**Comment by zack-vii** [comment]
Hmm what version are you on.
I tried on on recent alpha and
tty 1
```sh
$ echo '*' >/tmp/mdsip.hosts
$ mdsip -m -p 10000 -h /tmp/mdsip.hosts
Mon Sep  7 15:09:37 2020 (4) (pid 6368) Connection received from user@localhost [127.0.0.1]
Connected: user
Mon Sep  7 15:09:44 2020 (4) (pid 6368) Connection disconnected from user@localhost [127.0.0.1]
```
tty2
```python
$ python
>>> import MDSplus
>>> c = MDSplus.Connection('localhost:10000')
>>> c.disconnect()
```

**Comment by zack-vii** [comment]
Oh you are wondering wy you can still get.. well get checks if you are connected and reconnects if the connection has been dropped by server or client

**Comment by pfbuxton** [comment]
Thank you very much for the clarification!
