### ISSUE TITLE
How to implement the makesegment method in python with TDI

### ISSUE THREAD

**Issue by Merlencer** [MDSplus/mdsplus#2123]
How to implement the makesegment method in python with TDI

**Comment by zack-vii** [comment]
well at first, why not using the python methods. is you input not python.. are you on thin client?
fir the sake of it you can open a 
```python
tree = MDSplusTree(expt, shot)
# tree.DATA_NODE.makeSegment(begin, end, dim, data)
tree.tdiExecute('TreeMakeSegment(DATA_NODE,$,$,$,$)', begin, end, dim, data)
```
in principle. this is from memory the tdi method may be different.

**Comment by Merlencer** [comment]
Actually, I want to use matlab to upload data.I don't know if there is a method like makesegment in MATLAB



在 2020-09-27 14:00:52，"Timo Schroeder" <notifications@github.com> 写道：

well at first, why not using the python methods. is you input not python.. are you on thin client?
fir the sake of it either ooen a

tree=MDSplusTree(expt, shot)
# tree.DATA_NODE.makeSegment(begin, end, dim, data)tree.tdiExecute('TreeMakeSegment(DATA_NODE,$,$,$,$)', begin, end, dim, data)

in principle. this is from memory the tdi method may be different.

**Comment by zack-vii** [comment]
if you use the matlab-python bridge the pythonic way.. as in the commented line should work too. the java-bridge i am not sure but it should have a way to use tdi in the same way, that 's right.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
