### ISSUE TITLE
extra_path in distutils is deprecated in 3.6 and gone in 3.8

### ISSUE THREAD

**Issue by jmilhone** [MDSplus/mdsplus#2124]
I believe it is not possible to install MDSplus for python 3.8 because extra_path is used in setup.py.

In Issue 27919 for python (https://bugs.python.org/issue27919), extra_path for disutils was deprecated for python 3.6. 

To verify the issue was not on my end, I was able to successfully install MDSplus on a brand new python 3.7 environment.

**Comment by zack-vii** [comment]
well there is always the PYTHONPATH way as a workaround, which has become much more convenient as the folder python in the installation folder is set up in such a way =, it can be simply added to PYTHONPATH and it should work without install.

**Comment by jmilhone** [comment]
I would generally agree that one can do that as a workaround. But ultimately, that's really not a good solution. It has unintended consequences when importing other modules. Here is a conflict with ConfigObj while having MDSplus added to PYTHONPATH:

(py37) C:\Users\WHAMuser\piscope>ipython
Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import configobj
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ca3815d7213d> in <module>
----> 1 import configobj

~\.conda\envs\py37\lib\site-packages\configobj.py in <module>
     21
     22 import six
---> 23 from _version import __version__
     24
     25 # imported lazily to avoid startup performance hit if it isn't used

ImportError: cannot import name '__version__' from '_version' (C:\Users\WHAMuser\Documents\MDSplus\_version.py)

In [2]:

**Comment by zack-vii** [comment]
? can you post your PYTHONPATH and the content of MDSplus_version.py and the content of  "%MDSPLUS_DIR%\python" please.
```
echo %PYTHONPATH%
type C:\Users\WHAMuser\Documents\MDSplus_version.py
dir "%MDSPLUS_DIR%\python"
```

PYTHONPATH should contain "%MDSPLUS_DIR%\python" not "%MDSPLUS_DIR%\python\MDSplus" and the folder "%MDSPLUS_DIR%\python" should not contain _version.py .. i don't see why other packages would conflict.

**Comment by jmilhone** [comment]
Ok, I see this issue now. I pointed the PYTHONPATH variable into %MDSPLUS_DIR%\python\MDSplus instead of just %MDSPLUS_DIR%\python.

Everything seems to be working now with python 3.8.

C:\Users\WHAMuser>ipython
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import MDSplus
C:\Program Files\MDSplus\python\MDSplus\descriptor.py:122: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not '_structure' and name in dict(self._structure._fields_):
C:\Program Files\MDSplus\python\MDSplus\descriptor.py:126: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if name is not '_structure' and name in dict(self._structure._fields_):

In [2]: import configobj

**Comment by zack-vii** [comment]
Good: Ahh and the "is not" issue is was introduced by python 3.8 then.. well it has been fixed recently in alpha. #2127

**Comment by zack-vii** [comment]
we should get rid of setup.py to avoid confusion. the PYTHONPATH is a transparent and most compatible method installing the required numpy is trivial. setup.py has a hard time to comply with the range of python versions we support and poorly maintained.

**Comment by zack-vii** [comment]
fixed
