### ISSUE TITLE
Python source structure is non-standard: pip installation issues

### ISSUE THREAD

**Issue by amicitas** [MDSplus/mdsplus#2142]
The current organization of the python source is non-standard, and does not allow installation using `pip`.

### Issue

My expectation is that I would be able to use:

    pip install -e /usr/local/mdsplus/python

Or for a static installation:

    pip install /usr/local/mdsplus/python

It is also my expectation is that it would be possible to use the standard `distutils` commands to create source packages and then use these with `pip` for installation.

    python setup.py sdist
    pip install dist/MDSplus-7.114.0.tar.gz

Currently the only way to install MDSplus from source (I am aware of) is is to use: `python setup.py install`. Which bypasses all of the `pip` package handling.

Note that under the old `mdsobjects` source structure, standard packaging and `pip` could be used.  This issue is unique to the new source structure.

### Possible Fix

This can likely be fixed by moving `setup.py` to the parent directory `mdsplus/python`, and adjusting the directory listing in the script.

**Comment by amicitas** [comment]
A related issues is that `setup.py` explicitly uses `distutils` instead of `setuptools`. The current python standard is `setuptools` and should be used now instead.

**Comment by zack-vii** [comment]
my suggestion would be to remove setup.py entirely and we eradicate mdsplus from pip.
The best way to transparently install mdsplus for python without unintentionally breaking the linkage to apt/yum and co is to add /usr/local/mdsplus/python to PYTHONPATH.
