### ISSUE TITLE
something has happened to the packaging / testing

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2157]
I am getting very frustrated trying to fix the packaging / testing of MDSplus.  Any and all help would be appreciated.  The current issue is that the kernel package tests tdi, and tdi tests devices and the devices use the module queue, which is not part of python on the test environment.  See:
http://jenkins2.mdsplus.org/job/fc17/lastBuild/artifact/tests/64/tditest/testing/test-dev-py.log
What is weird is that the devices have used queue for a long time.  Why does this just come up now?

**Comment by zack-vii** [comment]
this is because none is listening to me when i say please follow the pydevice rule.. if you import queue without version sensitivity it will fail on python2 where the package is called Queue
```
import sys
if sys.version_info < (3,):
    import Queue as queue
else:
    import queue
```
there are many more known issues.
find more here:
https://www.mdsplus.org/index.php/Pydevice_dev

**Comment by joshStillerman** [comment]
Great  page - you should have told everyone about it!

Looking through my copy of the source I find no instances of importing queue without checking:
for i in `find . -name '*.py'`; do echo $i; grep -i queue $i | grep import; done 

Suggestions ?

**Comment by joshStillerman** [comment]
Nevermind -
  That was a PR for code that is not committed / merged.  I am still having trouble with the release jobs, but have to start a new investigation of that.
