### ISSUE TITLE
Image display problem

### ISSUE THREAD

**Issue by fun-gui** [MDSplus/mdsplus#2192]
Hi everyone.
We have several devices which write images into our MDS server, logged with each shot. 
We view these images using jScope. Every version of MDSplus past 7.49 causes the images to be displayed in an extensively washed out manner, whereas it previously was displayed with correct grey-scaling.

I've tried poking around through commits and changelogs, but can't track down what might have changed that causes the images to basically have become solid black or white. None of the server versions or device configurations have changed, and viewing the same image data in 7.49 clients works fine.

Let me know what information I can provide to help narrow this down, it's a pretty annoying bug for us. Thank you!

**Comment by fun-gui** [comment]
Here's a v7.49 image:
![image](https://user-images.githubusercontent.com/76135014/102522911-bb0f5080-404b-11eb-8608-abfa99a9e21d.png)

and here's the same image/shot from any version onwards:
![image](https://user-images.githubusercontent.com/76135014/102523460-6a4c2780-404c-11eb-8809-0a2ecf1a99cc.png)

**Comment by zack-vii** [comment]
might just be a broken bit filter.. might just be default vatue. can you share the kind (byte, short, long, float, ..) of the data?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by fun-gui** [comment]
The data is stored in bytes. Where would I find the bit filter info? Thanks zack-vii

**Comment by zack-vii** [comment]
I think i found the issue.. the classification may have changed resulting in Byte kind date to be interpreted as float. unfortunately the default values for paletteMin and paletteMax is 0.0 and 0.0 (? not 1.0) which renders you image black and white. better would be -128.0 and 127.0 to comply whit the java representation of a byte type. However this would overrun unsigned byte images. a dirty workaround would by to subtract 128 from the date. Given its interpreted as float anyway, best would be to divide by 255.0 but float seems to be broken as well.

my example


```jscp

Scope.geometry: 1238x550+100+100
Scope.update.disable: false
Scope.update.disable_when_icon: true
Scope.font: java.awt.Font[family=Dialog,name=Dialog,style=plain,size=12]


Scope.color_0: Black,java.awt.Color[r=0,g=0,b=0]
Scope.color_1: Blue,java.awt.Color[r=0,g=0,b=255]
Scope.color_2: Cyan,java.awt.Color[r=0,g=255,b=255]
Scope.color_3: Green,java.awt.Color[r=0,g=255,b=0]
Scope.color_4: Magenta,java.awt.Color[r=255,g=0,b=255]
Scope.color_5: Orange,java.awt.Color[r=255,g=200,b=0]
Scope.color_6: Pink,java.awt.Color[r=255,g=175,b=175]
Scope.color_7: Red,java.awt.Color[r=255,g=0,b=0]
Scope.color_8: Yellow,java.awt.Color[r=255,g=255,b=0]

Scope.data_server_name: Local
Scope.data_server_class: MdsDataProviderLocal
Scope.reversed: false

Scope.global_1_1.horizontal_offset: 0
Scope.global_1_1.vertical_offset: 0

Scope.columns: 3
Scope.rows_in_column_1: 1


Scope.plot_1_1.height: 416
Scope.plot_1_1.grid_mode: 0
Scope.plot_1_1.is_image: true
Scope.plot_1_1.keep_ratio: true
Scope.plot_1_1.horizontal_flip: false
Scope.plot_1_1.vertical_flip: false
Scope.plot_1_1.palette: B-W LINEAR
Scope.plot_1_1.bitShift: 0
Scope.plot_1_1.bitClip: false
Scope.plot_1_1.paletteMax: 1.0
Scope.plot_1_1.paletteMin: 0.0
Scope.plot_1_1.num_shot: 0
Scope.plot_1_1.num_expr: 1
Scope.plot_1_1.continuous_update: 0
Scope.plot_1_1.global_defaults: 212865
Scope.plot_1_1.y_expr_1: BYTE_UNSIGNED([[[0, 64],[128, 192]]])
Scope.rows_in_column_2: 1


Scope.plot_1_2.height: 416
Scope.plot_1_2.grid_mode: 0
Scope.plot_1_2.is_image: true
Scope.plot_1_2.keep_ratio: true
Scope.plot_1_2.horizontal_flip: false
Scope.plot_1_2.vertical_flip: false
Scope.plot_1_2.palette: B-W LINEAR
Scope.plot_1_2.bitShift: 0
Scope.plot_1_2.bitClip: false
Scope.plot_1_2.paletteMax: 127.0
Scope.plot_1_2.paletteMin: -128.0
Scope.plot_1_2.num_shot: 0
Scope.plot_1_2.num_expr: 1
Scope.plot_1_2.continuous_update: 0
Scope.plot_1_2.global_defaults: 212865
Scope.plot_1_2.y_expr_1: BYTE_UNSIGNED([[[0, 64],[128, 192]]])-128BU
Scope.rows_in_column_3: 1


Scope.plot_1_3.height: 416
Scope.plot_1_3.grid_mode: 0
Scope.plot_1_3.is_image: true
Scope.plot_1_3.keep_ratio: true
Scope.plot_1_3.horizontal_flip: false
Scope.plot_1_3.vertical_flip: false
Scope.plot_1_3.palette: B-W LINEAR
Scope.plot_1_3.bitShift: 0
Scope.plot_1_3.bitClip: false
Scope.plot_1_3.paletteMax: 1.0
Scope.plot_1_3.paletteMin: 0.0
Scope.plot_1_3.num_shot: 0
Scope.plot_1_3.num_expr: 1
Scope.plot_1_3.continuous_update: 0
Scope.plot_1_3.global_defaults: 212865
Scope.plot_1_3.y_expr_1: BYTE_UNSIGNED([[[0, 64],[128, 192]]])/255.

Scope.vpane_1: 333
Scope.vpane_2: 666

```



For a Fix:

I think best would be to tread byte and unsigned byte same as short with a default bitshift that would fit the byte data range... might be bitshift 8?

Float should by default either range from 0.0 to 1.0, or auto ( min to max of image )..


i attached the sample configuration.. plot 3 and 2 should display the same but dont.. float seems to do strange scaling if investigated with Point, non-zero values are of the order of 1e9.

bitshift would show in the context menu of the image selecting colormap

**Comment by GabrieleManduchi** [comment]
Dear fun-gui, have you changed the palette (popup menu color palette )?
What are the values you see printed in the low left corner of jScope when you move the cursor over the image in Point mode? 
Do they correspond to the values you expect? If yes, you should set min and max in the color palette corresponding to the minimum and maximum printed values. Afterwards you can save the jScope configuration.

**Comment by GabrieleManduchi** [comment]
Better, enable popup option ShowProfileDialog in order to see what are the maximum and minimum pixel value

**Comment by GabrieleManduchi** [comment]
hmm, looking at some examples, it seems, as Timo suggested an issue related to signed/unsigned bytes. I shall look into jScope in order to figure out this

**Comment by GabrieleManduchi** [comment]
Ok, I have found the problem related to byte images. I have a local fix, I will check it a bit more next Monday and then I  will report in alpha.

**Comment by GabrieleManduchi** [comment]
The fix has been reported in alpha. In a day the rpms shall be available.
Let me know if your problem is now solved.

**Comment by fun-gui** [comment]
@GabrieleManduchi much appreciated, I'll check it out when a Windows alpha becomes available.

**Comment by zack-vii** [comment]
seems to be resolved
