### ISSUE TITLE
make each platform build use unique port

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2194]
Some of the tests in the build process use events.  With the new builder, multiple jobs have started using the same events on the same ports as each other.

Adding: 
```
export mdsevent_port=`expr 4000 + $EXECUTOR_NUMBER`
```
to the scripts seems to do the trick.
I have done. FC30, FC29, FC28, FC27
and I will do the rest

**Comment by joshStillerman** [comment]
There is a better solution.  Add
`--eventport=$((4100+$EXECUTOR_NUMBER))` to the build script.

I have done through fc23 starting at the bottom of the jenkins display

**Comment by zack-vii** [comment]
maybe it is also possible to configure docker such that the builds are isolated., no?

**Comment by zack-vii** [comment]
I added the docker  network feature so each worker on builder will use its private network bridge. thus the should not be any more cross communication between the jobs. this should improve the quality of the tests. --network=none did not seem to work as UDPEvents required a valid network interface
