### ISSUE TITLE
makeSegmentResampled from python

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2197]
The current code for makeSegmentResampled and makeSegmentMinMax are in the cpp mdsobjects code. All of the current python code is implemented by calls into treeshr.

We need a way to call makeSegmentResampled from python.
We could write a C glue and call the C from python (not optimal)
We could move the C++ code for these functions to treeshr and then call them from C++ for the C++ API
  - Why does the C++ objects make its own entry points for all of the treeshr entry points it needs.  Wouldn't it be cleaner to only do this if there are C++ ish things it needs to do?

**Comment by GabrieleManduchi** [comment]
I think that the most effective solution is to move the C++ code for MakeSegmentResampled() and MakeSegmentMinMax() (but there are also beginSegment() and putSegment Rezsample and MinMax version) from C++ implementation to treeshr.
I did it the first time in tyhe C++ mdsobjects because it was at that time still experimental, but now it makes sense to move to treeshr.  Moreover, C++ interfaces from python can be tricky die to mangling.  I would also consider implementing the streaming stuff in python: now there only  sendStream but a class for receiving streams in python is missing.

**Comment by joshStillerman** [comment]
So the question is: 'who is going to take this on?'  And how big a job is it ?  At first glance it does not look too bad.

**Comment by GabrieleManduchi** [comment]
I can get this job, as I did it in C++. Next week I shall be working a couple of days, and things should be quiet. It should be not too complicated.

**Comment by zack-vii** [comment]
I am not sure but i think i implemented that already.. for the wsgi code.

**Comment by zack-vii** [comment]
it used the default resampling mode atm but Data.getXYSignal() may be what you are looking for..

**Comment by zack-vii** [comment]
ah no forget that.. looks like this is to store the resampling xnci to the node when writing data?

**Comment by zack-vii** [comment]
I think we should just add a treeshr method TreeSetResampleMode(NID nid, descriptor mode) 

Where mode is either a string naming the method (just like the environment var) or and integer corresponding to the enum used in xtreeshr or $Missing to disable resample and clear the xnci.

**Comment by joshStillerman** [comment]
Timo -

   I think we should have a discussion about this.  Are you free to 
zoom?  Wednesday morning (US-East) ?  I can set a meeting.

-Josh

**Comment by GabrieleManduchi** [comment]
I think Timo refers to  XTreeDefaultResample() that looks for an env var to decide what kind of resampling to carry out. Here, we refer to writing  a resampled version of the segment in addition to the original one, that is used afterwards by TreeDefalutResample()

Anyway, I am working on it, and I think to have it done by the end of the week.

**Comment by zack-vii** [comment]
We can do a a zoom meeting. Wednesday works for me. just let me know when. 

I i understand it correctly MakeSegmentResampled would set a XNCI attribute to the node that overrides the default behavior. to be inline with other methods that do similar things e.g. TreeSetSegementScale we should add a method that follows this structure. but we will see on Wednesday.

**Comment by GabrieleManduchi** [comment]
MakeSegmentResampled does not only set the xnci required attributes, bur actually writes a resampled version of the segment in a different node whose nid is passed as argument. This is currently implemented in the c++ mdsobjects, but Josh suggested to move to treeshr, and indeed I am working on it.

**Comment by santorofer** [comment]
Gabriele, just so you know, I have the following PR that implements/uses your work on this issue:

[https://github.com/MDSplus/mdsplus/pull/2234](url)

I used in this case:

makeSegmentResampled()

It's working very well!
