### ISSUE TITLE
use standard formatting for all C and C++ code

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2218]
Use `clang-format` to format all c, cpp, and .h files in MDSplus source so that we have uniform coding standards.

This should also be done for python, xml and other things

We should include IDE setup files to help keep the code this way.

**Comment by zack-vii** [comment]
we added `./clang-format.sh` which will run on teh whole repo folder 
or `./clang-format.sh path/to/dir` which would only format files in path/to/dir.

clang-format is applied on all *.c, *.cpp, *.h, and *.hpp files.
