### ISSUE TITLE
Use cross compiler for raspberry pi

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2219]
The raspberry pi build is very slow.  We have a docker image that almost works to cross compile for raspberry pi.  The following command:
```
deploy/build.sh --disable-java --os=raspberrypi --release 
```
complains with 
```
javac: invalid source release: 8
```
we could either fix this in the raspberrypi-32 docker image or figure out how to have it include the jars built elsewhere

**Comment by zack-vii** [comment]
builds now on builder 01
