### ISSUE TITLE
treeopen() in the same expression line does not work anymore

### ISSUE THREAD

**Issue by GabrieleManduchi** [MDSplus/mdsplus#2220]
The evaluation of an expression of the form 

treeopen(<experiment>, <shot>); <node content>

fails, while evaluating first treeopen(<experiment>, <shot>) and then <node content> works.

You can easily replicate the issue by creating a tree TEST shot -1 containing node NUM  with some data. Then

TDIC>treeopen('TEST', -1); NUM

fails while 

TDIC>treeopen('TEST',-1)
TDIC>NUM

works

**Comment by zack-vii** [comment]
Hm this might be due to the way tdi compile works. it may interpret the full expression first not recognizing NUM as a PATH that way. not sure if this can be fixed easily. This may have been the behavour since ever. But i may look into it in a few days.

**Comment by tfredian** [comment]
Weird. I responded to this yesterday but it didn't get sent. Yes, compile will not succeed with no tree open. If you need it you can do:

Treeopen("tree",-1);build_path("num")

**Comment by GabrieleManduchi** [comment]
Maybe we never met it before.....but it seems unlikely to me........

**Comment by zack-vii** [comment]
because it is related: in some case one may want to consider using
```tdi
USING(NUM, 0, -1, 'TEST')
```
instead which receives a special treatment during compile ensuring NUM is compiled in the context of the open tree
