### ISSUE TITLE
where are the timeouts for the tests set ?

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2221]
While working on PR to format the C code I ran into:

/home/jas/mdsplus/mdsobjects/cpp/testing/MdsTreeSegments.cpp:278:E:makeSegment:test_main:0: (after this point) Test timeout expired

when testing 32 bit.

2 questions
- where is this timeout set (I could not find it)
- Why would it all of a sudden be slower ?
-

**Comment by AndreaRigoni** [comment]
Hi Josh !
 as far as I can see through Tom scripts the smooth approach would be to change the env variable TEST_TIMEUNIT in the number of seconds for the timeout. In case Valgrind is involved the timeout is eventually multiplied by 5.
