### ISSUE TITLE
The current alpha has lost its version information

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2233]
The current alpha - which I think is : `alpha_release-7-125-3` has lost its version information

This has happened before, I don't recall the cause / solution.
```
jas@mfews05:~$ mdstcl
TCL> show version


MDSplus version: 0.0.0
----------------------
  Release:  alpha_release_0.0.0
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release_0.0.0
  Download: https://github.com/MDSplus/mdsplus/archive/alpha_release_0.0.0.tar.gz


TCL> 
```

**Comment by joshStillerman** [comment]
This is the same issue (I think) as the previously resolved:
https://github.com/MDSplus/mdsplus/issues/2079
Though as commented there the ub18 builder does have GIT.

**Comment by zack-vii** [comment]
I think it may be because the version info is generated during configure. We should generate it during bootstrap.. this way it will be uniform across all platforms and easier to debug.

**Comment by zack-vii** [comment]
hm this could have been to many reasons.. but i moved it to "deploy/git_revision.sh" which is called during bootstrap.. all automake vars are now static and can be inspected in the now auto generate "m4/ax_git_revision.m4".
should fix it for both alpha and stable
