### ISSUE TITLE
"nothing provides /usr/bin/python" during mdsplus installation on centos8/centos8stream 

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2236]
Hello,

Summary:  
* I didn't manage to install mdsplus-stable on centos8stream (Results is same in centos8)
* mdsplus-alpha works ok.

I tried to install mdsplus-stable on centos8stream. There seem to be a problem with python. Here's the full steps

```shell
yum install 'dnf-command(config-manager)'
yum config-manager --set-enabled PowerTools
wget https://www.mdsplus.org/dist/rhel8/stable/RPMS/noarch/mdsplus-repo-7.96-13.el8.noarch.rpm
dnf install mdsplus-repo-7.96-13.el8.noarch.rpm 
dnf install mdsplus
```

Error message:
```
Last metadata expiration check: 0:04:54 ago on Fri 19 Feb 2021 10:29:20 AM CET.
Error: 
 Problem: package mdsplus-7.96-13.el8.x86_64 requires mdsplus-python = 7.96-13.el8, but none of the providers can be installed
  - conflicting requests
  - nothing provides /usr/bin/python needed by mdsplus-python-7.96-13.el8.noarch
  - nothing provides numpy needed by mdsplus-python-7.96-13.el8.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

In the system, both python3 and python2 are installed. I tried selecting one or other using following. But result is the same.
```
alternatives --set python /usr/bin/python3
alternatives --set python /usr/bin/python2
```

I can see that there is a symlink in /usr/bin/python/
```
$ which python
/usr/bin/python
```

I can build it myself or use mdsplus-alpha too. I just wanted to report it in case there is a known solution.

**Comment by cenkoloji** [comment]
I digged into it and here's the problem:

* In Centos8 (RHEL8) there is no default python, one can install python2 and/or python3. `/usr/bin/python` is just a symbolic link.
* `mdsplus-python` `mdsplus-kernel_bin` require `/usr/bin/python` and `numpy`
  ```bash
  $ rpm -qpR mdsplus-python-7.96-13.el8.noarch.rpm|grep "python\|numpy"
  /usr/bin/python
  numpy
  ```
* mdsplus-alpha works fine because there is no hard dependency on `/usr/bin/python` and `numpy` (There is dependency for python2-numpy, which exists)
  ```
  $ rpm -qpR mdsplus-alpha-python-7.126-0.el8.noarch.rpm|grep "python\|numpy"
  python2-numpy
  ```

For now I found the following workaround:

* Download 2 packages that have unsatisfied dependencies
  `dnf download mdsplus-python mdsplus-kernel_bin`
* At this point there are 2 options:
  1. Rebuild 2 RPMs using [rpmrebuild](http://rpmrebuild.sourceforge.net/), remove `/usr/bin/python` and `numpy` dependencies, then install them with dnf. 
  2. Install this 2 RPMs with `rpm -i --nodeps`
* After this, one can continue installing whole mdsplus simply by
  `dnf install mdsplus`

**Comment by joshStillerman** [comment]
Reply -
  We have fixed this in the current alpha.  I will check the stable and get back to you.
SORRY for the delay!!
-Josh

**Comment by zack-vii** [comment]
should be fixed,, no?

**Comment by cenkoloji** [comment]
Worked for me with version 7.131-5. 
I see that now python3-numpy is installed as a dependency.

**Comment by FilipJankyTE** [comment]
None of it works for me. I am unable to install mdsplus.

I have dependencies to numpy-python. I don't think, I need python just to store data to MDSplus.
I cannot install mdsplus, only mdsplus-kernel. But include and bin folder are missing.

Linux 5.10.131-rt72-RedHawk-8.4.3-trace #1 SMP PREEMPT Thu Sep 1 14:09:13 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cenkoloji** [comment]
@FilipJankyTE , what OS/distro are you on? What MDSplus version are you installing?

Since a while, mdsplus-stable installs without issue on RHEL8 based platforms.

**Comment by FilipJankyTE** [comment]
@cenkoloji  Thank you very much for your reply.

Linux scatha3 5.10.131-rt72-RedHawk-8.4.3-trace #1 SMP PREEMPT Thu Sep 1 14:09:13 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

I have tried stable and alpha versions for example:
mdsplus-7.131-5.el8.noarch.rpm
mdsplus-7.128-1.el8.noarch.rpm
mdsplus-alpha-7.139-7.el8.noarch.rpm

I am maybe doing something wrong.

**Comment by cenkoloji** [comment]
RedHawk linux claims to be compatible with RHEL, Centos, Ubuntu (not sure how this is possible haha).

I assume there are some differences in packages/repositories, so that the RPMs for RHEL8 doesn't work. 

What's result of  `cat /etc/os-release`

**Comment by FilipJankyTE** [comment]
@cenkoloji 
cat /etc/os-release
NAME="RedHawk Linux"
VERSION="8.4 (Hadron)"
ID="redhawk"
ID_LIKE="rhel centos fedora"
CPE_NAME="cpe:/o:ccur:redhawk:8.4"
VERSION_ID="8.4"
PRETTY_NAME="RedHawk Linux 8.4 (Hadron)"
ANSI_COLOR="0;31"
HOME_URL="http://www.concurrent-rt.com/"
SUPPORT_URL="http://www.concurrent-rt.com/customer-support/"
BUG_REPORT_URL="http://www.concurrent-rt.com/support/"

PLATFORM_ID="platform:el8"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
