### ISSUE TITLE
test for readline needs <unistd.h> in code in configure

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2249]
On the macintosh the tests for readline fail with:
```configure:11117: gcc -o conftest -O3 -fvisibility=hidden  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -arch x86_64 -dynamic -Wno-missing-field-initializers -Wno-parentheses-equality -I/usr/local/opt/readline/include -I${top_srcdir}/include -I${top_builddir}/include   -L/usr/local/opt/readline/lib   conftest.c -lreadline  >&5
conftest.c:45:3: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  close(0);
  ^
conftest.c:48:3: error: implicit declaration of function 'dup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  dup(fd);
  ^
2 errors generated.
```
This is because close and dup are defined in <unistd.h> which is not included in the test program.  I could not find where this test program generated from so could not change it to add the extra include. The fixed (HACK) version of configure looks like:
```
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
#include <unistd.h>
#include <stdio.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <readline/readline.h>
#include <readline/history.h>
int main(int argc, char **argv)
{
  int fd;
  char *line;
  close(0);
  close(1);
  fd = open("/dev/null", 2);
  dup(fd);
  line = readline("giveittome> ");
  printf("got <%s>\n", line);
  return 0;
 }
////////////////////////////////////////////////////////////////////////////////
```

**Comment by santorofer** [comment]
Andrea, just to let you know:
1- the build, as you know, works well in the old Mac builder that is in place now (Sierra)
2- but, this seems to fail only in the new Mac mini builder (Catalina).
I'm not sure if this is relevant, but I thought to keep it in mind.

**Comment by santorofer** [comment]
One more thing, and I think this is relevant. When I installed the Command Line Tools in the new Mac mini:
xcode-select --install

This brought the following gcc version:

Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

While the version that is installed in the old Mac builder in used now, is:

Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
