### ISSUE TITLE
Does adding python devices work on macintosh ?

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2267]
With a new mac install when I try to add a python device it complains:

```
TCL> edit /new bagle
TCL> add node marte /model=MARTE


Unable to load python library: libpython3.8.so
Error: dlopen(libpython3.8.so, 10): image not found
```
I have not tracked down if this is an env problem or file extension problem yet.  Anyone else have this working ?

**Comment by joshStillerman** [comment]
Further when I try to do it from python:
```>>> from MDSplus import Tree
t = Tree('>>> t = Tree('bagle', -1, 'new')
>>> t
Tree("BAGLE",-1,"Edit")
>>> t.addDevice('marte', 'marte')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 734, in addDevice
    _exc.checkStatus(
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 94, in checkStatus
    raise exception
MDSplus.mdsExceptions.TreeLOCK_FAILURE: %TREE-W-LOCK_FAILURE, Error locking file, perhaps NFSLOCKING not enabled on this system
>>> 
```

**Comment by zack-vii** [comment]
we could activate the tests, or at least some, on the macosx Job to see..

**Comment by zack-vii** [comment]
> 
> 
> With a new mac install when I try to add a python device it complains:
> 
> ```
> TCL> edit /new bagle
> TCL> add node marte /model=MARTE
> 
> 
> Unable to load python library: libpython3.8.so
> Error: dlopen(libpython3.8.so, 10): image not found
> ```
> 
> I have not tracked down if this is an env problem or file extension problem yet. Anyone else have this working ?

But this loocks like you need to specify the PyLib env manually with a full path

**Comment by zack-vii** [comment]
> 
> 
> Further when I try to do it from python:
> 
> ```
> t = Tree('>>> t = Tree('bagle', -1, 'new')
> >>> t
> Tree("BAGLE",-1,"Edit")
> >>> t.addDevice('marte', 'marte')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/mdsplus/python/MDSplus/tree.py", line 734, in addDevice
>     _exc.checkStatus(
>   File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 94, in checkStatus
>     raise exception
> MDSplus.mdsExceptions.TreeLOCK_FAILURE: %TREE-W-LOCK_FAILURE, Error locking file, perhaps NFSLOCKING not enabled on this system
> >>> 
> ```

And this one i would only expect on Windows. well seems like macosx does not support NFS locking as well.. on could suppress the error for mac then as well. currently this is only an exception when not under windows.

**Comment by gauge2** [comment]
Not sure but I had the python library not found issue on Ubuntu18 for python 3.6, and had to specify the path to the python lib in LD_LIBRARY_PATH env using `envsyms` to append it to the current LD_LIBRARY_PATH.
Once that was sorted, was able to add new device. 

As for the NFSlocking etc, out of my wheelhouse.

**Comment by zack-vii** [comment]
hmm i guess i will close it then,,, the NFS is probably a different issue..
