### ISSUE TITLE
python Event class is needlessly inefficient

### ISSUE THREAD

**Issue by dgarnier** [MDSplus/mdsplus#2276]
the _event_run method which runs subclassed python events does a poll of the event queue with sleeps of 10 msec.  For fast events this is problematic.  Why not just wait for the events and sit on the underlying select/poll whatever it is?

**Comment by zack-vii** [comment]
Hm, the poll is the actuall wait with timeout. You are right though, the sleep would limit the repititionrate to 100Hz. I think this was meant to reduce the cpu load. I would suggest sending the total counter of the event as eventdata. This way you can keep track and process the right amount of events (which hopefully did not carry data already;) ). But I am not sure if the queue buffers more than one event, which would be bad for this usecase.

 Anyway, if it bothers you, you could make the sleep time variable, based on a field of the event class. Test, if this fixes it for you and possibly make a PR to the alpha branch.

Impotant though might be, that the default behaviour remains as other users may rely on that sleep.

Cheers

Timo

**Comment by dgarnier** [comment]
I looked at it more.. I agree with you.. it was probably unnecessary, but might be relied on by existing code now.  I just fixed my problem by subclass replacing the method (without the sleep).
