### ISSUE TITLE
MDSplus maintains singleton dimensions after subscripting

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2298]
I don't know if this is correct behavior or not.  For my particular case it is inconvenient.

I have a node containing a signal that is 
```
Build_Signal(Set_Range(4,4300,-.06440491052093825D0 /*** etc. ***/), *, [0D0,1D
```
if I evaluate
```
data(node)[3]
```
I get an answer that is of shape:
(4300, 1)

the singleton dimension is problematic and I think not subscripted correctly:
```
>>> dd = MDSplus.Data.execute('_y = data(.CONTROLLER.OUTPUTS.OUT2.VALUE)[3], _Y[1:*]')
>>> dd.shape
(4300, 0)
>>> dd = MDSplus.Data.execute('_y = data(.CONTROLLER.OUTPUTS.OUT2.VALUE)[3], _Y[,1:*]')
>>> dd.shape
(4299, 1)
>>> 
```
MDSplus is first fastest subscripting - **right ?**

anyone have thoughts about this?

**Comment by joshStillerman** [comment]
A more concise example:
```
_a = [[1,2,3],[4,5,6], [7,8,9], [10,11,12]]
[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
_a[0]
[[1], [4], [7], [10]]
_a[,0]
[1,2,3]
_a[0,]
[[1], [4], [7], [10]]
```
the question is should `_a[0,]` return `[1, 4, 7, 10]`.  If we made this change, what would it break ?

**Comment by joshStillerman** [comment]
We could easily have a flatten function:
```
_a = [[1,2,3],[4,5,6], [7,8,9], [10,11,12]]
[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
_b = _a[0,]
[[1], [4], [7], [10]]
set_range(len(_b), _b)
[1,4,7,10]
```
or to flatten across dimensions use size instead of len
```
set_range(size(_a), _a)
[1,2,3,4,5,6,7,8,9,10,11,12]
```
This latter works for both cases
```
set_range(size(_b), _b)
[1,4,7,10]
```

**Comment by zack-vii** [comment]
that all sound familliar, we have a flatten aun squeeze methond and syntax for a short while. its kind of matlab style

_a[:] return a flattened _a and _a[::] a squeezed version, i.e. it is _a with all singelton dimensions removed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by joshStillerman** [comment]
THANKS!!!!
