### ISSUE TITLE
How to operate array with TDI

### ISSUE THREAD

**Issue by Merlencer** [MDSplus/mdsplus#2307]
We can directly use "a = [1,2,3,3,5]" "a [3] = 4" to modify the value of an element of array a when using python.How can we achieve the same function with TDI？

**Comment by zack-vii** [comment]
I TDI this is not possible. .. you would have to do something like 
```tdi
_a = [1,2,3,3,5]
_a = [_a[0:3-1],4,_a[3+1:5]]
```
