### ISSUE TITLE
TDI fopen() call to open /tmp file no longer works through mdsconnect()

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2322]
This *used* to work, but doesn't now (we upgraded from Ubuntu 14.04 MDSplus v7-0-68 -> 18.04 MDSplus v7.128.1)

TDI> mdsconnect('***remote host name redacted***')
1
TDI> _u = fopen('/tmp/test.py', 'w')
Pointer(0x5651dc55c2e0)
TDI> _u = mdsvalue("_u = fopen('/tmp/test.py', 'w')")
$Missing

The file /tmp/test.py is created, but I get no file handle returned.

Any ideas?

Thanks,
Brian

**Comment by zack-vii** [comment]
that may be true the return value is a pointer and to work properly on 64 and 32bit machines the return value of changed to pointer. as you assinged _u remore you dont need to transfer the value to the client where the point has no meaning. you should be able to use the remote _u in consecutive calls do do stuff with the file. i have not tested it but you could try casing the pointer to int64 aka quadword.

**Comment by zack-vii** [comment]
ah so core issue is, that pointer is not a valid simple mdsip type. so, to transfer it you need to use serializeout/in

**Comment by nelson-zapenergy** [comment]
Thanks!  That makes sense.  I can use the "remote" _u pointer to write() and fclose():

 tdic
TDI> mdsconnect('zappa.zap')
1
TDI> mdsvalue("_u = fopen('/tmp/test.py', 'w')")
$Missing
TDI> mdsvalue('write(_u, "from MDSplus import Tree")')
25
TDI> mdsvalue('fclose(_u)')
0

... and I can see the line in the /tmp file.  I was indeed using the "remote" _u for write() and fclose(), but used the "local" _u to verify I was successful opening the remote file.  Sorry for the confusion.

I'm closing this issue, thanks again.
