### ISSUE TITLE
python: Active tree is not set when a new tree is opened

### ISSUE THREAD

**Issue by cenkoloji** [MDSplus/mdsplus#2335]
Hello, 

In  stable and alpha versions of MDSplus, if I open a tree in tdi, and I can use python ```MDSplus.Tree()``` to get the active tree,

```
TDI> TreeOpen("my_tree",-1)
265389633
TDI> py("import MDSplus; print(MDSplus.Tree())")
Tree("MY_TREE",-1,"Normal")
```

But if I open a tree in python, it's not set as the active tree by default. ```MDSplus.Tree()``` returns undefined Tree

```
>>> t = MDSplus.Tree("my_tree",-1)
>>> print(MDSplus.Tree())
Tree("?",?,"Closed")
```

In an older version (7.0-42), it seemed to work out of the box
```
>>> t = MDSplus.Tree("my_tree",-1)
>>> print(MDSplus.Tree())
Tree("MY_TREE",-1,"Normal")
```

Questions:

1. Is this expected behavior
2. Is there a way to explicitly set the active tree in python?

Thanks for the help
Cenk (from SPC-TCV, EPFL)

**Comment by zack-vii** [comment]
Hi Cenk,

I see you point, but the behavior had to change in favor or a stable handling of the tree context.  The context of Tree() is the tdi context, i.e. the global context that does not know about objects. if you where to close you Tree in python there has no consistent way of informing the global context. the Tree(expt, shot) is detached from the tdi context and will become invalid (freed and cleared) once you removed the last instance of the object of close the tree explicidly.
if you wish to use the global context you can use Tree() which will (is supposed to) reflect the dynamic behaviour of the tdi context. 
this context may be changed through user methods that are opaque to the api.

i have to play around a bit to figure out what would be the most convenient way to modify teh tdi context from withing python.
one could be:
```python
MDSplus.TdiExecute("TreeOpen($,$)", expt, shot)
```

**Comment by zack-vii** [comment]
if you only want to change the shot number you can do
```python
MDSplus.Tree().open(shot=shot)
```
however both methods will keep the currently opened trees open and add the new tree to the stack.

**Comment by cenkoloji** [comment]
I see what you mean. 

Using `TdiExecute` works for sure, I can live with it. I was mainly curious if there was already a method for this in the python API.

The issue can be considered closed for me...
