### ISSUE TITLE
MATLAB 2021a does not work with MDSplus module

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#2357]
Seems like checks for python code and prevents partial .m files from being loaded. Solution would be to export the python implementation in separate files.

**Comment by joshStillerman** [comment]
Hmm -
  It just worked for me:
```
jas@pc-marte2:~$ matlab -nosplash -nodisplay

                            < M A T L A B (R) >
                  Copyright 1984-2021 The MathWorks, Inc.
             R2021a Update 3 (9.10.0.1684407) 64-bit (glnxa64)
                                May 27, 2021

 
To get started, type doc.
For product information, visit www.mathworks.com.
 
>> mdsopen('marco', -1)

ans =

  int32

   -1

>> mdstcl('dir')

\MARCO::TOP

 :INPUT        :MARTE        :OUTPUT       :WAVEFORM    

Total of 4 nodes.

>>  
>> mdsInfo()

ans = 

  struct with fields:

           isConnected: 0
            connection: []
         connectedHost: ''
             usePython: 0
    isPythonConnection: 0
             useLegacy: 0

>> 
>> exit
jas@pc-marte2:~$ mdstcl
TCL> show version


MDSplus version: 7.134.0
----------------------
  Release:  alpha_release_7.134.0
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release_7.134.0
  Download: https://github.com/MDSplus/mdsplus/archive/alpha_release_7.134.0.tar.gz


TCL> 

```

**Comment by zack-vii** [comment]
Oh i got distracted by a meeting.. yes but it only works if you have a working python version in your PATH. If MATLAB cannot find python it will error out before even loading the m files suggestion on how to use CPython in matlab. This way even if you want to use the java bridge you wont be able to use the non python sections of the code

**Comment by joshStillerman** [comment]
I have verified this.  The problem is in the routine:
```
function err = setPython()
    global MDSINFO
    persistent cache
    if ~isempty(cache)
        err = cache;
    else
        try
            MDSINFO.ispy2 = logical(py.MDSplus.version.ispy2);
            err = false;
            cache = err;
        catch err
        end
    end
end
```
I moved it to another file and can call `mdsInfo(0)` but that does not fix subsequent calls to mdsopen - seems like it should since the 1st call should fill in the global.  I will check on that, and barring that working, I will put in some logic with an environment variable.

Actually the problem is that there are py calls in the other mdsxxx calls in matlab.  Calling mdsInfo() would be good enough if mdsvalue.m did not contain a py()

I will look at a more comprehensive fix after I go to a meeting.

**Comment by zack-vii** [comment]
I only saw it on a VM of a user. but is seemed there where more files involved. mdsinfo, MDSplusTo/From, mdsvalue and that sort.. they all have one method that implements the python branch of the code.
The issue is that MATLAB is compiling the file in one go and apparently in the new version injects python code directly.. as this fails if only on line in the whole file is python code, the file is rendered useless.. i possibly makes sense to create two subdirectories ./python and ./java each only containing pure python or java, respectively. the common code implements the API and will call the java or python subroutines as needed. there was a way to define private methods this way.. i think teh subdirectories must start with @ or something like that.

**Comment by zack-vii** [comment]
Hm the @ folders are for classes.. one could turn it into classes though  .. MDSINFO is practically used as some sort of class

**Comment by zack-vii** [comment]
the folder should be './matlab/private' and have files ala java_\*.m and python_\*.m which would be private to './matlab'.
setPython() would become python_setup.m setJava() java_setup.m and so on.
