### ISSUE TITLE
jScope generates "Main Shots evaluations error: Data type code : 24 not yet supported"

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2363]
When starting a jScope and filling in Customize->Global Settings: "Experiment" and "Shot"

I get a "Lost connection from : local" window over a window in the attached screenshot; any ideas?

<img width="268" alt="Screenshot 2021-08-15 11 55 07" src="https://user-images.githubusercontent.com/60521693/129489526-566d2aaf-31d4-4220-9d76-7622fd8944f7.png">

**Comment by zack-vii** [comment]
hm i think i have seen this one before. can you give us some information about the mdsplus versions involved. server and client, please. i think we fixed it but i could be wrong.

**Comment by zack-vii** [comment]
FYI, dtype 24 ist dtype dsc. which is not supported on all versions. the server may falsely respond with a mfsplus descriptor instead of an simple typed mdsip desc. this was a bug that should have been fixed i the latest versions.

**Comment by nelson-zapenergy** [comment]
Thanks Timo.  The server and client are both Ubuntu 20.04 LTS with MDSplus stable version 7.131.4 amd64

I also get this error running both through mdsip client (specifying the host) or on the server using "local" for the network.

**Comment by zack-vii** [comment]
hm i just tried i on out server.. running alpha 134 and also tested it with alpha 134.3 both work.. seems we only fixed in on alpha then..?

**Comment by nelson-zapenergy** [comment]
Thanks for checking TImo; are there any tests I could try to help?

**Comment by zack-vii** [comment]
core of issue is same as #2340, i will close this here and we should continue in the older thread.
