### ISSUE TITLE
TreeNodeArray Device nids from Tree.getNodeWild('***', 'DEVICE') fail in tree.py when referencing by index

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2368]
Any ideas on an alternative or workaround?

This *used* to work (in mdsplus stable 7.92.0 amd64), but doesn't in the latest stable mdsplus 7.131.5 amd64 on Ubuntu 20.04, viz., nids from tree.getNodeWild('***', 'DEVICE') fail in tree.py when referencing by index:

*****
tree = Tree('blah', 0)

nids = tree.getNodeWild('***', 'DEVICE')

In [19]: nids
Out[19]: [16777221,16777330,16777439,16777548,16777657,16777766,16777875,16777984,16778093,16778202,16778311,16778420,16778529,16778638,16778747,16778856,16778966,16779068,16778983,16779025,16779208,16779331,16779454]

nids[0]
Traceback (most recent call last):

File "", line 1, in
nids[0]

File "/usr/local/mdsplus/python/MDSplus/tree.py", line 3116, in getitem
return TreeNode(self._value[n], self.tree)

File "/usr/local/mdsplus/python/MDSplus/tree.py", line 1194, in new
return node.record.getDevice(node, head=0)

File "/usr/local/mdsplus/python/MDSplus/compound.py", line 264, in getDevice
cls = _tre.Device.PyDevice(model)

File "/usr/local/mdsplus/python/MDSplus/tree.py", line 4001, in PyDevice
modname = _ver.tostr(models[idx][0].tolist().rstrip())

AttributeError: 'int' object has no attribute 'tolist'

**Comment by nelson-zapenergy** [comment]
Wait, there's more; it's not getNode(), it is referencing the nids NodeArray by element

In [19]: nids
Out[19]: [16777221,16777330,16777439,16777548,16777657,16777766,16777875,16777984,16778093,16778202,16778311,16778420,16778529,16778638,16778747,16778856,16778966,16779068,16778983,16779025,16779208,16779331,16779454]

nids[0]
Traceback (most recent call last):

  File "<ipython-input-20-9e4faf48a429>", line 1, in <module>
    nids[0]

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 3116, in __getitem__
    return TreeNode(self._value[n], self.tree)

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 1194, in __new__
    return node.record.getDevice(node, head=0)

  File "/usr/local/mdsplus/python/MDSplus/compound.py", line 264, in getDevice
    cls = _tre.Device.PyDevice(model)

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 4001, in PyDevice
    modname = _ver.tostr(models[idx][0].tolist().rstrip())

AttributeError: 'int' object has no attribute 'tolist'

**Comment by nelson-zapenergy** [comment]
FYI:  I can reference nid TreeNodeArrays by index for Nodes other than Devices:

allNids = t.getNodeWild('***')

allNids[74]
Out[33]: .FANALYSIS.B_SM.THETA_315

allNids[75]
Traceback (most recent call last):

  File "<ipython-input-34-f702988a4420>", line 1, in <module>
    allNids[75]

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 3116, in __getitem__
    return TreeNode(self._value[n], self.tree)

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 1194, in __new__
    return node.record.getDevice(node, head=0)

  File "/usr/local/mdsplus/python/MDSplus/compound.py", line 264, in getDevice
    cls = _tre.Device.PyDevice(model)

  File "/usr/local/mdsplus/python/MDSplus/tree.py", line 4001, in PyDevice
    modname = _ver.tostr(models[idx][0].tolist().rstrip())

AttributeError: 'int' object has no attribute 'tolist'

**Comment by zack-vii** [comment]
hm looks like there is something wrong with the device that this node represents.. can you shine some light on what die specific node is about.. is it a device node (or sub-node of a device)? if yes can you please provide the device source or model if it it a device shipped with mdsplus?

**Comment by nelson-zapenergy** [comment]
Thanks Timo:  That's a good point, it *is* a Python Device I wrote, I will double-check if there is something weird.  

However, if I remove my pydevices directory from MDS_PYDEVICE_PATH, I can't add a W7xDevices item:

$ export MDS_PYDEVICE_PATH=/usr/local/mdsplus/pydevices
$ mdstcl
TCL> edit/new test/shot=-1
TCL> add node acq480 /model=acq480
Error adding device instance of acq480: 'int' object has no attribute 'tolist'
Error adding node acq480
Error was: %MDSPLUS-E-ERROR, Error
mdsdcl: --> failed on line 'add node acq480 /model=acq480'
TCL> exit
$ locate acq480.py
/usr/local/mdsplus/pydevices/W7xDevices/acq480.py

Also, a gvimdiff of the tree.py that works for me (on the left) and the latest tree.py (on the right) shows the line where it's failing (second magenta line --- the rest of the differences seem to be PEP8 cleanups):

<img width="1007" alt="Screenshot 2021-08-18 13 03 11" src="https://user-images.githubusercontent.com/60521693/129964895-aa755b41-92f4-4807-869b-a6df07e17bff.png">

**Comment by nelson-zapenergy** [comment]
SORRY MY BAD:  Thanks Timo; it was I had a "remnant" MdsDevices.fun TDI function in my MDS_PATH (line 2 rows higher than the second magenta line); getting rid of the fun file fixes it!  Sorry for the wild goose chase.

**Comment by zack-vii** [comment]
no worries, it took this insight into the python to fixup some pep issues and found an unrelated bug so it was worth it ;)
