### ISSUE TITLE
mdsplus.org not reachable as of 1030am EDT

### ISSUE THREAD

**Issue by gauge2** [MDSplus/mdsplus#2382]
Hope this is the right place to report this:

Prior to this time, today, was able to reach the site. After this, unable to. Change happened as adding repo key to apt get and updating apt. Ubuntu20 not listed on site so confirmed in the repo link then when back to terminal to run. got the key, then mdsplus.org stopped responding. As of this post still not reachable. 

Have tried on phone, on different machines on the network (linux and windows), on a VPN from my network, off my network. 
it's hilarously bad timing! I was ready to install it and build a tree for our experiment lol. Oh well. C'est la vie.

**Comment by zack-vii** [comment]
and its back.. this was like due to maintenance
