### ISSUE TITLE
jScope drops mdsip remote connection if Node is invalid

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2391]
In the most-recent stable MDSplus releases (Windows, Mac, & Ubuntu 20.04) if a Node is not found (e.g. a typo, or if the data are not yet stored) jScope dropped the mdsip connection.  It is solved by correcting the Node name and/or waiting for the data to store, but required selecting Network -> remote mdsip server.

I had not seen this behavior before with previous jScope releases.  In our /var/log/mdsplus/mdsipd/errors file I see these:

Connected: JAVA_USER
free(): invalid pointer

The "free(): invalid pointer" occurs when I try to plot a Signal that does NOT contain data.

I'm happy to do any tests that could shed light on this, thanks in advance.

**Comment by nelson-zapenergy** [comment]
Any ideas on this?  People are constantly losing connections if they try to read Signals in jScope for "shot 0" before the data are stored.  
Could this be a server-side issue?  (I'm thinking not, as "free(): invalid pointer" shows up in errors immediately after trying to read an empty Signal.)
Thanks in advance.

**Comment by zack-vii** [comment]
can you retry this with the most recent alpha version please..?
I remember there was an issue in the java module that we fixed, but i could be mistaken.

**Comment by GabrieleManduchi** [comment]
jScope loses connection if the mdsip connected server crashes. This holds also for local connection as mdsip is run as a subprocess. So I think you should investigate why mdsip crashes. If the signal is not found, the not found message is shown by jScope, but the connection is not lost.

So I think you should investigate the reason for the crash when non existing signals are accessed. maybe they go through some function? You may replicate the issue using mdsconnect in tdic

**Comment by nelson-zapenergy** [comment]
Thanks Timo: I'll try to look at the alpha build ... were you referring to the (closed) Issue: "jScope broken #2052"

Thanks Gabriele:  That is certainly possible that I have TDI functions causing this, however, we have had previous versions of jScope that did NOT drop the connection calling the exact same TDI functions.  Also, I can NOT reproduce the remote server crash using mdsconnect() in tdic.  Namely, I am copying and pasting the "Y" field from a jScope (that disconnects) into the TDIC> prompt, wrapped by mdsvalue(), and I just get a "*" response, and have never seen the mdsip process crash.

Any other ideas or tests I could do?

Thanks again

**Comment by morgak** [comment]
This sounds like the server-side issue in : "mdsip / gcc-9.3 optimization issue? [#2372](https://github.com/MDSplus/mdsplus/issues/2372)".  
Same symptom at least, mdsip server crashing when jScope (and only jScope) tries to access an empty node. If it is the same, the fix Timo made in that post works (it worked on my setup at least), so alpha might have the fix already.

**Comment by nelson-zapenergy** [comment]
Thanks Kyle:  Timo & Gabriele:  Do you know if the fix to Issue #2372 made it into the stable Ubuntu 20.04 build?
Thanks in advance.

**Comment by nelson-zapenergy** [comment]
I tried to find if the fix #2372 got into the stable Ubuntu 20.04 build, but to no avail.

Is there a way to check?  (The dropped connections are still happening.)  Thanks.

**Comment by joshStillerman** [comment]
I have made a PR to stable for this.  Should be merged and folded into 
stable shortly.

https://github.com/MDSplus/mdsplus/pull/2405


On 10/27/21 12:56 PM, nelson-zapenergy wrote:
>
> Is there a way to check? (The dropped connections are still 
> happening.) Thanks.
>
-- 
*Joshua Stillerman*
Research Engineer
MIT Plasma Science and Fusion Center
617.253.8176
***@***.***

**Comment by nelson-zapenergy** [comment]
Any update on this?  It seems to happening more frequently and making it difficult to look at data through jScope.

Thanks for any info.

**Comment by nelson-zapenergy** [comment]
Thanks everyone, the new version is working fine.  I haven't been able to break it with the fix.  Closing issue.
