### ISSUE TITLE
MDSplus python module defaults to be installed in system built-in python 

### ISSUE THREAD

**Issue by WenyinWei** [MDSplus/mdsplus#2393]
Hello all, I followed the installation routine on [MDSplus install](https://www.mdsplus.org/index.php/Downloads) to install MDSplus python module on Ubuntu and Windows. Sadly the installation defaults to be done for the system built-in python, which means it is hard to use MDSplus for virtualenv users.

It is fortunate for Windows users that they can simply new a python virtualenv from the system python after install of MDSplus, then the MDSplus package would be brought together into the new env. While for Ubuntu users, I also gave it a  try but failed,  do we have any good ideas about installing MDSplus package in virtual python env?

**Comment by joshStillerman** [comment]
They can turn on their virtual environment and then use.pip install -e /usr/local/MDSplus/Python/MDSplusOn Sep 27, 2021 10:51 PM, Wenyin Wei ***@***.***> wrote:
Hello all, I followed the installation routine on MDSplus install to install MDSplus python module on Ubuntu and Windows. Sadly the installation defaults to be done for the system built-in python, which means it is hard to use MDSplus for virtualenv users.
It is fortunate for Windows users that they can simply new a python virtualenv from the system python after install of MDSplus, then the MDSplus package would be brought together into the new env. While for Ubuntu users, I also gave it a  try but failed,  do we have any good ideas about installing MDSplus package in virtual python env?

**Comment by WenyinWei** [comment]
Oh cool, any idea for Windows users if their virtual env were derived from the system python env which had not yet equipped with MDSplus?

**Comment by WenyinWei** [comment]
I failed to find the correspondent `MDSplusOn` in the directory `C:\Program Files\MDSplus`. Would you mind giving me some tips?

C:\Program Files\MDSplus\
- devtools\
- epics\
- idl\
- include\
- java\
- LabView\
- matlab\
- pydevices\
- python\
  - MDSplus\
    - tests\
    - widgets\
    - wsgi\
    - __init__.py
    - ...
- tdi\
- trees\
- xml\
- ChangeLog
- mdsplus.ico
- MDSplus-License.rtf
- uninstall.dat
- uninstall.exe

**Comment by zack-vii** [comment]
I am not sure whats special about the virtual envs but you can try to:

* register the env for your user.
```batch
setX PYTHONPATH "C:\Program Files\MDSplus\python"
```

* set the env for your session.
```batch
set "PYTHONPATH=C:\Program Files\MDSplus\python ; python
```

* add it in python
```python
import sys
sys.path.append("C:\\Program Files\\MDSplus\\python")
import MDSplus
```

**Comment by WenyinWei** [comment]
Excellent and comprehensive solutions! I am used to installing python packages by pip so a little bit confused when I installed MDSplus by an executable on Windows. Now I know it is safe to simply append the path of MDSplus python package folder to the Python search list. Thank you!
