### ISSUE TITLE
Mispelled python exception names

### ISSUE THREAD

**Issue by fluffynukeit** [MDSplus/mdsplus#2395]
The following MDS python device exception names are mispelled.  This makes using them difficulty because users generally expect words to be spelled correctly.  I spent a good 5-10 minutes trying to figure out why I couldn't use DevUNKNOWN_STATE before realizing it was mispelled in the module.

- DevFREQ_TO_HIGH
- DevUNKOWN_STATE
- L8212FREQ_TO_HIGH
- TreeEDITTING

**Comment by joshStillerman** [comment]
Should be fixed by: https://github.com/MDSplus/mdsplus/pull/2400

Thanks for pointing this out.

btw: who are you?  Where are you using MDSplus ?

**Comment by fluffynukeit** [comment]
I am an employee at Zap Energy Inc., a fusion startup in the Seattle area.  I work with @nelson-zapenergy.
