### ISSUE TITLE
Memory leak on signal destructor 

### ISSUE THREAD

**Issue by cbarber4** [MDSplus/mdsplus#2412]
Here's a simple program that creates a signal out of a data array and time array.

        std::vector<float> v(50, 50);
        std::vector<double> time_v;

        for (auto i = 0; i < 50; ++i) {
                time_v.push_back(i);
        }

        MDSplus::Float32Array mds_v(const_cast<float *>(&v[0]), v.size());
        MDSplus::Float64Array time(const_cast<double *>(&time_v[0]), time_v.size());

        MDSplus::Signal sig(&mds_v, nullptr, &time);

When run, a "double free or corruption (out)" error is thrown. Running valgrind on the program gives the following:

![image](https://user-images.githubusercontent.com/93614790/140084251-a2b2b8e4-4836-4b66-a1fc-d3720f6046c0.png)

The call stack for the Signal destructor ( ~Signal() -> ~Compound()  -> propagateDeletion() -> ~Float32Array() ) ends with a 'delete' being called on the Float32Array. For some reason, it does not invoke the parent ~Array() destructor, which calls the correct 'delete [].' If I don't construct the signal at all, the program runs fine and the arrays are deleted from memory cleanly. 

This could be something I'm doing wrong in creating the the signal, but I believe the issue lies in how deletion propagates through Signal and its parent classes. Any help would be appreciated! Thanks.

**Comment by cbarber4** [comment]
I should note that this is using the current stable branch.

**Comment by GabrieleManduchi** [comment]
In your code example you are assigning to the Signal objects the address of two objects allocated on the stack (mds_v and time).

In your code when sig runs out of scope, its destructor is called that tries to deallocate the internal array references mds_v and time. However they are not allocated in the heap, but in the stack, thus causing memory corruption 

This is not the intended way of handling objects in mdsobjects. You need to allocate them dynamically, e.g. 

 MDSplus::Float32Array *mds_v = new MDSplus::Float32Array(const_cast<float *>(&v[0]), v.size());
 MDSplus::Float64Array *time = new MDSplus::Float64Array(const_cast<double *>(&time_v[0]), time_v.size());


  MDSplus::Signal *sig = new MDSplus::Signal(mds_v, nullptr, time);

All mds objects must be dynamically allocated, the main reason being that they heavily use virtual methods, that work only on objects reference. For example when you read from a Tree you get a generic MDSplus::Data objects (you may not know the actual type) and its methods shall depend on the actutal type of the instance

**Comment by cbarber4** [comment]
Thank you for the help and quick response.
