### ISSUE TITLE
Fail to find mds_status

### ISSUE THREAD

**Issue by szhyuling** [MDSplus/mdsplus#2436]
I am sorry to pardon you,could you tell me how to get mds_status by python?

**Comment by szhyuling** [comment]
Like this by matlab
 [shotopened,mds_status]=mdsopen('east',double(shot));

**Comment by zack-vii** [comment]
Hi, well afaik, you dont, python handles mds_status codes automatically as raises an MDSplusException on error. You can
use try ... catch blocks if you wish to handle exceptions.

**Comment by szhyuling** [comment]
OK,I use try...catch blocks

**Comment by szhyuling** [comment]
Thank you
