### ISSUE TITLE
mdsConnector for accessing DIIID data on atlas via iris and cybele?

### ISSUE THREAD

**Issue by jabbate7** [MDSplus/mdsplus#2448]
Not sure if this is the right place to ask this, but I'm having trouble accessing the atlas server from non-"official" servers to try to get at DIIID data. I have ssh configured so I can type "ssh iris" and it automatically logs me in (i.e. my .ssh/config file properly tunnels and I have keys set up) but I can't seem to find the right syntax for mdsConnector to properly hop. I can try to look deeper into the weeds myself, but **does anyone happen to have an example or know somebody who has already done this to access DIIID data via the python mdsConnector?**

**Comment by joshStillerman** [comment]
Sorry for the late reply.

If you have a working ssh tunnel, then you do not need to use the hop functionality.  It was put in for jump hosts that did not allow ssh tunneling.

Let use know if you have further trouble, or questions
