### ISSUE TITLE
fix return parameters from mdsput.m

### ISSUE THREAD

**Issue by FilipJankyTE** [MDSplus/mdsplus#2451]
mdsvalue.m returns an MDSobject and status, however, in mdsput the object is inserted into the status and no status is returned.

please return also status

**Comment by santorofer** [comment]
Hi Filip,

There are two different 'status' that are returned, depending of the Matlab API function being used, and that can be confusing:

a- a binary status value, defined as 0 FAILURE, 1 SUCCESS; or
b- the MDSplus status, that has a numerical value that can be translated to a more descriptive string

Therefore, I think there are two issues here:

1- mdsvalue.m CANNOT give you the MDSplus status, but instead it gives you a status of 0 or 1, failure or success.
2- mdsput.m CAN give you the MDSplus status.

As an example, to see the descriptive version of the mdsput status, you can do the following. In my example test tree, I try to put a string in a node of the model (which is not a good idea, and you will see the status returned for that action). In a Matlab command line, after opening the model tree:

```
>> address = 'x.x.x.x'
>> mdsput(':NODE', '$1', address)

ans =

  int32

   265388450
```

And that is the status value from MDSplus. If you want to actually have the message associated with it, then you can do:

```
>> mdsgetmsg(265388450)

ans =

    '%TREE-E-NOWRITESHOT, Data for this node can not be written into the SHOT file'
```

I hope this helps you.
Cheers!,
Fernando
