### ISSUE TITLE
only for old-trees branch -- jTraverser does not allow adding long node names

### ISSUE THREAD

**Issue by mwinkel-cfs** [MDSplus/mdsplus#2470]
On the old-trees branch, launch jTraverser in edit mode.   Edit a new tree.   Add a node with a long node name.  A pop-up then appears complaining about the long node name.

Note that mdstcl and jTraverser2 work fine when adding long node names.   Failure is only on jTraverser.

![jtraverser](https://user-images.githubusercontent.com/98131549/176593249-e4dd3522-317d-497e-b8ba-81ad2df25259.jpg)

**Comment by mwinkel-dev** [comment]
Fixed by PR #2471
