### ISSUE TITLE
No 'treename'_path

### ISSUE THREAD

**Issue by LiyeeW** [MDSplus/mdsplus#2494]
Hello, I get into trouble and need your help. There is a MDSplus server.   **huser** is a user and **htree** is a tree.

1) the path is OK
huser@dataserver:~$ echo $htree_path
/data/~g~f~e~d~c/~t;/data/~t

2)open it locally is OK
huser@dataserver:~$ tdic
TDI> TreeOpen("htree", -1)
265389633
TDI> 
-----------
class TreeSUCCESS(TreeException):
  status=265389633
  message="Operation successful"
  msgnam="SUCCESS"

3)mdsip mapping is OK
huser@dataserver:~$ cat /etc/mdsip.hosts
*@127.0.0.1 | huser
*@192.168.0.* | huser

4)file permission is OK
huser@dataserver:~$ ls -l /data
总用量 25
drwxrwxrwx 3 huser huser 3 9月  23 09:15 20000
drwxrwxrwx 2 huser huser 6 9月  23 09:14 htree

5)connect and open by Python or jTraverser2 FAIL
>>> c.openTree("htree",-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/mdsplus/python/MDSplus/connection.py", line 287, in openTree
    _exc.checkStatus(self.get("TreeOpen($,$)", tree, shot))
  File "/usr/local/mdsplus/python/MDSplus/mdsExceptions.py", line 94, in checkStatus
    raise exception
MDSplus.mdsExceptions.TreeNOPATH: %TREE-E-NOPATH, No 'treename'_path or default_tree_path environment variables defined. Cannot locate tree files.

I'm not sure what's wrong with my configuration. Could you please help me?
(The style is weird so I copy the context to the file
[context.txt](https://github.com/MDSplus/mdsplus/files/9821315/context.txt)
)

**Comment by cenkoloji** [comment]
Where is path of tree set? If you want to make it global, I believe you have to set it in `/etc/mdsplus.conf`

To check if you have the correct path after connection:
```
c = MDSplus.Connection("localhost")
c.get("getenv('htree_path')")
```

Btw, for formatting on github, you can wrap the relevant output in code tags (`<> `on the little bar on top of the edit window)

**Comment by LiyeeW** [comment]
Thank you very much. It has been solved in your way.
