### ISSUE TITLE
Missing customized environment with installation on Ubuntu 22.04

### ISSUE THREAD

**Issue by merlea** [MDSplus/mdsplus#2495]
I installed the `MDSplus` packages from the official repository on `Ubuntu 22.04` and I noticed that there is no definition of the environment variable `MDSPLUS_DIR`, nor does the mdsplus directory appear anywhere in the `PATH` and `LD_LIBRARY_PATH` variables.

As a result I wasn't able to start an MDSip connection using the SSH protocol unless I manually add `/usr/local/mdsplus/bin` to the `PATH` variable.

When I tried to use the repository for Ubuntu 20.04 (but still on my 22.04 OS) the same error persisted, so this might be a change in behaviour of the dpkg tool?

**Comment by joshStillerman** [comment]
This is supposed to be done by /etc/profile.d/mdsplus.sh  If you type:

> . /etc/profile.d/mdsplus.sh
> 
(that is dot space /etc/profile.d/mdsplus.sh

Is everything defined for you?

**Comment by merlea** [comment]
Indeed thanks I had forgotten about this. So you need a fresh new login session for things to automatically be activated, or you need to type this command in every new shell session.

Perhaps a word of warning during the package installation would be helpful. Otherwise you can close this.
