### ISSUE TITLE
TDI function "spread()" crashes if called with a scalar argument

### ISSUE THREAD

**Issue by WolfgangSuttrop** [MDSplus/mdsplus#2503]
Hi,
I just noticed that spread() now crashes if the first argument is a scalar:

$ tdic
TDI> spread(2.5,0,10)
malloc(): invalid size (unsorted)
Abort (core dumped)
$ 

Passing a one-element array works. 

I am using mdsplus-alpha 7.139.12 on Ubuntu 20.04
$ uname -a
Linux xxx 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Greetings,
Wolfgang

**Comment by joshStillerman** [comment]
thank you for reporting this.  We will look into it.
