### ISSUE TITLE
mdsconnector is broken?

### ISSUE THREAD

**Issue by sshiraiwa** [MDSplus/mdsplus#2507]
Hello. I would like to read a data from remote MDSplus server and I thought mdsconnector is a tool for that
purpose. Somwhow, pip installation does not work. Am I missing something?

$ pip install mdsconnector
$ python
Python 3.9.7 (default, May 10 2022, 23:45:56) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-10)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mdsconnector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sshiraiw/twopi_roots/20220725/lib/python3.9/site-packages/mdsconnector/__init__.py", line 9, in <module>
    mdsConnector=_import('mdsconnector').mdsConnector
AttributeError: partially initialized module 'mdsconnector' has no attribute 'mdsConnector' (most likely due to a circular import)

**Comment by joshStillerman** [comment]
Hi -
  I have verified this.  The circular import is not the only thing that does not work.  When I fixed that, I ran into changes to plumbum.lib which invalidate some of the mdsconnector code.  This will require a reworking of the whole thing.  We will add this to our Queue of things to do, but it is not a small task.  It will take a while.

--Josh

**Comment by joshStillerman** [comment]
Hi -
  With particular versions of rpyc, dill and plumbum it does work!  Remove them with pip and reinstall:
```
$ pip uninstall rpyc dill plumbum mdsconnector

$ pip install --user rpyc==4.1.5 dill==0.3.2 plumbum==1.6.9 mdsconnector
```
I will look into:

- changing the requirements to include versions
- updating the code to work with current versions of those libraries
  - This 2nd step is a bit difficult

**Let us know if setting the versions of the dependent packages works for you**

**Comment by joshStillerman** [comment]
The new version of mdsconnector (1.8.0) should install and work with modern python.  Let us know if you still have problems...
