### ISSUE TITLE
Cannot use LIST or DICT over thin client

### ISSUE THREAD

**Issue by fluffynukeit** [MDSplus/mdsplus#2508]
Minimal examples:

```
c.get("LIST(*, 1, 2)")
c.get("DICT(*, 1, 2)")
```
Each of those invocations results in KeyError: 183

Edit: this is on stable 7-131-6
Edit2: trying this again and now getting segfaults on the client side instead of keys errors.
Edit3: No luck trying to circumvent the TDI language and using python directly:

```
c = Connection("127.0.0.1"); c.get('py(["from MDSplus import Dictionary","ans=Dictionary((1,2))"
   ...: ],"ans")')
```
First resulted in KeyError: 97, then running immediately again caused segfault.

**Comment by zack-vii** [comment]
Hi there, yea not being able to get complex objects is due to the kind of the interface. mdsip interface can only transport arrays and scalars of simple types, i.e. numbers and stings. You already have noticed hat you need to request `get("DIM_OF(MY:SIGNAL)")` to get the dimensions rather than `get("MY:SIGNAL").dim_of()`. In order to get complex objects you can us a trick, i.e. serializing the object on the server and deserializing it on the client. this is done in the method getObject() and also massively used in jTraverser2.
```
    def getObject(self, exp, *args, **kwargs):
        return self.get('serializeout(`(%s;))' % exp, *args, **kwargs).deserialize()
```

**Comment by fluffynukeit** [comment]
getObject does work, thanks!  Is there a limit on the byte size or depth of the serialized complex object?

**Comment by zack-vii** [comment]
well there is a limit to the mdsip message.. as well as to the length of an array itself.. i think it is 2GB given by max of int32

**Comment by fluffynukeit** [comment]
Is it true that EmptyData cannot be deserialized?

```
In [28]: a = Dictionary((1, 2))

In [29]: a.serialize().deserialize()
Out[29]: {1: 2}

In [30]: a = Dictionary((1, None))

In [31]: a[1]
Out[31]: *

In [32]: type(a[1])
Out[32]: MDSplus.mdsdata.EmptyData

In [33]: a.serialize()
Out[33]: Byte([4,0,-40,-60,16,0,0,0,0,0,0,1,8,0,0,0,24,0,0,0,0,0,0,0,4,0,8,1,8,0,0,0,1,0,0,0,0,0,0,0])

In [34]: a.serialize().deserialize()
```
`AttributeError: 'super' object has no attribute '__getattr__'`

**Comment by joshStillerman** [comment]
Timo -
  Since you started on this one, can you reply?

**Comment by zack-vii** [comment]
Hi there, hm looks like a bug. you would deserialize the Int8Array that is the serialized EmptyData. it may be that the repr of EmptyData does not work or the deserialization to an EmptyData is special and does not work properly. i will try to reproduce this with the current alpha.

**Comment by zack-vii** [comment]
it was a bug.. quickfix: remove the  `descriptor.dtypeToClass[ ...` lines at the end of apd.py
