### ISSUE TITLE
MDSPlus documentation typos

### ISSUE THREAD

**Issue by segovale** [MDSplus/mdsplus#2516]
Hi,

I am starting to learn MDSPlus, and by reading the documentation I've found some typos/errors:

1- At https://www.mdsplus.org/index.php?title=Documentation:Tutorial --------> tag "/font" is visible on the text.
2- At https://www.mdsplus.org/index.php?title=Documentation:Tutorial:CreateTrees --------> Missing gif/image : Image:Tree-with-caption.gif.
3- At https://www.mdsplus.org/index.php?title=Documentation:Tutorial:CreateTrees --------> A coma is missing at: put TIMES "[0.,0.1,0.2,0.3,0.4,0.5.0.6,0.7,0.8,0.9]".

That's for now.

Thanks in advance,
Alex

**Comment by joshStillerman** [comment]
Fixed now.  Thanks!
