### ISSUE TITLE
mdsplus8 has an intermittent segfault that Valgrind can trigger

### ISSUE THREAD

**Issue by mwinkel-dev** [MDSplus/mdsplus#2523]
There are two formats for treefiles.   Format-2 was introduced in mdsplus8; Format-1 is used by all prior versions of MDSplus.   Format-2 has 64-character node names (63 visible, plus a null terminator).   Format-1 has 12-character node names padded with trailing blanks (and no null terminator).

When mdsplus8 reads a Format-1 treefile, it has to do in-memory expansion of the data structures.   Thus there is a fair amount of memory shuffling going on.

The attached bug.c program shows that there is a bug in the mdsplus8 code that processes Format-1 treefiles.   Interestingly, the program runs fine at the Linux terminal prompt and also in gdb.   However when run in Valgrind, it causes a variety of crashes.

Although the Valgrind crash is repeatable and consistent for a given set of factors (valgrind parameters, same branch head, etc.), note that changing those factors will alter how memory is corrupted.   Most of the time the corruption is so bad that Valgrind crashes.   Occasionally, a set of factors can be selected that allows Valgrind to detect a segfault.   And the memory corruption also makes it difficult to debug the problem using Valgrind's remote monitor for gdb.

When the same program is linked with the alpha branch (MDSplus ver. 7), it runs fine in Valgrind (and also in gdb and at the terminal prompt).

To see the bug, follow the instructions in the header comments of the attached bug.c program.   Example output of a Valgrind crash has also been attached.  

[bug.txt](https://github.com/MDSplus/mdsplus/files/10514504/bug.txt)
[valgrind_err.txt](https://github.com/MDSplus/mdsplus/files/10514414/valgrind_err.txt)

**Comment by zack-vii** [comment]
Did you try address-sanitizer on your test code yet? It may reveal more clarity.. also gdb of the valgrind process may allow you to inspect the issue further.
Also did you try other trees or shots?

**Comment by mwinkel-dev** [comment]
Thanks for the tips!  Yes, I used gdb with Valgrind to debug the issue and devise a fix (see PR #2524).   A related segfault (#2519) was initially found prior to the DAQ PDR when looping over 17 C-Mod shots (to estimate speed of a cross-campaign analysis).   During the investigation of that bug, it was determined that the issue could be simplified to just looping over a single C-Mod shot.   There is nothing special about the C-Mod shots -- any treefile (generated prior to mdsplus8) with subtrees has the potential to trigger the bug.
