### ISSUE TITLE
GETNCI(\\PATH::TOP.TO:NODE, "RECORD") doesn't seem to work?

### ISSUE THREAD

**Issue by pfbuxton** [MDSplus/mdsplus#2545]
Hi,

The "record" is what is actually contained within a node.

This command should retrieve the node "record". However, instead it returns the evaluated node.
```python
conn = Connection('IP_ADDRESS')
conn.openTree('TREE')
conn.get('GETNCI(\\PATH::TOP.TO:NODE, "RECORD")')
```

However, using the Tree class correctly works and retrieves the record:
```python
t = Tree(tree_name, pulseNo, 'ReadOnly')
n = t.getNode(place_to_read)
n.getRecord()
```

The reason it's more convenient to use the Connection class is that you don't have to add environment variables.

Thanks!

**Comment by joshStillerman** [comment]
Shouldn’t the first argument to conn.get be a string?Sent from my iPhoneOn Mar 19, 2023, at 2:41 PM, Peter Buxton ***@***.***> wrote:﻿
Hi,
This command:
conn = Connection('IP_ADDRESS')
conn.openTree('TREE')
conn.get(GETNCI(\\PATH::TOP.TO:NODE, "RECORD"))
returns the evaluated node.
However, using the Tree class correctly works and retrieves the record:
t = Tree(tree_name, pulseNo, 'ReadOnly')
n = t.getNode(place_to_read)
n.getRecord()
The reason it's more convenient to use the Connection class is that you don't have to add environment variables.
Thanks!

**Comment by pfbuxton** [comment]
True. I corrected the example. But this is not the reason it's not working.

**Comment by pfbuxton** [comment]
All other GETNCI calls work, such as TIME_INSERTED and NID_NUMBER.

**Comment by joshStillerman** [comment]
That is because get has to return a python native type. It does not know anything about the higher level types, which are MDS plus specific.Sent from my iPhoneOn Mar 19, 2023, at 3:33 PM, Peter Buxton ***@***.***> wrote:﻿
All other GETNCI calls work, such as TIME_INSERTED and NID_NUMBER.

**Comment by pfbuxton** [comment]
Thank you for the replies - I do really appreciate it.

I have tried quite hard and I agree - there doesn't seem to be a way of retrieving the record using the Connection class or TDI commands.

The closest I came to being able to retrieve the record is if the node contained a TDI/python function call I can use repeated calls to `ARG_OF` to kind of reconstruct the record:
```python
from MDSplus import Connection

conn = Connection('IP_ADDRESS')
conn.openTree('TREE', shot_no)
mds_path = '\\PATH::TOP.TO:NODE'

# Number of "arguments" behind node
nArgs = conn.get(f'ndesc({mds_path})').data()

# retrieve the record, argument by argument (first argument is empty? Note - this is not robust!)
command = ''
for iArg in range(1, nArgs):
    command = command + str(conn.get(f'ARG_OF({mds_path},{iArg})').data())
    if iArg==1:
        command += '('
command = command + ')'

print(command)
```

Can I ask - what is the expected behaviour of `conn.get('GETNCI(\\PATH::TOP.TO:NODE, "RECORD")')`

**Comment by joshStillerman** [comment]
I would say that it should return the 'value' of the record. That is the 
evaluation of the first descriptor of the signal into a native type.  
connection.get  is the equivalent to MDSvalue in Matlab or IDL.

-Josh

#close
