### ISSUE TITLE
Question:  Can one embed dimensions in an image displayed in jScope?

### ISSUE THREAD

**Issue by nelson-zapenergy** [MDSplus/mdsplus#2546]
Hi All,

We are displaying magnetograms in jScope (e.g. time on the abscissa, spatial location on the ordinate, value of magnetic field as the image).  I embedded MDSplus Dimensions into an MDSplus Signal object
e.g., Signal(b, None, t, z) where b (in NumPy) has dimensions [1, len(z), len(t)] (we're only displaying a single image).

jScope will display the magnetogram (I had to convert from floating point values to Uint16Array values), but the axes (via the jScope pointer) are index values, NOT t nor z.

Also, must jScope images be integer?

Thanks,
Brian

**Comment by GabrieleManduchi** [comment]
Not sure to understand. The pixel values of the displayed image can also be float, and the reported axis values when in point mode are the real axis values, not their indexes.
Try showing in jScope the following:

_x = 0 : 2 * $pi :  0.1;
_y = 1 :  10  :  1;
_s = ( sin(_x) * 100 );
_z = [ _s, 2*_s, 3*_s , _s*4, _s*5, _s*6, _s*7, _s*8, _s*9, _s*10 ];
build_signal( _z,  , _x,  _y )

**Comment by nelson-zapenergy** [comment]
Thanks Gabriele.  First I'm using a fairly-recent version of jScope on Windows 10.

I had to do the following (use [ ] rather than ( ) for the _s definition) to NOT get the error "TDI-E-BAD_INDEX, index or subscript is too small or too big":

![image](https://user-images.githubusercontent.com/60521693/227052927-d531500a-f953-4c1e-bce6-1f4e191409b2.png)

with the image setup:

![image](https://user-images.githubusercontent.com/60521693/227052461-2a0a6750-a067-4452-bfa1-7e83e6b1440b.png)

and color setup (0.0 to 1000.0):

![image](https://user-images.githubusercontent.com/60521693/227052554-6d1e5495-d24c-41d1-8772-8acac7fe36cc.png)

BUT it is monochromatic:

![image](https://user-images.githubusercontent.com/60521693/227052594-6bbd7747-3c02-4c47-9220-31e5ad7c4af1.png)

Any ideas?

**Comment by GabrieleManduchi** [comment]
Don't check IS_IMAGE toggle button in Setup form.   IS_IMAGE is checked only for sequences of frames in which case the matrix has 3 dimensions (ehm, yes...the name is a bit misleading)
I understand you are showing a **single**image.

**Comment by GabrieleManduchi** [comment]
...and the popup menu select Signal2d->Plot Image

**Comment by nelson-zapenergy** [comment]
Great, thanks!

Looks like the lineout feature doesn't work for the "signal2d" option, is that correct?

**Comment by nelson-zapenergy** [comment]
Ah, I understand how it works now, thanks!  Closing Issue #2546.
