### ISSUE TITLE
Incorrect JAVASOURCE in Makefile.am?

### ISSUE THREAD

**Issue by mdclemen** [MDSplus/mdsplus#2560]
**Affiliation**
Mitchell Automation LLC

**Version(s) Affected**
mdsplus-stable_release-7-132-0

**Platform**
Fedora 37

**Describe the bug**
[java/mdsobjects/Makefile.am](https://github.com/MDSplus/mdsplus/blob/alpha/java/mdsobjects/Makefile.am) and [java/mdsplus/Makefile.am](https://github.com/MDSplus/mdsplus/blob/alpha/java/mdsplus/Makefile.am) set `JAVASOURCE = 6`, which for me, when building from source and following the directions from (https://mdsplus.org/index.php/Software:BuildingFromSources), resulted in an error saying that `JAVASOURCE = 6` was outdated. I manually updated these files to `JAVASOURCE = 8`, and the build worked.

**To Reproduce**
Build the latest stable source using the directions from: https://mdsplus.org/index.php/Software:BuildingFromSources

**Expected behavior**
A build with no errors.

**Comment by santorofer** [comment]
Could you let us know explicitly the error message that you are seeing?. The error appears when running 'make', I assume.

**Comment by zack-vii** [comment]
JAVASOURCE was used to maintain backward compatibility for matlab (javamds, mdsobjects, and co) while also supporting newer modules such as mdsapi and jtraverser2. it may nor work with newer java versions. however we built with jdk8 (platform independdant). i you wish to build with a newer java version 
`make JAVASOURCE=8` may indeed do the trick. some projects also support maven. however, maintaining the java buildchain for all distributions was dropped a good while ago. i would not say its a bug or that JAVASOURCES=6 os incorrect, but simply that your jdk does not suppport the intended compatibility or the way we attempt to achive the compatibility does not support your jdk version.

best may be to download the compiled jars and only compile the binaries.

**Comment by mdclemen** [comment]
> Could you let us know explicitly the error message that you are seeing?. The error appears when running 'make', I assume.

This is where compilation failed for me:
```
CLASSPATH=./classes: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64/bin/javac -d ./classes  -encoding UTF-8 -source 6 -target 6   src/main/java/MdsPlus/MdsPlusDescriptor.java src/main/java/MdsPlus/MdsPlusEvent.java src/main/java/MdsPlus/MdsPlusEvents.java src/main/java/MdsPlus/MdsPlusException.java src/main/java/MdsPlus/MdsPlus.java
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
make[1]: *** [Makefile:588: classjava.stamp] Error 2
make[1]: Leaving directory '/home/mitchell/PROJECTS/mdsplus-stable_release-7-132-0/java/mdsplus'
make: *** [Makefile:104: java/mdsplus] Error 2
```
I'd like to also note that `JAVASOURCE = 8` is hard coded in a  bunch of other Makefiles:
```
mdsplus-stable_release-7-132-0]$ grep -rin 'JAVASOURCE = ' ./*
./java/jtraverser2/Makefile.am:1:JAVASOURCE = 8
./java/jtraverser/Makefile.am:1:JAVASOURCE = 8
./java/jscope/Makefile.am:1:JAVASOURCE = 8
./java/devicebeans/Makefile.am:1:JAVASOURCE = 8
./java/jdevices/Makefile.am:1:JAVASOURCE = 8
./java/jdispatcher/Makefile.am:1:JAVASOURCE = 8
./java/mdsobjects/tests/Makefile.am:1:JAVASOURCE = 8
./java/mdsobjects/Makefile.am:1:JAVASOURCE = 6
./java/mdsplus-api/tests/Makefile.am:1:JAVASOURCE = 8
./java/mdsplus-api/Makefile.am:1:JAVASOURCE = 8
./java/tests/Makefile.am:1:JAVASOURCE = 8
./java/mdsplus/Makefile.am:1:JAVASOURCE = 6
```

**Comment by santorofer** [comment]
mdclemen, could you use `make` with the modifier that Timo explained about?, i.e.:

`make JAVASOURCE=8`

will that avoid the errors that you see?

**Comment by mdclemen** [comment]
@santorofer using `make JAVASOURCE=8` works without errors.

**Comment by santorofer** [comment]
Excellent.
