### ISSUE TITLE
numpy deprecation warning for .tostring()

### ISSUE THREAD

**Issue by pfbuxton** [MDSplus/mdsplus#2589]
Hello,

Numpy is warning that `.tostring()` is a deprecated.

Here is the warning:
```terminal
  /tmp/mdsplus-stable/python/MDSplus/mdsscalar.py:437: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
    return cls(_N.array(_C.cast(d.pointer, _C.POINTER((_C.c_byte*d.length))).contents[:], dtype=_N.uint8).tostring())
```
the line which is causing the issue is here: [mdsscalar.py#L437](https://github.com/MDSplus/mdsplus/blob/alpha/python/MDSplus/mdsscalar.py#L437).

I am using:
```terminal
numpy                           1.24.3
MDSplus                         7.132.0
```

Here is the [numpy documentation](https://numpy.org/devdocs/reference/generated/numpy.ndarray.tostring.html), which states **"Despite its name, it returns bytes not strs."**, so it's not surprising that it has been deprecated, and changing to `tobytes()` should produce exactly the same results.

**Comment by mwinkel-dev** [comment]
This issue from Tokamak Energy is probably on the stable branch (implied by version 7.132.0 listed in the bug report).

Was able to replicate the problem on Ubuntu 20.04 using a current build of MDSplus alpha (~7.139.17), numpy 1.24.3, python 3.8.10 and PYTHONWARNINGS=default.   And also confirmed that replacing tostring() with tobytes() eliminates the warning.   Will submit a PR soon.

**Comment by mwinkel-dev** [comment]
And here is an example of how to trigger the warning.

```
#
# Simple program to illustrate Issue #2589.
# Install NumPy 1.19.0 or later.
# And set environment variable PYTHONWARNINGS=default.
#

import MDSplus as mds

# This refers to a C-Mod shot and subtree
shot = 1160422016
tree = mds.Tree("engineering", shot)

node = tree.getNode("cryo_plc.after:EF1L_RC")
data = node.getData()

print()

# This statement triggers the warning about tostring() being deprecated
print("data = ", data)

print("type = ", type(data))
print()
```

**Comment by pfbuxton** [comment]
Great to hear that you were able to replicate the issue!
