### ISSUE TITLE
website documentation for ubuntu / debian

### ISSUE THREAD

**Issue by dgarnier** [MDSplus/mdsplus#2633]
On this page:

https://mdsplus.org/index.php/Latest_Ubuntu/Debian_Packages

It is suggested that one adds a signing key like this:

`sudo apt-get -y install curl gnupg && curl -fsSL http://www.mdsplus.org/dist/mdsplus.gpg.key | sudo apt-key add -`

This is deprecated.

Instead it should be:

`sudo apt-get -y install curl && curl -fsSL http://www.mdsplus.org/dist/mdsplus.gpg.key | sudo tee /etc/apt/trusted.gpg.d/mdsplus.asc > /dev/null`

**Comment by joshStillerman** [comment]
Thanks -
  Fixed
