### ISSUE TITLE
Can I compose a tree to have physical subtrees with different shot numbers?

### ISSUE THREAD

**Issue by fluffynukeit** [MDSplus/mdsplus#2651]
**Affiliation**
Zap Energy

**Question**
I am interested in creating a collection of physical subtrees, each with their own (possibly different) shot numbers, and putting them in a parent tree with its own shot number.  My motivation is that I would like to associate a physical tree with each subsystem in our device so that an experimental sequence can be run for just that subsystem by dispatching to just that physical tree while also allowing running sequences on sets of subsystems through the parent tree.

One way that this would almost work is to have a parent tree that contains physical subtree nodes.  I can open a subtree S, create a pulse file for it, and run the sequence.  It will get a shot number, say S_1.  I could then open the parent tree, create a pulse (which creates a pulse for all the subtrees be default), and dispatch across the parent pulse.  The shot number for the parent pulse and all the physical subtrees it created would be 1, so P_1 and S_1.   The S_1 file would collide with the subtree-only sequence file S_1 done just prior.  What I would like to happen is for parent pulse P_1 to create and have a subtree reference to subsystem pulse S_2, not S_1.

As far as I can tell through experimentation and some code inspection, this is not possible.  A subtree reference always uses the same shot number as its parent.  Is that true?  Are there any ways to create a tree that has a shot number that is distinct from the shot numbers of its subtrees?

If not, the alternative I can see possibly working is to manually create pulses for each physical subtree that each have their own shot numbers, then create a pulse file for the parent that has its own shot number but explicitly EXCLUDE all physical subtrees, then do some kind of _path and symlink game where I create symlinks with parent shot numbers that point to the files of subtree shot numbers.  So something like P_1 contains a subtree reference to PS_1, and in the file system there is a symlink PS_1 -> S_2.

I have also read in papers that some facilities create their own shot numbering association system that is distinct from MDSplus.  The reason I want to do the association in MDSplus is that I want jScopes and jTraverser and everything else in the ecosystem to work when accessing a parent tree.  Thanks.

**Comment by joshStillerman** [comment]
Daniel -
  I am not exactly sure I understand what you are trying to accomplish.  A few thoughts:
You can open a tree without (or with a limited set of) its subtrees by providing a comma list for the tree name.
For just one top tree tree name,XX will do it
You can copy or link the 3 files treename_shotnumber.* to any three filenames treename_other-shot-number.* or even new-tree name_other-shot-number.* And you will then have the new shot number or name
You can use a .fun file to generate parts of the tree path computationally (I would have to look up the syntax for this)
In general what we did at C-Mod was to:
Assign a range of test shot numbers for each subsystem either:
Yymmdd1xx, 2xx, ...
1000, 2000, …
When we wanted to run more than one subsystem we either did
Set tree  "cmod,sub1,sub2,…”
Create pulse <shot-number>
Set tree mod
Set node .sub3 /noinclude
Set create pulse <shot-number>
There are probably other games that you could play. 
We do not have a shot number qualified subtree reference.  Maybe we should?  Have to think about that
So some of the above refers to the filename games you describe below.  I would think that this will be pretty confusing though.  One way that you could simplify those games is by having a separate directory in your tree_path that contains the trees composed of symlinks.  If you can play those filename/simlink games then you have some unused shot number that all of the subsystems could use ?  

We would be happy to discuss all of this with you.  Maybe discord ?

-Josh

**Comment by fluffynukeit** [comment]
Sure, I will look for you on discord.

**Comment by fluffynukeit** [comment]
Here is a summary of my discussion of this issue with Josh.  The best approach to my problem is to have separate shot number conventions for the individual subsystem pulse and the subsystem-as-a-part of the parent pulse.  For instance, in our case our shot number convention is YYMMDDNNN for the parent pulse.  To run a pulse for just a single particular subsystem tree, we would institute a different shot number convention that is easily distinguished from the shot number used for a parent pulse.  One constraint is that a shot number is currently a 32 bit integer, so the highest number is 4,294,967,295.  For example, a single subsystem pulse could be YYMMDDNNNN (four digits N for the day's shot sequence number instead of 3).  This pulse would exist for only the subsystem tree; it would not be a pulse of the parent tree.  One thing to watch out for would be doing any filtering of the shot number by date range because the potential extra digit would need to be accounted for.

This would not support creating distinct shot number conventions using an arbitrary collection of subsystems.  Specifically, we could disable or enable different subtrees in the parent, but the parent's shot number would still follow the convention YYMMDDNNN.  There is no mechanism for the parent tree to have a different shotnumber than a subtree.
