### ISSUE TITLE
Executing connection.get("_output") returns KeyError: 0 error

### ISSUE THREAD

**Issue by hjx777** [MDSplus/mdsplus#2665]
**Affiliation**
USTC

**Question**
Use python to access directories at all levels of the mdsplus tree. When obtaining the second layer signal list, the terminal returns the following error:

Traceback (most recent call last):
  File "/tmp/pycharm_project_656/mdsdatainfo_v0.1/eastexperimentinfo.py", line 109, in <module>
    getShotData(shot_number)
  File "/tmp/pycharm_project_656/mdsdatainfo_v0.1/eastexperimentinfo.py", line 54, in getShotData
    print(connection.get(tcl3))
  File "/root/anaconda3/envs/readfile/lib/python3.10/site-packages/MDSplus/connection.py", line 254, in get
    ans = self.__getAnswer__()
  File "/root/anaconda3/envs/readfile/lib/python3.10/site-packages/MDSplus/connection.py", line 110, in __getAnswer__
    ans=Connection.dtype_to_scalar[dtype](_C.cast(ans,_C.POINTER(_dtypes.mdsdtypes.ctypes[dtype])).contents.value)
KeyError: 0
MDSPlus dependent libraries are installed through anaconda, mdsplus7.7.15.

The functions in the code are implemented through tcl instructions and are executed normally when displaying the first-level directory, but the second-level subtree cannot be accessed normally. I would like to ask why. Previously, MdsValue() provided by c++ could be accessed normally.

```
import MDSplus.connection
from MDSplus import mdsExceptions
import MDSplus.tree
import MDSplus.mdsdata
def getShotData(shot_number):
    try:
        connection = MDSplus.connection.Connection("127.0.0.1")
        connection.openTree("east", shot_number)
        treeid = 1
        tcl1 = f"TCL(\"set def t{treeid}\",_output)"
        status = connection.get(tcl1)
        if status & 1 == 1:
            tcl2 = "TCL(\"dir\",_output)"
            status = connection.get(tcl2)
            if status & 1 == 1:
                tcl3 = "_output"
**# this print not work**
                print(connection.get(tcl3))
            else:
                print(f"open t{treeid} siglist error")
        else:
            print(f"open t{treeid} tree error")
    except mdsExceptions.MDSplusException as e:
        print(f"Error: Failed to open tree for shot {shot_number}. Reason: {e}")
```

**Comment by mwinkel-dev** [comment]
Hi @hjx777 -- I'm curious what the solution was to your problem.   (If the problem still exists, we should reopen this GitHub issue.)

**Comment by hjx777** [comment]
> Hi @hjx777 -- I'm curious what the solution was to your problem. (If the problem still exists, we should reopen this GitHub issue.)

This code itself can run normally. The error occurred because I forgot to consider that some subtrees have no next-level content. You can see that treeid is set to 1. This error disappears when switching other values. I completely forgot about this question when I asked the question. I suddenly remembered it later and confirmed that the code was error-free.

**Comment by mwinkel-dev** [comment]
Hi @hjx777 -- Thanks for the explanation.   Much appreciated.
