### ISSUE TITLE
Ubuntu 22 build Makefile error

### ISSUE THREAD

**Issue by ghost** [MDSplus/mdsplus#2697]
**Affiliation**
SNU NUPLEX

**Version**
Ubuntu 22 
autoconf 2.69
automake 1.15.1

**Question**
What is your question?
I'm trying to build the file using docker but it keeps fail and I couldn't find the way to solve this problem while still using docker

> config.status: creating include/mdsplus/mdsconfig.h
> config.status: executing depfiles commands
> Makefile.inc:181: *** missing separator.  Stop.
> 79b3d61a253c58d7fe22d60b6cdb6b6fdebede6a01db50540179208ed825b4
> ======================================================
> 
> Docker debian_docker_build.sh returned failure
> status when exiting from mdsplus/builder:ubuntu22-64
> 
> ======================================================
> ============================================
> 
> Failure: The build was unsuccessful!
> 
> ============================================

These are the last few comments when I enter "../deploy/build.sh --os=ubuntu22 --release" . (I also tried with some other options such as sudo ../deploy/build.sh --os=ubuntu22 --branch=alpha --release=7.139.61/ sudo ../deploy/build.sh --os=ubuntu22 --release=7.139.61)
Checking the Makefile.inc by using ./configure comment, the error happens on this line. 

> 180 ## git release tags
> 181 @AX_GIT_REVISION_TARGETS@ 

And I couldn't find any solution that could help.

**Comment by ghost** [comment]
Before this error I added some code in configure.ac file 

> configure.ac:9: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> configure.ac:12: error: possibly undefined macro: AS_VAR_SET
> configure.ac:18: error: possibly undefined macro: AM_INIT_AUTOMAKE
> configure.ac:19: error: possibly undefined macro: AM_MAINTAINER_MODE
> configure.ac:79: error: possibly undefined macro: AM_CONDITIONAL
> configure.ac:95: error: possibly undefined macro: AC_MSG_RESULT
> configure.ac:134: error: possibly undefined macro: AS_VAR_TEST_SET
> configure.ac:139: error: possibly undefined macro: AM_COND_IF
> configure.ac:167: error: possibly undefined macro: AC_CHECK_JAVA_HOME
> configure.ac:196: error: possibly undefined macro: AC_MSG_WARN
> configure.ac:652: error: possibly undefined macro: AC_SEARCH_READLINE
> configure.ac:712: error: possibly undefined macro: AM_PATH_XML2
> configure.ac:1049: error: possibly undefined macro: AS_ECHO

These were the error lines when I type autoconf as described in mdsplus site. 

> docs/config/doxygen.am:35: error: DX_COND_doc does not appear in AM_CONDITIONAL
> docs/Makefile.am:3:   'docs/config/doxygen.am' included from here
> docs/config/doxygen.am:41: error: DX_COND_html does not appear in AM_CONDITIONAL
> docs/Makefile.am:3:   'docs/config/doxygen.am' included from here
> docs/config/doxygen.am:51: error: DX_COND_man does not appear in AM_CONDITIONAL
> docs/Makefile.am:3:   'docs/config/doxygen.am' included from here
> docs/config/doxygen.am:62: error: DX_COND_pdf does not appear in AM_CONDITIONAL
> docs/Makefile.am:3:   'docs/config/doxygen.am' included from here
> docs/config/doxygen.am:91: error: DX_COND_latex does not appear in AM_CONDITIONAL
> docs/Makefile.am:3:   'docs/config/doxygen.am' included from here
> .
> .
> .
> testing/selftest/Makefile.am:49: error: ENABLE_VALGRIND does not appear in AM_CONDITIONAL
> treeshr/testing/../../testing/testing.am:75: error: ENABLE_SANITIZE does not appear in AM_CONDITIONAL
> treeshr/testing/Makefile.am:3:   'treeshr/testing/../../testing/testing.am' included from here
> treeshr/testing/../../testing/testing.am:103: error: ENABLE_SANITIZE does not appear in AM_CONDITIONAL
> treeshr/testing/Makefile.am:3:   'treeshr/testing/../../testing/testing.am' included from here

And I also got this error messages when I type automake 

So I just added AC_CONFIG_MACRO_DIRS([m4]) to configure.ac file and type aclocal, autoconf, automake.
I don't think this would effect the above situation but isn't configure.ac file should have this line "AC_CONFIG_MACRO_DIRS([m4])"? Or mdsplus[https://www.mdsplus.org/index.php?title=Software:BuildingFromSources&open=110662451143527432703&page=Software%2FBuilding+from+sources](url) should add aclocal? (I didn't use homebrew to install the autoconf and automake file I just use apt install and some librearies like autoconf-archieve and some source file for automake and autoconf to get specific version.

**Comment by mwinkel-dev** [comment]
Hi @sjleefg02,

Let's see if we can get your Docker build to work.   (I just used Docker to build MDSplus for Ubuntu 22.04 and it worked fine.)  Try the following steps.

```
$
$ # Make a new directory (so we don't mess up your existing work).
$ # This example uses "/tmp/new_repo", but you can use any path you wish.
$ mkdir /tmp/new_repo
$ cd /tmp/new_repo
$ git clone https://github.com/MDSplus/mdsplus.git
$
$ # Check to make sure the status command shows on the "alpha" branch 
$ cd mdsplus
$ git status
$ 
$ # Now create a build directory and build with Docker
$ cd /tmp/new_repo
$ mkdir build
$ cd build
$ ../mdsplus/deploy/build.sh --os=bootstrap
$ ../mdsplus/deploy/build.sh --os=ubuntu22 --release
$
$ # The debs will be found at this location (assuming you are building for x86_64)
$ cd /tmp/new_repo/build/build/ubuntu22/alpha/release/Ubuntu22/alpha/DEBS/amd64
$
$ # And if you want to instead create a tarball, then tar this directory
$ cd /tmp/new_repo/build/build/ubuntu22/alpha/releasebld/buildroot/usr/local/mdsplus
```

The above process is how I manually build the current alpha using Docker.   It should work for you too.

Regardless, let us know if this solved your problem or not.

**Comment by satelite2517** [comment]
Hello This is just my another account with sjleefg02 and I just success with building the current alpha version! Thank you so much!! 👍👍 :)

**Comment by mwinkel-dev** [comment]
Hi @sjleefg02 / @satelite2517,

You're welcome.

And congratulations!   I am glad to read that you were able to get the Docker build of alpha to work for Ubuntu 22.

Because your build was successful, I am closing this issue.

-Mark

P.S. -- We are finishing some maintenance work on our build server.   So in the near future, you will once again be able to download pre-built binaries (i.e., "deb" packages)  from the MDSplus web site (and also from GitHub).
