### ISSUE TITLE
MDSplus tries to use OFD locks on systems that do not support it

### ISSUE THREAD

**Issue by joshStillerman** [MDSplus/mdsplus#2725]
**Affiliation**
MIT PSFC

**Version(s) Affected**
MDSplus version: 7.139.67
----------------------
  Release:  alpha_release_7.139.67
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release_7.139.67
  Download: https://github.com/MDSplus/mdsplus/archive/alpha_release_7.139.67.tar.gz

while this version is fine:

MDSplus version: 7.112.1
----------------------
  Release:  alpha_release_7.112.1
  Browse:   https://github.com/MDSplus/mdsplus/tree/alpha_release_7.112.1
  Download: https://github.com/MDSplus/mdsplus/archive/alpha_release_7.112.1.tar.gz

**Platform**
RHEL6

**Describe the bug**
I built the current alpha for RHEL6.  Things appeared to work.  A user reported that there was a complaint about OFD locks when he did a `create pulse`

**Comment by zack-vii** [comment]
The corresponding line to decide would be here.
https://github.com/MDSplus/mdsplus/blob/a8b4e01560da8a262f9b0bfa8af3b54af959c590/treeshr/RemoteAccess.c#L1563
however, I did not find a reliable way to check if it is supported. It is highly recommended to work on a system with ofd support, as one would have to lock the entire file or implement a handmade locking mechnism that work in between processes. I was fiddling with something like that that would at least allow to safely append. however, it newer worked reliably in all enviroments.
As you can see here
https://github.com/MDSplus/mdsplus/blob/a8b4e01560da8a262f9b0bfa8af3b54af959c590/treeshr/RemoteAccess.c#L1574
it is just a warning once before turning off the feature.

**Comment by joshStillerman** [comment]
Thanks!    I will test.  I reported it when a user complained that his program was / is failing.  If worse comes to worse we could add a build switch for it. Though systems that do not support it are really really old. Sadly I have one.
