### ISSUE TITLE
Missing "mdsobjectscppshr-vs.lib" in vs devtools lib32 folder

### ISSUE THREAD

**Issue by rdeng23** [MDSplus/mdsplus#2739]
**Affiliation**
Hello, Here's Rui from SWIP, we are uing mdsplus 7.131-5

**Question**
I am trying to build applications based on vs-studio, I can find mdsobjectscppshr-vs.lib file in lib64 folder and it works fine, but I can not find the file in lib32, so I can not build applications for 32bit systems.
Can anyone could tell me where to get the 32bit file, or share me one?

Thank you very much!

**Comment by mwinkel-dev** [comment]
Hi @rdeng23 -- Just a quick note to acknowledge receipt of your post.

Some additional information would be helpful.
- Which operating system are you using?   And what version of the operating system?
- Regarding the MDSplus version, I gather that you are using `stable 7.131-5` (and not `alpha`), correct?

**Comment by rdeng23** [comment]
> Hi @rdeng23 -- Just a quick note to acknowledge receipt of your post.
> 
> Some additional information would be helpful.
> 
> * Which operating system are you using?   And what version of the operating system?
> * Regarding the MDSplus version, I gather that you are using `stable 7.131-5` (and not `alpha`), correct?

Hi @mwinkel-dev ,
Thank you very much for your quick response

I am using Windows 10 64bit, Visual Studio 2022, trying to build client application(c++) which need to access our mdsplus database。And yes I am using stable 7.131-5 mdsplus version.

When I finished installing, I can find mdsobjectscppshr-vs.lib file in the lib64 folder of installation path of mdsplus, but the 32bit file is not in the lib32 folder.

Here we have many different types of devices, So I need to provide both 32bit application and 64bit application. But now I can only make the 64bit application because I do not have the 32bit mdsobjectscppshr-vs.lib file.

I'm not sure if I am using this lib right, or it is actually missing the file in lib32 folder?
![image](https://github.com/MDSplus/mdsplus/assets/154024307/e839d9f8-4eb2-4a91-b605-59d2951b5b74)

**Comment by mwinkel-dev** [comment]
Hi @rdeng23,

I just observed the same problem on my Windows 10 dev system (which presently has the older `stable_7.50.1` installed).

If you look at the `devtools\lib32\mingw` directory, you will see a `mdsobjectscppshr.lib` file.  Although that isn't the file that you need for Visual Studio, it does indicate that the build system is building 32-bit libs for the `mdsobjects*`.

Current conjecture is that the missing file is either not being built, is not being included in the installer or is ignored by the installer.  Regardless, it looks like an issue with our build system / scripts.

I am currently doing a build of MDSplus for Windows to investigate the issue.  I will post an update here later today or early tomorrow.

**Comment by mwinkel-dev** [comment]
Hi @rdeng23,

Answer is that the build system is presently not building a 32-bit version of `MdsObjectsCppShr-VS.lib`. Therefore, I am upgrading your inquiry to a bug.

It will likely take a day or two to fix the build script.  We can then manually do a build of `stable_7.131.5` and provide the missing 32-bit *.lib file.

**Comment by mwinkel-dev** [comment]
Hi @rdeng23,

Visual Studio is quite flexible.  If you already have the `mingw` toolchain installed on your computer, Visual Studio can probably use the `devtools\lib32\mingw\MdsObjectsCppShr.lib` file.   A web search will yield some articles regarding using `mingw` with Visual Studio.

Regardless, we'll fix this bug regarding the missing 32-bit *.lib file.

**Comment by rdeng23** [comment]
@mwinkel-dev ,
Thank you so so so much for your support! This indeeed gives me tons of help!!!!
