### ISSUE TITLE
errors importing MDSplus with numpy 2.x

### ISSUE THREAD

**Issue by rcavazz** [MDSplus/mdsplus#2793]
with the new python version I got this error:
File "/usr/local/mdsplus/python/MDSplus/version.py", line 34, in <module>
    from numpy import string_ as npbytes
ImportError: cannot import name 'string_' from 'numpy'

reason:
string_ and unicode_ have been removed in numpy 2.x

I came up with this quick fix in version.py:
```
# from numpy import string_ as npbytes
from numpy import bytes_ as npbytes
# from numpy import unicode_ as npunicode
from numpy import str_ as npunicode
```

probably should be refactored to maintain some back compatibility.

**Comment by alkhwarizmi** [comment]
Same on my side, I also had to manually do those changes in 7.142-80.

Cheers!
