### ISSUE TITLE
Stable 7.142.80, Windows: server does not accept incoming conenctions (Attempting to duplicate socket from pid 8660 socket 380)

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#2794]
**Affiliation**
Eurac Research / Institute for Renewble Energy

**Version(s) Affected**
Server and client version: Stable 7.142.8

**Platform(s)**
Windows 10 Enterprise

**Installation Method(s)**
Installer downloaded from mdsplus.org repository

**Describe the bug**
After upgrade from Stable 7.50 to Stable 7.142.80 the server does not accept incoming conenctions any more.

**To Reproduce**
1. Locally on the server trying to connect to 127.0.0.1 with the jTraverser
Also
2. Trying to connect to the server via jTraverser from another machine 

**Additional context**
1. Installation of 7.142.80 was not seamless because the 7.50 uninstaller did not remove files from the system folders C:\Windows\System32 and C:\Windows\SysWOW64. We removed manually the files to allow the installer to proceed. Later we uninstalled 7.142.80 and re-installed it again without errors.
2. As noticed we need both 64 and 32 bit version of the libraries because we integrate MDS+ in LabView and we are stuck with a certain hardware version requiring 32-bit.
3. We installed the server as a service with the provided very handy script and verified the service is working.
4. We are using a customized version of mdsip.hosts which has not been changed by the installer and was not giving problems in the past years.
5. The following files are created/updated upon connection attampts
    a. MDSIP_8000.log (a new identical line is added every time we try to connect)
       `CreateProcess returned 1 with cmd=mdsip.exe --port=8000 --hostfile="C:\mdsip.hosts" --compression=0 --sockethandle=8660:380`
    b. MDSIP_8000_xxxx.log (a new files appears with this content every time we try to connect)
        `Error duplicating socket from parent: No error`
        `Attempting to duplicate socket from pid 8660 socket 380`
6. Inbound rules for TCP and UDP port 8000 were already there and have not been changed
7. Access to the trees locally via jTraverser and Python Tree class seems to be working using python 311
8. Had to modify  string_ to bytes_ and unicode_ to str_ in version.py to make MDSplus package loadable

The matter is extremely critical because this is our production server.

Cheers,

**Comment by alkhwarizmi** [comment]
Sorry, the line is not identical, because the socket number changes.

I also tested this locally on my PC, Windows 10, MDSplus version  Stable 7.132.0 with the same results.

MDSIP_8000.log
```
CreateProcess returned 1 with cmd=mdsip.exe --port=8000 --hostfile="C:\mdsip.hosts" --compression=0 --sockethandle=59296:392
CreateProcess returned 1 with cmd=mdsip.exe --port=8000 --hostfile="C:\mdsip.hosts" --compression=0 --sockethandle=59296:428
CreateProcess returned 1 with cmd=mdsip.exe --port=8000 --hostfile="C:\mdsip.hosts" --compression=0 --sockethandle=59296:432
```
MDSIP_8000_49172.log
```
Error duplicating socket from parent: No error
Attempting to duplicate socket from pid 59296 socket 428
```

Is it possible that [this thread](https://stackoverflow.com/questions/70368504/duplicate-windows-sockets-between-unrelated-processes) is relevant.

Cheers,

**Comment by mwinkel-dev** [comment]
Hi @alkhwarizmi,

Thanks for the bug report.   I will install the software on my Windows 10 virtual machine and see if I can reproduce the problem.

It appears to me that there are some typos in the bug title and report regarding the version numbers.   Am I correct that these are the versions used?
- stable 7-142-80
- stable 7-132-0

-MarkW

P.S. -- July 4 is a holiday in the U.S.   Thus, the next full work day is Monday July 8.

**Comment by alkhwarizmi** [comment]
Now I reverted back the server to 7.50-0 so I can't run the mdstcl command for getting the version, however I can confirm that I made typos in the report, the version is 7.142-80 which I am going to correct if I can. Regarding my PC instead ...
```
C:\>mdstcl show version


MDSplus version: 7.132.0
----------------------
  Release:  stable_release_7.132.0
  Browse:   https://github.com/MDSplus/mdsplus/tree/stable_release_7.132.0
  Download: https://github.com/MDSplus/mdsplus/archive/stable_release_7.132.0.tar.gz
```

**Comment by mwinkel-dev** [comment]
Hi @alkhwarizmi -- Thanks for the clarification.   That will enable me to create a similar configuration on my dev systems.

**Comment by mwinkel-dev** [comment]
Hi @alkhwarizmi -- My manager just succeeded in reproducing the problem you encountered with stable-7-142-80 on Windows 10.

**Comment by alkhwarizmi** [comment]
> Hi @alkhwarizmi -- My manager just succeeded in reproducing the problem you encountered with stable-7-142-80 on Windows 10.

Good, in the mean time I reverted back to 7.50. When this gets solved and reaches into stable I will try again to update the PXI server. I can also try out on my laptop an alpha distribution.

Thankyou, very much appreciated.

**Comment by joshStillerman** [comment]
This should now be resolved
