### ISSUE TITLE
Does MDS+ have Multiplexed Persistent Connection TCP/IP Capabilities

### ISSUE THREAD

**Issue by wdeshazer** [MDSplus/mdsplus#2811]
**Affiliation**
General Atomics

**Issue/Observation**
For some use cases we are experiencing a lot of MDS+ connections and are oversubscribing our system. I would like to have all sessions reuse the same Multiplexed TCP/IP connection for the multiple instances or open new connections based on Connection bandwidth not new application instances. 

**Question**
Does MDS+ already have the capability to create and reuse persistent TCP/IP connections? 

In SSH a multiplexed socket is created through the ControlMaster, ControlPath, ControlPersist API. I am hoping for a similar functionality.

**Comment by mwinkel-dev** [comment]
Hi @wdeshazer -- I'm pretty sure that MDSplus does not have that capability.   Later today, I will check with my manager and post an additional response here.

**Comment by joshStillerman** [comment]
Mark is correct!

MDSplus does have shared servers but that implies shared context (tree open, set_default, etc...) so this is not a solution.  mdsip is a process local connection.  It does (or did) recognize that there is already a connection if there is one and reuse it.  This is/was problematic for multi threaded applications, since incoming packets potentially ended up in the wrong thread.  This was further exasperated by python threads not really being threads as far as the OS is concerned.

When you say 'overwhelmed' -  if xinetd or systemd are limiting the number of connections then they can tweak the knobs.  If the OS is limiting the number of processes they can tweak those knobs.

**Comment by zack-vii** [comment]
This is all true, however, we have the tunnel protocol which is also used for ssh. It work with stdin and out and can be used to wrap any bidirectional communication, c.f. https://github.com/MDSplus/mdsplus/blob/alpha/mdstcpip/mdsip-client-ssh
So technically you should be able to use it to implement any kind of multiplexed connection as long as you handle the multiplexing in the carrier protocol. Furthermore the mdsip allows you to add any kind of protocol to dynamically be loaded.
c.f. https://github.com/MDSplus/mdsplus/blob/alpha/mdstcpip/mdsipshr/LoadIo.c

I dont know for sure but i can imagine a suitable carrier protocol already exists, we just did not provide out of the box support for it yet. If you want to explore the possibilities a bit, let us know if you find a elegant solution to your problem and maybe let others benefit form it through a merge request. Maybe someone may even be able to help and join you half way there.

**Comment by wdeshazer** [comment]
Thank you for thinking about this and for weighing in. Sean Flannaghan and I digested your response together. The links were very helpful. One thing that would have helped you, even though you seem to understand the question, is some background, which I put at the end of this coment. I will edit the opening question later.

To keep the discussion moving forward, it looks like [mdsthin](https://github.com/MDSplus/mdsthin) exposes the ssh client features. That means we get multiplexing out of the box if all of the ssh API has been exposed in the thin client.

Additionally, SLURM provisions the options for managing the number of sockets to resource:
--cores-per-socket
--gpus-per-socket
--ntasks-per-socket

With a combination of these capabilities, Sean Flannagan and I think that we reduce the number of tcp/ip connections and its associated overhead.

**Questions:**
1) In your opinion overall do you see or know of barriers to using multiplexed-persistent sockets? You mentioned the [mdsip not recognizing the existing connection](https://github.com/MDSplus/mdsplus/issues/2811#issuecomment-2391604098). I think that the ssh Control API addresses this issue, we will try it and see.
2) Does that seem like it would be a significant performance opportunity? I am asking based on technical judgement to see if it is worth collecting the actually statistics
3) What similar things could we do on the MDS Client-Server interaction that would take a big  request and make it as optimized as reasonably possible?

I should have put the background in the opening question, but ...

**Background**
One of our users parallelized their mdsplus request for ~100000 shots and made a flash spawning of tcp/ip connections and taxed our server. We are using this issue to revisit the infrastructure of our tools and ensure that by default  they limit the number of connections to a reasonable (as yet to be determined) amount.

**Assessment Plan**
Sean and I came up with the approach of taking the exact use-case and implement the improvements that come from this Issue to quantify them. I am personally optimistic that this will be a really beneficial and possibly eye-opening exercise.

**Comment by mwinkel-dev** [comment]
Hi @wdeshazer -- Thanks for the additional detail.   I've alerted the rest of the team to this new information.
