### ISSUE TITLE
MDSplus python returns an incorrect string class type when loading a list of strings

### ISSUE THREAD

**Issue by jdelder** [MDSplus/mdsplus#374]
Save a list of strings to MDSplus and then load it. The join function works fine on the original list but has a type mismatch of string vs String on the list returned by MDSplus. One workaround is to type cast the MDSplus return value to str. 

e.g. Adding this line between the getData() and the join in the example below lets the code work. 
d = [str(s) for s in d]

> > > c=['1','test','2','this is a']
> > > print ":".join(c)
> > > 1:test:2:this is a
> > > a.putData(c)
> > > d=a.getData()
> > > print d
> > > ["1", "test", "2", "this is a"]
> > > print ":".join(d)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: sequence item 0: expected string, String found

**Comment by tfredian** [comment]
You are correct. a.getData() is returning a List instance containing String instances. You do have to convert them to str instances if you want to use join. The only solution I could imagine other than the one you found would be to add something like a tostr() method for a List object. I think your solution is probably sufficient. It is the str objects method that requires a particular type of input variable so there is not much that can be done on the MDSplus side to fix this. Too bad the join method of str doesn't try to convert the elements of the list to str itself.
