### ISSUE TITLE
servershr/ServerSendMessage.c: Uninitialized var used

### ISSUE THREAD

**Issue by kgerickson** [MDSplus/mdsplus#471]
In servershr/ServerSendMessage.c, ServerSendMessage(), jobid is declared at line 144 and used on line 173 in an sprintf command whether or not it has been initialized on line 170.  It is conditionally set based on the value of addr.  jobid should be defined to be an invalid value so that in the case where addr is not set, the sprintf yields defined results.  Further, better handling is needed in the case that addr is zero.

**Comment by tfredian** [comment]
FIxed

**Comment by kgerickson** [comment]
Thanks!
