### ISSUE TITLE
treeshr/TreeGetRecord.c use of uninit status

### ISSUE THREAD

**Issue by kgerickson** [MDSplus/mdsplus#482]
In TreeOpenDatafileR(), status will be returned as an undefined value if TreeGetVmDatafile returns NULL.  I'd change it to default to some safe value, but I don't know what that safe value is.  I assume zero is wrong.

**Comment by zack-vii** [comment]
How about:

```
TreeDFREAD : %TREE-E-DFREAD, Error reading from datafile.
```

**Comment by zack-vii** [comment]
defualts to TreeERROR by default in current alpha
