### ISSUE TITLE
Could anyone share the file "JavaGetAllFrames.fun" etc ?

### ISSUE THREAD

**Issue by pyshi** [MDSplus/mdsplus#484]
According to the jScope Help Document,
 "JavaGetAllFrames.fun", "JavaGetFrameTimes.fun", "JavaGetFrameAt.fun" are necessary for jScpe to display image. But in the installtion folder "...\tdi", there is no such file. So, could anyone share them with me?

**Comment by GabrieleManduchi** [comment]
Those files were used in ancient jScope versions and are no more 
required. Please refer to the MDSplus tutorial for up-to-date documentation.

On 04/05/2016 16:57, pyshi wrote:

> According to the jScope Help Document,
> "JavaGetAllFrames.fun", "JavaGetFrameTimes.fun", "JavaGetFrameAt.fun" 
> are necessary for jScpe to display image. But in the installtion 
> folder "...\tdi", there is no such file. So, could anyone share them 
> with me?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/issues/484

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by pyshi** [comment]
Hi, Manduchi
Thanks for your valuable information. But could you enlighten me further on this problem indicated below :
After storing 26 frames of images(1024*200) via"PutSegment", I could read out the data by MatLab "GetSegment" correctly; but in jScope, error turns out saying "No Tree Node".

PS. In jTraverser, the node appears to be undefined, but with corret length (~42.6 MB).

**Comment by GabrieleManduchi** [comment]
Are you using MdsDataProvider?
What is the exact error message you get?
If you manage sending me the pulse file and jScope configuration (e.g. 
in google drive) we can diagnose better the problem

On 04/05/2016 18:47, pyshi wrote:

> Hi, Manduchi
> Thanks for your valuable information. But could you enlighten me 
> further on this problem indicated below :
> After storing 26 frames of images(1024*200) via"PutSegment", I could 
> read out the data by MatLab "GetSegment" correctly; but in jScope, 
> error turns out saying "No Tree Node".
> 
> PS. In jTraverser, the node appears to be undefined, but with corret 
> length (~42.6 MB).
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/MDSplus/mdsplus/issues/484#issuecomment-216927371

## 

Gabriele Manduchi

Istituto Gas Ionizzati del CNR
Consorzio RFX - Associazione EURATOM/ENEA sulla Fusione
Corso Stati Uniti 4, 35127 Padova - Italy
ph +39-049-829-5039/-5000 fax +39-049-8700718
mailto:gabriele.manduchi@igi.cnr.it, http://www.igi.cnr.it

**Comment by pyshi** [comment]
Yes, I am using MdsDataProvider.
The error message is shown below:
![errimg](https://cloud.githubusercontent.com/assets/19190104/15038849/2bd80f90-12da-11e6-8364-e03060cfcac4.PNG)

In addition, other related pulse files and jScope file is being sent to your email.

Thanks very much.

**Comment by zack-vii** [comment]
Please reopen this issue if it is still unresolved. I am closing it for now since it has been inactive for several moth now.
