### ISSUE TITLE
LabView mdsplus_connection_putData Can only be Scalar or Array. Need to write 2 and 3 (video) dimension data to server.

### ISSUE THREAD

**Issue by fehlingd** [MDSplus/mdsplus#492]

**Comment by fehlingd** [comment]
2 and 3 dimension data to server

**Comment by pyshi** [comment]
I suggest one possible solution logic: 1. in LabVIew, call "MdsValue" function in the "MdsLib" library using "Call Library Function.vi"--> 2. this function could interpret TDI command, for your case "Build_Signal()" could help. 
More detial on the usage of this function including to write 3D data is in http://www.mdsplus.org/old/tdi/TDI_B2.HTML#build_signal

Hope it helps.
