### ISSUE TITLE
strange incomplete tdi functions

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#535]
what is the purpose of "tdi/GetDbInfo.fun"
and "tdi/fintreedir.fun" depends on "tdi/findtree.fun" which does not exist.
I am pretty sure there are more old corrupted tdi functions that could be removed/fixed.

**Comment by tfredian** [comment]
Good points. At some point we should make an effort to weed out obsolete tdi fun's and perhaps add new ones. Many of the fun's could probably be better implemented in python and python could easily be used to implement other useful helper functions. I've put in a pull request to remove the fun's mentioned and will commit it as soon as the tests finish.
