### ISSUE TITLE
Debian repo out of date

### ISSUE THREAD

**Issue by bstandley** [MDSplus/mdsplus#572]
I think there may be something mis-configured in the build chain for Debian packages.  My machine is stuck on 7.0.284 despite having the appropriate line
`deb http://www.mdsplus.org/dist/DebianWheezy/repo MDSplus alpha`
in the file `/etc/apt/sources.list.d/mdsplus.list` and regularly running `apt-get update && apt-get upgrade`.

Poking around http://www.mdsplus.org/dist/DebianWheezy/repo I noticed many of the files have not changed since May 22, which is indeed when 7.0.284 was built.  Could it be related to https://github.com/MDSplus/mdsplus/commit/5048d899191ccfd4660a2edcd43ab35b15d9a94f?

**Comment by tfredian** [comment]
IHmmm. I'll try to get this fixed asap.

**Comment by tfredian** [comment]
I think this is now fixed in alpha https://github.com/MDSplus/mdsplus/commit/117147a502a8567ee49297a212f13b654d78b037 and stable https://github.com/MDSplus/mdsplus/commit/97cea99ed202a425eb1c02c2d6f22e2f9d69d52b .
