### ISSUE TITLE
Bad library name breaks Intel compilation

### ISSUE THREAD

**Issue by ZedThree** [MDSplus/mdsplus#574]
The following lines in [`configure.ac`](https://github.com/MDSplus/mdsplus/blob/alpha/configure.ac#L81-L82):

```
AC_CHECK_LIB(socket,socket,SOCKETLIB="-l socket",SOCKELIB="")
AC_CHECK_LIB(nsl,inet_addr,NSLLIB="-l nsl",NSLLIB="")
```

have spaces between the flag and the library name, which causes the Intel compiler (v14 at least) to choke. Note also the first line has a typo ("SOCKELIB"). Removing the spaces results in a successful compliation.

It's possible those two lines aren't needed at all, as similar (more robust?) lines appear [later on as well](https://github.com/MDSplus/mdsplus/blob/alpha/configure.ac#L595-L596), except the latter lines set LIB{NSL,SOCKET} and the former set {NSL,SOCKET}LIB.

I can submit a pull request if it's clear one of the sets is wrong.

**Comment by kgerickson** [comment]
All of these should be removed and replaced with a simple:

AC_SEARCH_LIBS([gethostbyname], [socket ws2_32], [], [], [nsl])

with some extra in there in case we don't want to link with those libs for every library, even if they don't need them.  But, to do this right, I need some more information on the platforms we support.  For Windows, it's easy -- everything is in ws2_32.  For linux and OSX, everything is in libc.  What platform uses libnsl?  Just Solaris?  And what platform uses libsocket?  Does anyone know?

EDIT:
Also, we should be replacing all instances of gethostbyname with getaddrinfo anyway.  The former is deprecated.  But the library search is still required.

**Comment by kgerickson** [comment]
I pushed a rewrite to kge-config-cleanup.  Let me know if that fixes your issue.  Ideally this should be tested on Windows and OSX before merging.

**Comment by kgerickson** [comment]
Is anyone able to test?
