### ISSUE TITLE
mds_compress2 missing in libMdsIpShr.a

### ISSUE THREAD

**Issue by transp** [MDSplus/mdsplus#608]
The symbol "mds_compress2" is only defined in libMdsIpShr.so and NOT in libMdsIpShr.a (nor in any other static library). I think the same is true for "mds_uncompress".
MDSplus master, no configure options (except --prefix), built with gcc 6.1.0 on Ubuntu 14.04.
This issue prevents build of static executables linked with MDSplus.

**Comment by tfredian** [comment]
fixed
