### ISSUE TITLE
mdsplus directory required for python 3?

### ISSUE THREAD

**Issue by mattngc** [MDSplus/mdsplus#613]
Hi,

I'm trying to load MDSplus for python 3 at AUG. I installed the python module using:

pip install --user mdsplus

Now I get the following error when importing mdsplus:
## In [1]: from MDSplus import connection

OSError                                   Traceback (most recent call last)
~/.local/lib/python3.3/site-packages/mdsplus-7.1.10-py3.3.egg/MDSplus/version.py in load_library(name)
     33         try:
---> 34             return C.CDLL('lib'+name+'.so')
     35         except:

/.../python33/python/3.3.6/lib/python3.3/ctypes/**init**.py in **init**(self, name, mode, handle, use_errno, use_last_error)
    352         if handle is None:
--> 353             self._handle = _dlopen(self._name, mode)
    354         else:

OSError: libMdsShr.so: cannot open shared object file: No such file or directory

However I know that these files available in the MDSplus path:

~> find $MDSPLUS_DIR -iname libMdsShr.so
/.../mdsplus/20130708/@sys/lib/libMdsShr.so

How do I tell the MDSplus python module where the MDSplus library files are?

**Comment by tfredian** [comment]
You need to make sure the libraries are in the directory search list defined by LD_LIBRARY_PATH. If they already are make sure your python3 is the same architecture as the MDSplus libraries installed (i.e. if the python3 was 32-bit it could not load 64-bit libraries).

**Comment by mattngc** [comment]
Thanks for the fast reply. That did work and fixed the original exception. However now I get a new exception. Would I need to build mdsplus specially for python 3? At the moment I'm just pointing it to the module available by default at AUG. 

## In [3]: from MDSplus import connection

AttributeError                            Traceback (most recent call last)
/.../.local/lib/python3.5/site-packages/MDSplus/treenode.py in _mimport(name, level)
      2     try:
----> 3         return __import__(name, globals(), level=level)
      4     except:

/.../.local/lib/python3.5/site-packages/MDSplus/mdsdcl.py in <module>()
     14 _mdsdcl=_ver.load_library('Mdsdcl')
---> 15 _mdsdcl_do_command_dsc=_mdsdcl.mdsdcl_do_command_dsc
     16 _mdsdcl_do_command_dsc.argtypes=[_C.c_char_p, _C.POINTER(_desc.descriptor_xd), _C.POINTER(_desc.descriptor_xd)]

/.../anaconda/amd64_sles11/3/2.5.0/lib/python3.5/ctypes/**init**.py in **getattr**(self, name)
    359             raise AttributeError(name)
--> 360         func = self.**getitem**(name)
    361         setattr(self, name, func)

/.../anaconda/amd64_sles11/3/2.5.0/lib/python3.5/ctypes/**init**.py in **getitem**(self, name_or_ordinal)
    364     def **getitem**(self, name_or_ordinal):
--> 365         func = self._FuncPtr((name_or_ordinal, self))
    366         if not isinstance(name_or_ordinal, int):

AttributeError: /afs/ipp/tok/soft/mdsplus/20130708/@sys/lib/libMdsdcl.so: undefined symbol: mdsdcl_do_command_dsc

**Comment by tfredian** [comment]
The problem is probably that you are using a very old version of MDSplus if the directory is an indication of the date it was built. What platform are you running on? If we support the platform you are using could you just install MDSplus locally on your system using the repositories on http://www.mdsplus.org/index.php?title=Downloads&page=Software%2FDownloads? The version of the python module you are getting from pip requires a more recent version of MDSplus installed.

**Comment by mattngc** [comment]
ah, thanks. I'll have to chase this up with the local system administrators. We can close the issue as you solved the original problem.
