### ISSUE TITLE
missing 'make distclean'

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#680]
When running deploy/build.sh after executing ./configure . The build terminates suggesting to run 'make distclean'. However, there is no setup for 'make distclean' and 'make clean' does not fulfill the job.
It not urgent or anything but a nice to have.

```
configure: error: source directory already configured; run "make distclean" there first
```

**Comment by tfredian** [comment]
I agree the clean options in the top level Makefile needs a lot of work. There is a full_clean which kind of works but not completely and the diskclean does not exist while the aclocal.m4 suggests doing make distclean.

I normally don't run the build.sh script inside the source tree which makes things a little easier to deal with (or even configure for that matter). I use a different directory outside of the sources and do ${srcdir}/deploy/build.sh in that build directly (or ${srcdir}/configure). At this point the srcdir remains pristine and you can just rm all the files in the build directory tree when done.

**Comment by tfredian** [comment]
make distclean added
