### ISSUE TITLE
calling python functions from tdi does not support _variables

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#78]
This is probably one for Tom.
The variable type "Ident" should not be passes as object of itself but its content.
Or in short: Variables should be evaluated (one layer) before sending to python.

``` tdi
_a=1
pytest(_a)
```

returns

``` tdi
"\<class \'MDSplus.ident.Ident'\>"
```

instead of

``` tdi
"<class 'MDSplus.mdsscalar.Int32'>"
```

Since the variable does not exist inside the python environment getting its value will fail.
The same holds for MDSplus.tdibuiltins.builtins_other.*, such as IF_ERROR. However, these could be buffered using:

``` tdi
_b=IF_ERROR(_a,*);pytest(_b)
```

pytest.py:

``` python
def pytest ( arg ):
    return str(type(arg))
```

**Comment by tfredian** [comment]
I can't reproduce this problem either.

==== pytest.py ====
def pytest(arg):
   print(type(arg))

#    return arg.data()

[twf@fc22-vm tdi]$ tditest
_a=42
_a=42
42
pytest(_a)
pytest(_a)
<class 'MDSplus.ident.Ident'>
42

-tom

**Comment by zack-vii** [comment]
Hmm, after some resetting, it works now on my machine, too.
Thanks for testing and verifying that it should work.
