### ISSUE TITLE
Python API in master broken?

### ISSUE THREAD

**Issue by taerath** [MDSplus/mdsplus#785]
Hello,

I tried to install the Python interface from current git master, but `python3 setup.py install --user` ends with a worrying

```
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing MDSplus-1.0-py3.5.egg
creating /home/nikratio/.local/lib/python3.5/site-packages/MDSplus-1.0-py3.5.egg
Extracting MDSplus-1.0-py3.5.egg to /home/nikratio/.local/lib/python3.5/site-packages
Sorry: TabError: inconsistent use of tabs and spaces in indentation (mdsscalar.py, line 74)
Adding MDSplus 1.0 to easy-install.pth file
```

And indeed, when trying to use it:

```
$ python3 py3bug.py 
Error importing MDSplus package: inconsistent use of tabs and spaces in indentation (mdsscalar.py, line 74)
Traceback (most recent call last):
  File "py3bug.py", line 10, in <module>
    tree = MDSplus.Tree(TREENAME, -1, 'New')
AttributeError: module 'MDSplus' has no attribute 'Tree'
```

**Comment by tfredian** [comment]
Sorry for the confusion but the master branch in the MDSplus/mdsplus repository is very obsolete and not currently used or updated. Instead please use the alpha branch to test the most up to date versions or the stable branch to get the source code for the stable release.

**Comment by taerath** [comment]
Ah, ok. Out of curiosity: is there any reason to not just delete the master branch then and work with just stable and alpha?

**Comment by tfredian** [comment]
Good idea... master is now gone. There is an old_master branch now just in case.
