### ISSUE TITLE
Stable package for Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by diogoff** [MDSplus/mdsplus#795]
Desperately need this. Is it coming anytime soon?
Thanks.

**Comment by tfredian** [comment]
I would suggest trying the Ubuntu14 alpha repository. The current alpha release will soon be promoted to the stable branch  and should be safe to use at this point. We will look into adding Ubuntu16 to our list of supported platforms in the future.

**Comment by tfredian** [comment]
I believe we now have stable releases for Ubuntu16 so closing this issue now. Reopen with more details if still a problem.
