### ISSUE TITLE
Julia Interface

### ISSUE THREAD

**Issue by lstagner** [MDSplus/mdsplus#8]
[Julia](http://julialang.org/) is a high performance programming language targeted towards scientific computing. It has syntax similar to Python but with C like speed. I have begun to use it in my own research and an MDSplus interface would be very helpful. 

This could potentially be easily implemented by leveraging Julia's built in [C interoperability](http://docs.julialang.org/en/release-0.3/manual/calling-c-and-fortran-code/) to wrap MDSplus's existing C interface

**Comment by tfredian** [comment]
We will definitely explore adding an MDSplus interface to Julia. Thanks 
for the suggestion.

-tom

**Comment by lstagner** [comment]
I had a bit of free time so I coded up a working prototype.
https://github.com/lstagner/MDSplus.jl

Heres an example

``` julia
function get_signal_length(sig)
    s = [0]
    idesc = descr(Int32, size(s), s)
    stat = MdsValue("SIZE($sig)", idesc)
    return s[1]
end

function run_example(shot)
    socket = MdsConnect("atlas.gat.com")

    stat = MdsOpen("EFIT01",shot)

    s = get_signal_length("\\AMINOR")

    data = zeros(Float64, s)
    sigdesc = descr(data)
    stat = MdsValue("\\AMINOR", sigdesc)

    time = zeros(Float64, s)
    timedesc = descr(time)
    stat = MdsValue("DIM_OF(\\AMINOR)", timedesc)

    for i=1:10
        println(@sprintf("%2i X: %6.2f Y: %6.2f",i,time[i],data[i]))
    end

    MdsDisconnect()
end

run_example(107000)
```

It is a bit basic but it works.

**Comment by joshStillerman** [comment]
Luke -

   Sounds great! Thanks.  Things have been very crazy here with the the 
Alcator C-Mod experiment ending etc...  I will try this out very soon!

THANKS

josh

**Comment by joshStillerman** [comment]
Cool -

   I just tried it out.  And it appears to work!  Thanks.  I want to 
learn more about how to use Julia.  I am wondering if there is a 
mechanism to avoid pre-allocating the buffers ?

-Josh

**Comment by lstagner** [comment]
If there is a way to query the MDSplus server to get the data type and size of the variable then the you can dynamically create the correct data buffer. The variable description contains a reference to this buffer so that when you call MdsValue it uses it instead of allocating a separate data buffer and copying the results. 

It is also possible to [get data directly from a pointer](http://docs.julialang.org/en/release-0.5/manual/calling-c-and-fortran-code/#accessing-data-through-a-pointer) if you know what its format is.

**Comment by joshStillerman** [comment]
I just tried using the python objects directly in Julia and they work.  The syntax is a bit ugly, but they could be wrapped in Julia objects to clean it up.

Here is an example that reads the plasma current from a C-Mod shot
```julia
$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.add("PyCall")
INFO: Package PyCall is already installed

julia> using PyCall

julia> @pyimport MDSplus

julia> tree = MDSplus.Tree("cmod", 1090909010)
PyObject Tree("CMOD",1090909010,"Normal")

julia> node = tree[:TIME_OF_SHOT]
PyObject \CMOD::TOP:TIME_OF_SHOT

julia> node[:data]()
"11:34:21 AM"

julia> node[:record]
PyObject \ENGINEERING::TOP.TORVAC:T0TIME

julia> ip = tree[:getNode]("\\IP")
PyObject \MAGNETICS::IP

julia> ip[:record]
PyObject Build_Signal(Build_With_Units(\MAGNETICS::MAG_ROGOWSKI.SIGNALS:ROG_FG + 2100. * \MAGNETICS::BTOR, "ampere"), *, DIM_OF(\MAGNETICS::BTOR))

julia> y = ip[:data]()
13312-element Array{Float32,1}:
 -937.377 
 -313.142 
 -624.235 
 -313.142 
 -313.142 
    0.0   
 -313.142 
    2.0493
    0.0   
    0.0   
    ⋮     
  998.856 
  683.665 
  996.807 
  994.758 
  992.708 
  992.708 
  996.807 
  683.665 
  683.665 

julia> ip = tree[:_IP]
PyObject \MAGNETICS::IP

julia> ip_values = tree[:_IP][:data]()
13312-element Array{Float32,1}:
 -937.377 
 -313.142 
 -624.235 
 -313.142 
 -313.142 
    0.0   
 -313.142 
    2.0493
    0.0   
    0.0   
    ⋮     
  998.856 
  683.665 
  996.807 
  994.758 
  992.708 
  992.708 
  996.807 
  683.665 
  683.665 

julia> 
```

One thing that apparently is not possible, is implementing the magic methods that do not have fixed names.  In python you can say:
```python
child = Tree.CHILD
node = child.SOME.CHILD
```
and 
```
child will be a node that is the top nodes child or member named 'CHILD'
node will be a node that is the child or member of the node called 'SOME' that is a child or member of child
```
There is no mechanism in Julia to implement these properties (and methods) that do not have fixed names.  See: [Julia Issue 1974](https://github.com/JuliaLang/julia/issues/1974)

**Comment by rohong** [comment]
To get GA data from MDSplus using PTDATA, one can try folowing:

```
usimg PyCall
@pyimport MDSplus
conn = MDSplus.Connection("atlas.gat.com")
pname = "Ip"
shot = 150136
y = conn[:get]("_s=ptdata('$pname',  $shot)")
t = conn[:get]("dim_of(_s")
units = conn[:get]("units(_s)")

```
