### ISSUE TITLE
help text for device nodes read from parts field

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#829]
An extra entry 'help' in dictionaries of device's parts field could be used to display device and node specific help upon allowed keywords assumed units etc. it could be accessed easily via python, i.e. a python script in the tdi path. The jTraverser could retrieve the information if available and provide the user via tooltipboxes with additional information.

e.g.
```pyhton
{'path':'TRIGGER_EDGE', 'type':'text', 'options':('no_write_shot',), 'help':'rising or falling'}
```

**Comment by zack-vii** [comment]
alternatively one could add meta-information as ExtendedAttribute to any node with getHelp(nid) setHelp(nid,desc)

**Comment by joshStillerman** [comment]
The device class 'PARTS' member could have help strings for its elements. This way the fields could be documented in place, and the part names of the device could help.

Something like:

tcl> help /device model
tcl>help /device model field
or
tcl>help/device model.field
