### ISSUE TITLE
URGENT: python tests are not properly executed in current alpha

### ISSUE THREAD

**Issue by zack-vii** [MDSplus/mdsplus#834]
python tests are not performed in Jenkins!
Currently, executing
```bash
make tests
```
in "mdsobjects/python/tests" does not properly execute the python test suite. The suite will mark all UnitTests as PASS without actually executing them. The error is most likely in testing/testing.py which would be @AndreaRigoni 's field of expertise ?!

**Comment by tfredian** [comment]
Not sure what tests you are referring to. The configured set of python tests seem to be executing as indicated in the build logs and the individual test logs in the workspace. It is only configured to do data, tree and segment tests.

**Comment by zack-vii** [comment]
Des they show nice results, however. The test have not been run at all. Even if you deliberately plant an exception in one if the tests, it will pass. The tests suite returns almost instantly as if set everything up but then forgets to run the testunit.

Sent from my Windows Phone
________________________________

**Comment by AndreaRigoni** [comment]
Hi Timo, I'm working on it sorry.

**Comment by tfredian** [comment]
I believe this has been fixed by Andrea so I am closing it for now.
