### ISSUE TITLE
Serious problem with original_part_name fix made last week

### ISSUE THREAD

**Issue by tfredian** [MDSplus/mdsplus#838]
The fix made to deal with the original_part_name node characteristic issue with python devices is extremely inefficient. The code added to TreeNode.__init__ can be quite costly since it is done for every instantiation of a TreeNode object.  When n=tree.getNodeWild('***') is done on one of the CMOD subtrees (which has ~4k nodes in it) it takes 31 seconds to complete! If you do n=Data.execute('getnci("***","nid_number")  it takes all of .04 seconds! We will need to reestablish a less costly approach which is only paid when you attempt to get the original part name of a device node. It's still not clear when/why this broke in the first place.

**Comment by zack-vii** [comment]
issue was in getNodeWild which invoked getNodeWildIter of Tree instead of _treeshr
getNodeWildIter instantiates the output as TreeNode however only the nid number is used.
cleanup and fix in #839
