### ISSUE TITLE
java paths improperly installed on OSX

### ISSUE THREAD

**Issue by amicitas** [MDSplus/mdsplus#878]
After installing the most recent stable OS X installer (MDSplus 7.1.14) jTraverser is no longer working.  The jTraverser windows opens, but provides errors when trying to open a tree.  The error that I get is:

`Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no JavaMds in java.library.path`

Full error attached.
Currently using OS X 10.11.6 (15G1217).

[20170404_jTraverser_error.txt](https://github.com/MDSplus/mdsplus/files/893666/20170404_jTraverser_error.txt)

**Comment by joshStillerman** [comment]
I am pretty sure this is due to the macintosh SIP protection.  We have 
found that the easiest fix is to disable it (requires a reboot).  I have 
not tested it, but someone suggested that:

$ sudo ln -s /usr/bin/java /usr/local/bin/java

will solve your problem.  Though I think you will run into trouble with 
other MDSplus things.  I will be very interested to hear if this 
suggestion works for you.

Disable SIP:

http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11


-Josh

**Comment by amicitas** [comment]
I tried creating the symbolic links, and also modifying the jTraverser scripts to use the new link; no change in the error message.  I think the problem is that newer versions of OS X no longer look at the DYLD library path environment variables.  I ran into something similar for one of my own projects, but I don't really remember how I solved this issue; I'll try to look into this further when I have a bit of time.

**Comment by joshStillerman** [comment]
OK -

   I think the next step is to try turning off SIP

**Comment by amicitas** [comment]
I have found several solutions that do not require disabling of SIP.

1.  Set the java.library.path from within Java rather than using the `DYLD_LIBRARY_PATH` environment variable. 
`$java -Xss5M -Djava.library.path=$MDSPLUS_DIR/${lib} jTraverser $1 $2 $3 $4 $5 $6 $7`
I believe that this can also be done programmatically by using `System.setProperty("java.library.path", "/usr/local/mdsplus/lib")`.

2. Running jTraverser from within the mdsplus lib directory:
`(cd $MDSPLUS_DIS/${lib} && exec env ...)`

3. Creating symbolic links of all the mdsplus shared libraries in `/usr/local/lib`. I have not actually tested this, though this will almost certainly work.

I have attached a working version of solution 1 below.

```java
#!/bin/sh
#!
#! display MDSplus java traverser.
#
java=`which java`
if ( uname -p | grep 64 > /dev/null )
then
  if (file -L $java } grep 64i-bit > /dev/null )
  then 
    lib=lib64
  else
    lib=lib32
  fi
else
  lib=lib
fi
exec env \
CLASSPATH=$MDSPLUS_DIR/java/classes/jTraverser.jar:$MDSPLUS_DIR/java/classes/jScope.jar:$MDSPLUS_DIR/java/classes/jDevices.jar \
$java -Xss5M -Djava.library.path=$MDSPLUS_DIR/${lib} jTraverser $1 $2 $3 $4 $5 $6 $7
```

**Comment by joshStillerman** [comment]
I have tested this on linux - works there also, so I made a pull request to update this in alpha.
THANKS
