### ISSUE TITLE
jScope launch script fails to set install lib dir in some linux distros

### ISSUE THREAD

**Issue by AndreaRigoni** [MDSplus/mdsplus#910]
Hi Josh / All,
 a recent Fix in https://github.com/MDSplus/mdsplus/blob/alpha/javascope/jScope.template for macos prevents the jScope to be started from linux Redhat 6.5

the problem seems related to the the $lib variable and the java argument -Djava.library.path=$MDSPLUS_DIR/${lib} added recently.

The script has a selection of lib from processor type and java version:
if ( uname -p | grep 64 > /dev/null )
then
  if (file -L $java } grep 64i-bit > /dev/null )
  then 
    lib=lib64
  else
    lib=lib32
  fi
else
  lib=lib
fi

But there seems to be an issue related to the variable value or the lib directory target which seems to be only lib in linux not lib32 or lin64. 

In my pc the command: uname -p  gives output: "unknown" so "lib" is correctly applied. But in RedHat 6.5  uname -p  gives: "x86_64" so the value lib64 or lib32 where the target install dir seems to be lib

**Comment by tfredian** [comment]
Fixed by https://github.com/MDSplus/mdsplus/pull/914 and https://github.com/MDSplus/mdsplus/pull/911

Josh fixed this issue.
New script should properly determine the architecture of the java command and pick the appropriate library directory to use.
