### ISSUE TITLE
ImportError: cannot import MDSplusERROR (Python devices)

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#929]
Dear all,

trying to develop our Devices in python we receive this error:

![mdsplusexception error](https://cloud.githubusercontent.com/assets/5898559/26456599/d622577c-416d-11e7-952f-ea63e28907b3.png)

We tried to debug this ourselves, the symbol MDSplusERROR seems to be missing. Also we are not able to find any reference to it in the reference documentation on the www.mdsplus.org website.

This error has been found on the Debian Linux distribution.

![mdsplusexception version](https://cloud.githubusercontent.com/assets/5898559/26456785/6da9378c-416e-11e7-8a3d-9811e79d6008.png)

Sincerely,

**Comment by tfredian** [comment]
Can you check to ensure you have the MDSplus python package installed that matches the version of MDSplus you have installed? You can do:

 $ python
 \>\>\> import MDSplus
 \>\>\> print(MDSplus.\_\_file\_\_)

and it should look something like:

/usr/lib/python2.7/site-packages/mdsplus-7.7.1-py2.7.egg/MDSplus/\_\_init\_\_.pyc

If you do not see something similar you might try doing as root:

\# cd /usr/local/mdsplus/mdsobjects/python
\# python setup.py install

I just tested the MDSplus module for stable version 7.7.1 and was able to successfully import MDSplusERROR.

Hope this helps.

**Comment by tfredian** [comment]
If you are using pip to install you can install from the /usr/local/mdsplus/mdsobjects/python version by doing: pip install /usr/local/mdsplus/mdsobjects/python (optionally adding --user and/or --upgrade options)

**Comment by alkhwarizmi** [comment]
Thank you Tom,

this solved the problem!

Sincerely,
