### ISSUE TITLE
remote signal put fails python 3.6 and windows 7

### ISSUE THREAD

**Issue by cameronsamuell** [MDSplus/mdsplus#978]
Hi, 

I had a problem whereby putting a signal to a local tree was successful but putting it to a remote tree using the python object orientated routines fails. I was able to put a numeric to both local and remote trees just fine and the trees are near-identical which points towards it being signal-specific.

Here is what i would be trying to do:
node = tree.getNode('PROCESSED:ACQUIRING')
acq_sig = mds.Signal(mds.makeArray(acq_volts), 'V', mds.makeArray(acq_times), 'ms')
node.putData(acq_sig)

It would fail with the following: 
OSError: exception: access violation reading oxFFFFFFFFFFFFFFFF

We were able to do a work around by building the signal and a thin client (i.e. a mds.Connection() object)

I don't know if this is relevant or not, but it mirrors a similar problem I had with Labview: local signals were fine but those to a remote server were not.

**Comment by tfredian** [comment]
Can you tell us which release version of MDSplus is installed on your Windows system? If it is a relatively recent version you can use the "show version" command in mdstcl. If you have not updated MDSplus recently you might try doing so to see if the problem still persists. If you continue to have the problem on recent releases of MDSplus we will try to replicated the problem and hopefully provide a fix.

It shouldn't be relevant to the access violation problem but assuming that you are trying to associate units to the value and timebase of the signal you should do the following:

y=mds.makeArray(acq_volts)
y.units='V'
x=mds.makeArray(acq_times)
x.units='ms'
acq_sig=mds.Signal(y,None,x)
The Signal constructor arguments are (value, raw, dim0[,dim1,...dimn). In python units are assigned to MDSplus data items using item.units=units-string.

**Comment by tfredian** [comment]
I tested this with the latest alpha release of MDSplus and the latest anaconda3 and it seems to work. However I ran into a problem with the latest stable release of MDSplus. That release at least on Windows is having trouble returning floating point arrays. It does not get an access violation but complains about the datatype being returned when retrieving double or single floating point arrays. I will start another issue for this new problem and will try to track it down. In the mean time I would recommend using the latest MDSplus alpha release. To install the MDSplus module in anaconda, the best approach is to do:

pip install [--user] "C:\Program Files\MDSplus\mdsobjects\python"

This ensures that the MDSplus python module version matches that of the MDSplus libraries installed on your system.

**Comment by cameronsamuell** [comment]
Thanks for taking a look. 

It's a relatively recent MDSPlus install - 7.7.1 
It's not trivial to update the MDSPlus versions as the computer doesn't connect to the internet but i could do it. The system is approaching operational status so I'd prefer to to mess with the versions on this system until we have a maintenance window (in about a month). 

The floating point thing is interesting, however i would have thought such a thing would affect the local and remote puts equally, whereas this is just a problem with a connection to a remote server.

**Comment by tfredian** [comment]
I have been able to reproduce this problem and will look into providing a fix. It seems to only occur when using thick client mode (i.e. tree_path=host::). I did not see the problem when using distributed client mode where the tree path is defined as host::/directory-spec-where-tree-lives.

**Comment by cameronsamuell** [comment]
That fits with my experience - I used the distributed client mode as a workaround.

**Comment by tfredian** [comment]
I am assuming the fix on Jul 24 resolved this issue. Please reopen if that is not the case.
