### ISSUE TITLE
traverser.bat problem in Alpha 7.15-5 Win10 64-bit

### ISSUE THREAD

**Issue by alkhwarizmi** [MDSplus/mdsplus#997]
Dear all,

after setup the traverser.bat file contains the following single line
```
start "" javaw -jar "%MDSPLUS_DIR%\Java\Classes\jTraverser.jar" %*
```
which doesn't work.

I solve the problem by modifying it to read:
```
start javaw -cp "%MDSPLUS_DIR%\Java\Classes\jTraverser.jar" jTraverser
```
although I am not sure if the `%*` is something meant to be passed as command line argument by some applications. In my application (making a shortcut to start jTraverser) the `%*` is annoying, because I can't input the tree name with the mouse.

Apart of this, the right string should be ok from old commit  [fd39554] (sept. 2015), but it is not installed correctly at the moment.

Sincerely,

**Comment by alkhwarizmi** [comment]
Dear all,

I tried out the `%*` stuff again and I found out that it does not pose problems nor for the shortcut, nor when called from command line. Probably I did some mistake when I tried out the thing the first time.

Cheers,

**Comment by zack-vii** [comment]
Dear all,

to give some insight to the %* argument. jTraverser accepts arguments that are passed to the java executable, which will allow to open a specific tree,shot immediately. %* is the windows version of the bash "$@" and allows to pass an arbitrary number of arguments to the java program thou the batch call, i.e. you can call

> traverser.bat %server% %tree% %shot% -readonly

to connect to a server and open a shot of a tree (server is for jTraverser2 only)

It does not make sense to add it in a short-cut, though. Instead, you would put the arguments directly.

Cheers

**Comment by alkhwarizmi** [comment]
Hallo Zack,

what about the fact that on a re-install one gets a not working traverser.bat file like this below?
```
start "" javaw -jar "%MDSPLUS_DIR%\Java\Classes\jTraverser.jar" %*
```

Sincerely,

**Comment by zack-vii** [comment]
O sorry I oversaw that i mad a fix for the new release. The reason for the wrong code is that we have an experimental version 2 of the javatraverser with many more features such as dynamic tree_path adaptation (you can open trees by drag&drop them onto the jar-file or open them by  "javaw -jar jTraverser2.jar C:\path\to\tree_model.tree"), thin client, enhanced data monitor/editors, and much more. Its source is available in the gitlab alpha but you may need to compile it yourself.
